// Generated by Kukicha (requires Go 1.26+)

package mcp_test

import (
	"context"
	"fmt"
	mcppkg "github.com/kukichalang/kukicha/stdlib/mcp"
	"github.com/kukichalang/kukicha/stdlib/test"
	gomcp "github.com/modelcontextprotocol/go-sdk/mcp"
	"testing"
)

//line stdlib/mcp/mcp_test.kuki:13
func TestSchemaHelpers(t *testing.T) {
//line stdlib/mcp/mcp_test.kuki:14
	t.Run("Prop builds a SchemaProperty", func(t *testing.T) {
//line stdlib/mcp/mcp_test.kuki:15
		p := mcppkg.Prop("path", "string", "File path")
//line stdlib/mcp/mcp_test.kuki:16
		test.AssertEqual(t, p.Name, "path")
//line stdlib/mcp/mcp_test.kuki:17
		test.AssertEqual(t, p.Type, "string")
//line stdlib/mcp/mcp_test.kuki:18
		test.AssertEqual(t, p.Description, "File path")
	})
//line stdlib/mcp/mcp_test.kuki:21
	t.Run("Schema produces an object with properties", func(t *testing.T) {
//line stdlib/mcp/mcp_test.kuki:22
		s := mcppkg.Schema([]mcppkg.SchemaProperty{mcppkg.Prop("path", "string", "File path"), mcppkg.Prop("limit", "integer", "Max items")})
//line stdlib/mcp/mcp_test.kuki:26
		test.AssertEqual(t, s["type"], "object")
//line stdlib/mcp/mcp_test.kuki:28
		props, ok := s["properties"].(map[string]any)
//line stdlib/mcp/mcp_test.kuki:29
		test.AssertTrue(t, ok)
//line stdlib/mcp/mcp_test.kuki:30
		pathProp, ok2 := props["path"].(map[string]any)
//line stdlib/mcp/mcp_test.kuki:31
		test.AssertTrue(t, ok2)
//line stdlib/mcp/mcp_test.kuki:32
		test.AssertEqual(t, pathProp["type"], "string")
//line stdlib/mcp/mcp_test.kuki:33
		test.AssertEqual(t, pathProp["description"], "File path")
	})
//line stdlib/mcp/mcp_test.kuki:36
	t.Run("Required adds a required list", func(t *testing.T) {
//line stdlib/mcp/mcp_test.kuki:37
		s := mcppkg.Required(mcppkg.Schema([]mcppkg.SchemaProperty{mcppkg.Prop("path", "string", "File path")}), []string{"path"})
//line stdlib/mcp/mcp_test.kuki:42
		required, ok := s["required"].([]string)
//line stdlib/mcp/mcp_test.kuki:43
		test.AssertTrue(t, ok)
//line stdlib/mcp/mcp_test.kuki:44
		test.AssertEqual(t, len(required), 1)
//line stdlib/mcp/mcp_test.kuki:45
		test.AssertEqual(t, required[0], "path")
	})
}

//line stdlib/mcp/mcp_test.kuki:49
func TestResultHelpers(t *testing.T) {
//line stdlib/mcp/mcp_test.kuki:50
	text := mcppkg.TextResult("hello")
//line stdlib/mcp/mcp_test.kuki:51
	test.AssertNotNil(t, text)
//line stdlib/mcp/mcp_test.kuki:53
	errRes := mcppkg.ErrorResult("boom")
//line stdlib/mcp/mcp_test.kuki:54
	test.AssertNotNil(t, errRes)
}

//line stdlib/mcp/mcp_test.kuki:58
func TestContentTypeAliases(t *testing.T) {
//line stdlib/mcp/mcp_test.kuki:59
	items := make([]any, 4)
//line stdlib/mcp/mcp_test.kuki:60
	items[0] = &gomcp.AudioContent{MIMEType: "audio/mp3"}
//line stdlib/mcp/mcp_test.kuki:61
	items[1] = &gomcp.ResourceLink{URI: "file:///foo.txt"}
//line stdlib/mcp/mcp_test.kuki:62
	items[2] = &gomcp.EmbeddedResource{Resource: &gomcp.ResourceContents{Text: "hello"}}
//line stdlib/mcp/mcp_test.kuki:63
	items[3] = &gomcp.ResourceContents{URI: "file:///bar.txt", Text: "bar"}
//line stdlib/mcp/mcp_test.kuki:66
	_, ok1 := items[0].(*mcppkg.AudioContent)
//line stdlib/mcp/mcp_test.kuki:67
	test.AssertTrue(t, ok1)
//line stdlib/mcp/mcp_test.kuki:70
	_, ok2 := items[1].(*mcppkg.ResourceLink)
//line stdlib/mcp/mcp_test.kuki:71
	test.AssertTrue(t, ok2)
//line stdlib/mcp/mcp_test.kuki:74
	_, ok3 := items[2].(*mcppkg.EmbeddedResource)
//line stdlib/mcp/mcp_test.kuki:75
	test.AssertTrue(t, ok3)
//line stdlib/mcp/mcp_test.kuki:78
	_, ok4 := items[3].(*mcppkg.ResourceContents)
//line stdlib/mcp/mcp_test.kuki:79
	test.AssertTrue(t, ok4)
}

//line stdlib/mcp/mcp_test.kuki:85
func TestCallToolRichContent(t *testing.T) {
//line stdlib/mcp/mcp_test.kuki:86
	ctx := context.Background()
//line stdlib/mcp/mcp_test.kuki:87
	cTransport, sTransport := gomcp.NewInMemoryTransports()
//line stdlib/mcp/mcp_test.kuki:89
	richContent := []gomcp.Content{&gomcp.TextContent{Text: "hello"}, &gomcp.ImageContent{MIMEType: "image/png"}, &gomcp.AudioContent{MIMEType: "audio/wav"}, &gomcp.ResourceLink{URI: "file:///doc.txt"}, &gomcp.EmbeddedResource{Resource: &gomcp.ResourceContents{Text: "embedded text"}}}
//line stdlib/mcp/mcp_test.kuki:96
	richResult := &gomcp.CallToolResult{Content: richContent}
//line stdlib/mcp/mcp_test.kuki:97
	emptySchema := map[string]any{"type": "object", "properties": map[string]any{}}
//line stdlib/mcp/mcp_test.kuki:99
	server := gomcp.NewServer(&gomcp.Implementation{Name: "test", Version: "1.0"}, nil)
//line stdlib/mcp/mcp_test.kuki:100
	server.AddTool(&gomcp.Tool{Name: "rich", InputSchema: emptySchema}, func(ctx context.Context, req *gomcp.CallToolRequest) (*gomcp.CallToolResult, error) {
//line stdlib/mcp/mcp_test.kuki:101
		return richResult, nil
	})
//line stdlib/mcp/mcp_test.kuki:104
	ss, err_1 := server.Connect(ctx, sTransport, nil)
//line stdlib/mcp/mcp_test.kuki:104
	if err_1 != nil {
//line stdlib/mcp/mcp_test.kuki:104
		//line stdlib/mcp/mcp_test.kuki:105
		t.Fatalf("server connect failed: %v", err_1)
		//line stdlib/mcp/mcp_test.kuki:106
		return
	}
//line stdlib/mcp/mcp_test.kuki:108
	defer ss.Close()
//line stdlib/mcp/mcp_test.kuki:110
	client := gomcp.NewClient(&gomcp.Implementation{Name: "test-client", Version: "1.0"}, nil)
//line stdlib/mcp/mcp_test.kuki:111
	rawSession, err_2 := client.Connect(ctx, cTransport, nil)
//line stdlib/mcp/mcp_test.kuki:111
	if err_2 != nil {
//line stdlib/mcp/mcp_test.kuki:111
		//line stdlib/mcp/mcp_test.kuki:112
		t.Fatalf("client connect failed: %v", err_2)
		//line stdlib/mcp/mcp_test.kuki:113
		return
	}
//line stdlib/mcp/mcp_test.kuki:115
	defer rawSession.Close()
//line stdlib/mcp/mcp_test.kuki:117
	session := mcppkg.ConnectFromSession(rawSession)
//line stdlib/mcp/mcp_test.kuki:118
	result, err_3 := mcppkg.CallTool(ctx, session, "rich", map[string]any{})
//line stdlib/mcp/mcp_test.kuki:118
	if err_3 != nil {
//line stdlib/mcp/mcp_test.kuki:118
		//line stdlib/mcp/mcp_test.kuki:119
		t.Fatalf("CallTool failed: %v", err_3)
		//line stdlib/mcp/mcp_test.kuki:120
		return
	}
//line stdlib/mcp/mcp_test.kuki:122
	test.AssertEqual(t, result.Text, "hello\n[image: image/png]\n[audio: audio/wav]\n[resource: file:///doc.txt]\nembedded text")
//line stdlib/mcp/mcp_test.kuki:127
	test.AssertEqual(t, len(result.Content), 5)
//line stdlib/mcp/mcp_test.kuki:128
	test.AssertFalse(t, result.IsError)
}

//line stdlib/mcp/mcp_test.kuki:131
func TestPromptArgStruct(t *testing.T) {
//line stdlib/mcp/mcp_test.kuki:132
	a := mcppkg.PromptArg{Name: "text", Description: "Input text", Required: true}
//line stdlib/mcp/mcp_test.kuki:133
	test.AssertEqual(t, a.Name, "text")
//line stdlib/mcp/mcp_test.kuki:134
	test.AssertEqual(t, a.Description, "Input text")
//line stdlib/mcp/mcp_test.kuki:135
	test.AssertTrue(t, a.Required)
}

//line stdlib/mcp/mcp_test.kuki:138
func TestToolOptsZeroValue(t *testing.T) {
//line stdlib/mcp/mcp_test.kuki:139
	opts := mcppkg.ToolOpts{}
//line stdlib/mcp/mcp_test.kuki:140
	test.AssertFalse(t, opts.ReadOnly)
//line stdlib/mcp/mcp_test.kuki:141
	test.AssertFalse(t, opts.Destructive)
//line stdlib/mcp/mcp_test.kuki:142
	test.AssertFalse(t, opts.Idempotent)
//line stdlib/mcp/mcp_test.kuki:143
	test.AssertNil(t, opts.OutputSchema)
}

//line stdlib/mcp/mcp_test.kuki:146
func TestClientResourceStruct(t *testing.T) {
//line stdlib/mcp/mcp_test.kuki:147
	r := mcppkg.ClientResource{URI: "config://app", Name: "App", Description: "Config", MIMEType: "text/plain"}
//line stdlib/mcp/mcp_test.kuki:153
	test.AssertEqual(t, r.URI, "config://app")
//line stdlib/mcp/mcp_test.kuki:154
	test.AssertEqual(t, r.Name, "App")
//line stdlib/mcp/mcp_test.kuki:155
	test.AssertEqual(t, r.MIMEType, "text/plain")
}

//line stdlib/mcp/mcp_test.kuki:160
func TestServerRegistration(t *testing.T) {
//line stdlib/mcp/mcp_test.kuki:161
	server := mcppkg.New("test", "1.0")
//line stdlib/mcp/mcp_test.kuki:162
	schema := mcppkg.Required(mcppkg.Schema([]mcppkg.SchemaProperty{mcppkg.Prop("text", "string", "Text input")}), []string{"text"})
//line stdlib/mcp/mcp_test.kuki:167
	textFn := func(uri string) (string, error) {
//line stdlib/mcp/mcp_test.kuki:168
		return "version=1.0", nil
	}
//line stdlib/mcp/mcp_test.kuki:170
	mcppkg.TextResource(server, "config://app", "App config", "Configuration", textFn)
//line stdlib/mcp/mcp_test.kuki:172
	uriTemplate := (("users://" + "{") + "id}/profile")
//line stdlib/mcp/mcp_test.kuki:173
	mcppkg.TextResourceTemplate(server, uriTemplate, "User profile", "Per-user profile", textFn)
//line stdlib/mcp/mcp_test.kuki:175
	promptFn := func(args map[string]string) (string, error) {
//line stdlib/mcp/mcp_test.kuki:176
		txt := args["text"]
//line stdlib/mcp/mcp_test.kuki:177
		return fmt.Sprintf("Summarize: %v", txt), nil
	}
//line stdlib/mcp/mcp_test.kuki:179
	mcppkg.UserPrompt(server, "summarize", "Summarize text", []mcppkg.PromptArg{mcppkg.PromptArg{Name: "text", Required: true}}, promptFn)
//line stdlib/mcp/mcp_test.kuki:187
	toolFn := func(args map[string]any) (any, error) {
//line stdlib/mcp/mcp_test.kuki:188
		return "ok", nil
	}
//line stdlib/mcp/mcp_test.kuki:190
	mcppkg.ToolWithOpts(server, "read", "Read-only tool", schema, mcppkg.ToolOpts{ReadOnly: true}, toolFn)
//line stdlib/mcp/mcp_test.kuki:199
	richFn := func(ctx context.Context, tc *mcppkg.ToolContext, args map[string]any) (any, error) {
//line stdlib/mcp/mcp_test.kuki:200
		return "ok", nil
	}
//line stdlib/mcp/mcp_test.kuki:202
	mcppkg.ToolRich(server, "rich", "Tool with context", schema, richFn)
//line stdlib/mcp/mcp_test.kuki:204
	test.AssertNotNil(t, server)
}

//line stdlib/mcp/mcp_test.kuki:208
func TestCompletionRouter(t *testing.T) {
//line stdlib/mcp/mcp_test.kuki:209
	ctx := context.Background()
//line stdlib/mcp/mcp_test.kuki:210
	router := mcppkg.NewRouter()
//line stdlib/mcp/mcp_test.kuki:212
	router.AddPrompt("summarize", func(argName string, partial string, prevArgs map[string]string) []string {
//line stdlib/mcp/mcp_test.kuki:213
		if argName == "text" {
//line stdlib/mcp/mcp_test.kuki:214
			return []string{"hello world", "hello there"}
		}
//line stdlib/mcp/mcp_test.kuki:215
		return []string{}
	})
//line stdlib/mcp/mcp_test.kuki:218
	router.AddResource("config://app", func(argName string, partial string, prevArgs map[string]string) []string {
//line stdlib/mcp/mcp_test.kuki:219
		return []string{"version=1.0", "version=2.0"}
	})
//line stdlib/mcp/mcp_test.kuki:222
	handler := router.Handler()
//line stdlib/mcp/mcp_test.kuki:225
	promptReq := &gomcp.CompleteRequest{Params: &gomcp.CompleteParams{Ref: &gomcp.CompleteReference{Type: "ref/prompt", Name: "summarize"}, Argument: gomcp.CompleteParamsArgument{Name: "text", Value: "he"}}}
//line stdlib/mcp/mcp_test.kuki:232
	res, err := handler(ctx, promptReq)
//line stdlib/mcp/mcp_test.kuki:233
	test.AssertNil(t, err)
//line stdlib/mcp/mcp_test.kuki:234
	test.AssertEqual(t, len(res.Completion.Values), 2)
//line stdlib/mcp/mcp_test.kuki:235
	test.AssertEqual(t, res.Completion.Values[0], "hello world")
//line stdlib/mcp/mcp_test.kuki:238
	resReq := &gomcp.CompleteRequest{Params: &gomcp.CompleteParams{Ref: &gomcp.CompleteReference{Type: "ref/resource", URI: "config://app"}, Argument: gomcp.CompleteParamsArgument{Name: "key", Value: ""}}}
//line stdlib/mcp/mcp_test.kuki:245
	res2, err2 := handler(ctx, resReq)
//line stdlib/mcp/mcp_test.kuki:246
	test.AssertNil(t, err2)
//line stdlib/mcp/mcp_test.kuki:247
	test.AssertEqual(t, len(res2.Completion.Values), 2)
//line stdlib/mcp/mcp_test.kuki:250
	unknownReq := &gomcp.CompleteRequest{Params: &gomcp.CompleteParams{Ref: &gomcp.CompleteReference{Type: "ref/prompt", Name: "unknown"}, Argument: gomcp.CompleteParamsArgument{Name: "x", Value: ""}}}
//line stdlib/mcp/mcp_test.kuki:257
	res3, _ := handler(ctx, unknownReq)
//line stdlib/mcp/mcp_test.kuki:258
	test.AssertEqual(t, len(res3.Completion.Values), 0)
}
