// Generated by Kukicha (requires Go 1.26+)

package safe_test

import (
	"github.com/kukichalang/kukicha/stdlib/llm/safe"
	strpkg "github.com/kukichalang/kukicha/stdlib/string"
	"github.com/kukichalang/kukicha/stdlib/test"
	"testing"
)

//line stdlib/llm/safe/safe_test.kuki:10
func TestWrap(t *testing.T) {
//line stdlib/llm/safe/safe_test.kuki:11
	got := safe.Wrap("INPUT", "hello")
//line stdlib/llm/safe/safe_test.kuki:12
	test.AssertEqual(t, got, "<INPUT>\nhello\n</INPUT>")
}

//line stdlib/llm/safe/safe_test.kuki:14
func TestFrameNoBlocks(t *testing.T) {
//line stdlib/llm/safe/safe_test.kuki:15
	got := safe.Frame("rules", []string{})
//line stdlib/llm/safe/safe_test.kuki:16
	test.AssertEqual(t, got, "rules")
}

//line stdlib/llm/safe/safe_test.kuki:18
func TestFrameIncludesPreambleAndBlocks(t *testing.T) {
//line stdlib/llm/safe/safe_test.kuki:19
	block := safe.Wrap("DATA", "x")
//line stdlib/llm/safe/safe_test.kuki:20
	got := safe.Frame("rules", []string{block})
//line stdlib/llm/safe/safe_test.kuki:21
	if !strpkg.Contains(got, "rules") {
//line stdlib/llm/safe/safe_test.kuki:22
		t.Errorf("missing instructions in: %v", got)
	}
//line stdlib/llm/safe/safe_test.kuki:23
	if !strpkg.Contains(got, "UNTRUSTED DATA") {
//line stdlib/llm/safe/safe_test.kuki:24
		t.Errorf("missing preamble in: %v", got)
	}
//line stdlib/llm/safe/safe_test.kuki:25
	if !strpkg.Contains(got, "<DATA>\nx\n</DATA>") {
//line stdlib/llm/safe/safe_test.kuki:26
		t.Errorf("missing wrapped block in: %v", got)
	}
}

//line stdlib/llm/safe/safe_test.kuki:28
type TruncateCase struct {
	name string
	in   string
	n    int
	want string
}

//line stdlib/llm/safe/safe_test.kuki:34
func TestTruncate(t *testing.T) {
//line stdlib/llm/safe/safe_test.kuki:35
	cases := []TruncateCase{TruncateCase{name: "short unchanged", in: "abc", n: 10, want: "abc"}, TruncateCase{name: "exact length", in: "abc", n: 3, want: "abc"}, TruncateCase{name: "over length", in: "abcdef", n: 3, want: "abc"}, TruncateCase{name: "zero", in: "abc", n: 0, want: ""}, TruncateCase{name: "negative", in: "abc", n: -1, want: ""}}
//line stdlib/llm/safe/safe_test.kuki:42
	for _, tc := range cases {
//line stdlib/llm/safe/safe_test.kuki:43
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/llm/safe/safe_test.kuki:44
			test.AssertEqual(t, safe.Truncate(tc.in, tc.n), tc.want)
		})
	}
}

//line stdlib/llm/safe/safe_test.kuki:47
type SanitizeLineCase struct {
	name string
	in   string
	n    int
	want string
}

//line stdlib/llm/safe/safe_test.kuki:53
func TestSanitizeLine(t *testing.T) {
//line stdlib/llm/safe/safe_test.kuki:54
	cases := []SanitizeLineCase{SanitizeLineCase{name: "newlines to spaces", in: "a\nb", n: 100, want: "a b"}, SanitizeLineCase{name: "cr stripped", in: "a\rb", n: 100, want: "a b"}, SanitizeLineCase{name: "trims", in: "  hi  ", n: 100, want: "hi"}, SanitizeLineCase{name: "caps length", in: "abcdefghij", n: 4, want: "abcd"}, SanitizeLineCase{name: "trim then cap", in: "  abcdefgh  ", n: 4, want: "abcd"}}
//line stdlib/llm/safe/safe_test.kuki:61
	for _, tc := range cases {
//line stdlib/llm/safe/safe_test.kuki:62
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/llm/safe/safe_test.kuki:63
			test.AssertEqual(t, safe.SanitizeLine(tc.in, tc.n), tc.want)
		})
	}
}

//line stdlib/llm/safe/safe_test.kuki:66
type IsStructuralCase struct {
	name string
	in   string
	want bool
}

//line stdlib/llm/safe/safe_test.kuki:71
func TestIsStructural(t *testing.T) {
//line stdlib/llm/safe/safe_test.kuki:72
	cases := []IsStructuralCase{IsStructuralCase{name: "empty", in: "", want: false}, IsStructuralCase{name: "plain text", in: "hello world", want: false}, IsStructuralCase{name: "heading", in: "## Heading", want: true}, IsStructuralCase{name: "bullet dash", in: "- item", want: true}, IsStructuralCase{name: "bullet star", in: "* item", want: true}, IsStructuralCase{name: "blockquote", in: "> quote", want: true}, IsStructuralCase{name: "plus list", in: "+ item", want: true}, IsStructuralCase{name: "code fence", in: "```", want: true}}
//line stdlib/llm/safe/safe_test.kuki:82
	for _, tc := range cases {
//line stdlib/llm/safe/safe_test.kuki:83
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/llm/safe/safe_test.kuki:84
			test.AssertEqual(t, safe.IsStructural(tc.in), tc.want)
		})
	}
}
