// Generated by Kukicha (requires Go 1.26+)

package http

import (
	"errors"
	"fmt"
	"github.com/kukichalang/kukicha/stdlib/fetch"
	"github.com/kukichalang/kukicha/stdlib/json"
	kukistring "github.com/kukichalang/kukicha/stdlib/string"
	"github.com/kukichalang/kukicha/stdlib/validate"
	"html"
	"io"
	"net/http"
	"net/url"
	"slices"
	"strconv"
)

//line stdlib/http/http.kuki:17
const StatusOK = 200

//line stdlib/http/http.kuki:19
const StatusCreated = 201

//line stdlib/http/http.kuki:21
const StatusAccepted = 202

//line stdlib/http/http.kuki:23
const StatusNoContent = 204

//line stdlib/http/http.kuki:25
const StatusMovedPermanently = 301

//line stdlib/http/http.kuki:27
const StatusFound = 302

//line stdlib/http/http.kuki:29
const StatusNotModified = 304

//line stdlib/http/http.kuki:31
const StatusBadRequest = 400

//line stdlib/http/http.kuki:33
const StatusUnauthorized = 401

//line stdlib/http/http.kuki:35
const StatusForbidden = 403

//line stdlib/http/http.kuki:37
const StatusNotFound = 404

//line stdlib/http/http.kuki:39
const StatusMethodNotAllowed = 405

//line stdlib/http/http.kuki:41
const StatusConflict = 409

//line stdlib/http/http.kuki:43
const StatusGone = 410

//line stdlib/http/http.kuki:45
const StatusUnprocessableEntity = 422

//line stdlib/http/http.kuki:47
const StatusTooManyRequests = 429

//line stdlib/http/http.kuki:49
const StatusInternalServerError = 500

//line stdlib/http/http.kuki:51
const StatusBadGateway = 502

//line stdlib/http/http.kuki:53
const StatusServiceUnavailable = 503

//line stdlib/http/http.kuki:55
const StatusGatewayTimeout = 504

//line stdlib/http/http.kuki:58
const HeaderContentType = "Content-Type"

//line stdlib/http/http.kuki:60
const HeaderAuthorization = "Authorization"

//line stdlib/http/http.kuki:62
const HeaderAccept = "Accept"

//line stdlib/http/http.kuki:64
const HeaderCacheControl = "Cache-Control"

//line stdlib/http/http.kuki:66
const HeaderContentLength = "Content-Length"

//line stdlib/http/http.kuki:68
const HeaderUserAgent = "User-Agent"

//line stdlib/http/http.kuki:70
const HeaderXRequestID = "X-Request-Id"

//line stdlib/http/http.kuki:72
const HeaderXForwardedFor = "X-Forwarded-For"

//line stdlib/http/http.kuki:75
const ContentJSON = "application/json"

//line stdlib/http/http.kuki:77
const ContentHTML = "text/html; charset=utf-8"

//line stdlib/http/http.kuki:79
const ContentText = "text/plain; charset=utf-8"

//line stdlib/http/http.kuki:81
const ContentForm = "application/x-www-form-urlencoded"

//line stdlib/http/http.kuki:83
const ContentMultipart = "multipart/form-data"

//line stdlib/http/http.kuki:88
func WithCSRF(handler http.Handler) http.Handler {
//line stdlib/http/http.kuki:89
	protection := http.NewCrossOriginProtection()
//line stdlib/http/http.kuki:90
	return protection.Handler(handler)
}

//line stdlib/http/http.kuki:94
func Serve(addr string, handler http.Handler) error {
//line stdlib/http/http.kuki:95
	return http.ListenAndServe(addr, handler)
}

//line stdlib/http/http.kuki:103
func JSON(w http.ResponseWriter, value any) error {
//line stdlib/http/http.kuki:104
	w.Header().Set("Content-Type", "application/json")
//line stdlib/http/http.kuki:105
	return json.Write(w, value)
}

//line stdlib/http/http.kuki:110
func JSONStatus(w http.ResponseWriter, value any, status int) error {
//line stdlib/http/http.kuki:111
	w.Header().Set("Content-Type", "application/json")
//line stdlib/http/http.kuki:112
	w.WriteHeader(status)
//line stdlib/http/http.kuki:113
	return json.Write(w, value)
}

//line stdlib/http/http.kuki:117
func JSONCreated(w http.ResponseWriter, value any) error {
//line stdlib/http/http.kuki:118
	return JSONStatus(w, value, 201)
}

//line stdlib/http/http.kuki:123
func JSONError(w http.ResponseWriter, message string, status int) error {
//line stdlib/http/http.kuki:124
	w.Header().Set("Content-Type", "application/json")
//line stdlib/http/http.kuki:125
	w.WriteHeader(status)
//line stdlib/http/http.kuki:126
	errorBody := map[string]string{"error": message}
//line stdlib/http/http.kuki:127
	return json.Write(w, errorBody)
}

//line stdlib/http/http.kuki:131
func JSONBadRequest(w http.ResponseWriter, message string) error {
//line stdlib/http/http.kuki:132
	return JSONError(w, message, 400)
}

//line stdlib/http/http.kuki:136
func JSONUnauthorized(w http.ResponseWriter, message string) error {
//line stdlib/http/http.kuki:137
	return JSONError(w, message, 401)
}

//line stdlib/http/http.kuki:141
func JSONForbidden(w http.ResponseWriter, message string) error {
//line stdlib/http/http.kuki:142
	return JSONError(w, message, 403)
}

//line stdlib/http/http.kuki:146
func JSONNotFound(w http.ResponseWriter, message string) error {
//line stdlib/http/http.kuki:147
	return JSONError(w, message, 404)
}

//line stdlib/http/http.kuki:151
func JSONInternalError(w http.ResponseWriter, message string) error {
//line stdlib/http/http.kuki:152
	return JSONError(w, message, 500)
}

//line stdlib/http/http.kuki:160
func ReadJSON(r *http.Request, target any) error {
//line stdlib/http/http.kuki:161
	return json.ReadInto(r.Body, target)
}

//line stdlib/http/http.kuki:167
func ReadJSONAndClose(r *http.Request, target any) error {
//line stdlib/http/http.kuki:168
	defer r.Body.Close()
//line stdlib/http/http.kuki:169
	return json.ReadInto(r.Body, target)
}

//line stdlib/http/http.kuki:174
func ReadJSONLimit(r *http.Request, maxBytes int64, target any) error {
//line stdlib/http/http.kuki:175
	return json.ReadInto(io.LimitReader(r.Body, maxBytes), target)
}

//line stdlib/http/http.kuki:179
func GetQueryParam(r *http.Request, key string) string {
//line stdlib/http/http.kuki:180
	return r.URL.Query().Get(key)
}

//line stdlib/http/http.kuki:184
func GetQueryParamOr(r *http.Request, key string, defaultValue string) string {
//line stdlib/http/http.kuki:185
	value := r.URL.Query().Get(key)
//line stdlib/http/http.kuki:186
	if value == "" {
//line stdlib/http/http.kuki:187
		return defaultValue
	}
//line stdlib/http/http.kuki:188
	return value
}

//line stdlib/http/http.kuki:193
func GetQueryInt(r *http.Request, key string) (int, error) {
//line stdlib/http/http.kuki:194
	value := r.URL.Query().Get(key)
//line stdlib/http/http.kuki:195
	if value == "" {
//line stdlib/http/http.kuki:196
		return 0, fmt.Errorf("query parameter '%v' is required", key)
	}
//line stdlib/http/http.kuki:197
	val, err_1 := strconv.Atoi(value)
//line stdlib/http/http.kuki:197
	if err_1 != nil {
//line stdlib/http/http.kuki:197
		return 0, fmt.Errorf("query parameter '%v' must be an integer", key)
	}
//line stdlib/http/http.kuki:198
	return val, nil
}

//line stdlib/http/http.kuki:203
func GetQueryIntOr(r *http.Request, key string, defaultValue int) int {
//line stdlib/http/http.kuki:204
	value := r.URL.Query().Get(key)
//line stdlib/http/http.kuki:205
	if value == "" {
//line stdlib/http/http.kuki:206
		return defaultValue
	}
//line stdlib/http/http.kuki:207
	val, err_2 := strconv.Atoi(value)
//line stdlib/http/http.kuki:207
	if err_2 != nil {
//line stdlib/http/http.kuki:207
		return defaultValue
	}
//line stdlib/http/http.kuki:208
	return val
}

//line stdlib/http/http.kuki:214
func GetQueryBool(r *http.Request, key string) (bool, error) {
//line stdlib/http/http.kuki:215
	value := r.URL.Query().Get(key)
//line stdlib/http/http.kuki:216
	if value == "" {
//line stdlib/http/http.kuki:217
		return false, fmt.Errorf("query parameter '%v' is required", key)
	}
//line stdlib/http/http.kuki:218
	val, err_3 := validate.ParseBool(value)
//line stdlib/http/http.kuki:218
	if err_3 != nil {
//line stdlib/http/http.kuki:218
		return false, fmt.Errorf("query parameter '%v' must be a boolean", key)
	}
//line stdlib/http/http.kuki:219
	return val, nil
}

//line stdlib/http/http.kuki:224
func GetQueryBoolOr(r *http.Request, key string, defaultValue bool) bool {
//line stdlib/http/http.kuki:225
	value := r.URL.Query().Get(key)
//line stdlib/http/http.kuki:226
	if value == "" {
//line stdlib/http/http.kuki:227
		return defaultValue
	}
//line stdlib/http/http.kuki:228
	val, err_4 := validate.ParseBool(value)
//line stdlib/http/http.kuki:228
	if err_4 != nil {
//line stdlib/http/http.kuki:228
		return defaultValue
	}
//line stdlib/http/http.kuki:229
	return val
}

//line stdlib/http/http.kuki:233
func GetHeader(r *http.Request, key string) string {
//line stdlib/http/http.kuki:234
	return r.Header.Get(key)
}

//line stdlib/http/http.kuki:238
func GetHeaderOr(r *http.Request, key string, defaultValue string) string {
//line stdlib/http/http.kuki:239
	value := r.Header.Get(key)
//line stdlib/http/http.kuki:240
	if value == "" {
//line stdlib/http/http.kuki:241
		return defaultValue
	}
//line stdlib/http/http.kuki:242
	return value
}

//line stdlib/http/http.kuki:248
func NoContent(w http.ResponseWriter) {
//line stdlib/http/http.kuki:249
	w.WriteHeader(204)
}

//line stdlib/http/http.kuki:254
func Redirect(w http.ResponseWriter, url string) {
//line stdlib/http/http.kuki:255
	w.Header().Set("Location", url)
//line stdlib/http/http.kuki:256
	w.WriteHeader(302)
}

//line stdlib/http/http.kuki:261
func RedirectPermanent(w http.ResponseWriter, url string) {
//line stdlib/http/http.kuki:262
	w.Header().Set("Location", url)
//line stdlib/http/http.kuki:263
	w.WriteHeader(301)
}

//line stdlib/http/http.kuki:272
func SafeRedirect(w http.ResponseWriter, redirectURL string, allowedHosts ...string) error {
//line stdlib/http/http.kuki:273
	if redirectURL == "" {
//line stdlib/http/http.kuki:274
		return errors.New("redirect URL is empty")
	}
//line stdlib/http/http.kuki:278
	if kukistring.HasPrefix(redirectURL, "//") {
//line stdlib/http/http.kuki:279
		return fmt.Errorf("protocol-relative redirect '%v' is not allowed", redirectURL)
	}
//line stdlib/http/http.kuki:280
	parsed, err_5 := url.Parse(redirectURL)
//line stdlib/http/http.kuki:280
	if err_5 != nil {
//line stdlib/http/http.kuki:280
		return fmt.Errorf("invalid redirect URL: %v", err_5)
	}
//line stdlib/http/http.kuki:281
	if (parsed.Scheme == "") && (parsed.Host == "") {
//line stdlib/http/http.kuki:284
		if !kukistring.HasPrefix(redirectURL, "/") {
//line stdlib/http/http.kuki:285
			return errors.New("relative redirect must start with '/'")
		}
//line stdlib/http/http.kuki:286
		w.Header().Set("Location", redirectURL)
//line stdlib/http/http.kuki:287
		w.WriteHeader(302)
//line stdlib/http/http.kuki:288
		return nil
	}
//line stdlib/http/http.kuki:290
	if (parsed.Scheme != "http") && (parsed.Scheme != "https") {
//line stdlib/http/http.kuki:291
		return fmt.Errorf("redirect scheme '%v' is not allowed", parsed.Scheme)
	}
//line stdlib/http/http.kuki:292
	if slices.Contains(allowedHosts, parsed.Host) {
//line stdlib/http/http.kuki:293
		w.Header().Set("Location", redirectURL)
//line stdlib/http/http.kuki:294
		w.WriteHeader(302)
//line stdlib/http/http.kuki:295
		return nil
	}
//line stdlib/http/http.kuki:296
	return fmt.Errorf("redirect to '%v' is not in the allowed hosts list", parsed.Host)
}

//line stdlib/http/http.kuki:302
func SafeURL(tmpl string, pathParams map[string]string, queryParams map[string]string) (string, error) {
//line stdlib/http/http.kuki:303
	base, err_6 := fetch.URLTemplate(tmpl, pathParams)
//line stdlib/http/http.kuki:303
	if err_6 != nil {
//line stdlib/http/http.kuki:303
		return "", err_6
	}
//line stdlib/http/http.kuki:304
	return fetch.URLWithQuery(base, queryParams)
}

//line stdlib/http/http.kuki:309
func Text(w http.ResponseWriter, content string) error {
//line stdlib/http/http.kuki:310
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
//line stdlib/http/http.kuki:311
	_, err := io.WriteString(w, content)
//line stdlib/http/http.kuki:312
	return err
}

//line stdlib/http/http.kuki:316
func TextStatus(w http.ResponseWriter, content string, status int) error {
//line stdlib/http/http.kuki:317
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
//line stdlib/http/http.kuki:318
	w.WriteHeader(status)
//line stdlib/http/http.kuki:319
	_, err := io.WriteString(w, content)
//line stdlib/http/http.kuki:320
	return err
}

//line stdlib/http/http.kuki:328
func HTML(w http.ResponseWriter, content string) error {
//line stdlib/http/http.kuki:329
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
//line stdlib/http/http.kuki:330
	_, err := io.WriteString(w, content)
//line stdlib/http/http.kuki:331
	return err
}

//line stdlib/http/http.kuki:337
func SafeHTML(w http.ResponseWriter, content string) error {
//line stdlib/http/http.kuki:338
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
//line stdlib/http/http.kuki:339
	_, err := io.WriteString(w, html.EscapeString(content))
//line stdlib/http/http.kuki:340
	return err
}

//line stdlib/http/http.kuki:347
func SetSecureHeaders(w http.ResponseWriter) {
//line stdlib/http/http.kuki:348
	w.Header().Set("X-Content-Type-Options", "nosniff")
//line stdlib/http/http.kuki:349
	w.Header().Set("X-Frame-Options", "DENY")
//line stdlib/http/http.kuki:350
	w.Header().Set("Referrer-Policy", "strict-origin-when-cross-origin")
//line stdlib/http/http.kuki:351
	w.Header().Set("Content-Security-Policy", "default-src 'self'")
}

//line stdlib/http/http.kuki:357
func IsGet(r *http.Request) bool {
//line stdlib/http/http.kuki:358
	return (r.Method == "GET")
}

//line stdlib/http/http.kuki:362
func IsPost(r *http.Request) bool {
//line stdlib/http/http.kuki:363
	return (r.Method == "POST")
}

//line stdlib/http/http.kuki:367
func IsPut(r *http.Request) bool {
//line stdlib/http/http.kuki:368
	return (r.Method == "PUT")
}

//line stdlib/http/http.kuki:372
func IsDelete(r *http.Request) bool {
//line stdlib/http/http.kuki:373
	return (r.Method == "DELETE")
}

//line stdlib/http/http.kuki:377
func IsPatch(r *http.Request) bool {
//line stdlib/http/http.kuki:378
	return (r.Method == "PATCH")
}

//line stdlib/http/http.kuki:383
func MethodNotAllowed(w http.ResponseWriter, allowed ...string) {
//line stdlib/http/http.kuki:384
	w.Header().Set("Allow", kukistring.Join(allowed, ", "))
//line stdlib/http/http.kuki:385
	w.WriteHeader(405)
}

//line stdlib/http/http.kuki:390
func SecureHeaders(handler http.Handler) http.Handler {
//line stdlib/http/http.kuki:391
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
//line stdlib/http/http.kuki:392
		w.Header().Set("X-Content-Type-Options", "nosniff")
//line stdlib/http/http.kuki:393
		w.Header().Set("X-Frame-Options", "DENY")
//line stdlib/http/http.kuki:394
		w.Header().Set("Referrer-Policy", "strict-origin-when-cross-origin")
//line stdlib/http/http.kuki:395
		w.Header().Set("Content-Security-Policy", "default-src 'self'")
//line stdlib/http/http.kuki:396
		handler.ServeHTTP(w, r)
	})
}
