// Generated by Kukicha (requires Go 1.26+)

package set

//line stdlib/set/set.kuki:11
func New[K comparable](hint ...K) map[K]bool {
//line stdlib/set/set.kuki:12
	return make(map[K]bool)
}

//line stdlib/set/set.kuki:16
func From[K comparable](items []K) map[K]bool {
//line stdlib/set/set.kuki:17
	s := make(map[K]bool, len(items))
//line stdlib/set/set.kuki:18
	for _, item := range items {
//line stdlib/set/set.kuki:19
		s[item] = true
	}
//line stdlib/set/set.kuki:20
	return s
}

//line stdlib/set/set.kuki:25
func Add[K comparable](s map[K]bool, item K) map[K]bool {
//line stdlib/set/set.kuki:26
	result := make(map[K]bool, (len(s) + 1))
//line stdlib/set/set.kuki:27
	for k := range s {
//line stdlib/set/set.kuki:28
		result[k] = true
	}
//line stdlib/set/set.kuki:29
	result[item] = true
//line stdlib/set/set.kuki:30
	return result
}

//line stdlib/set/set.kuki:35
func AddIn[K comparable](s map[K]bool, item K) {
//line stdlib/set/set.kuki:36
	s[item] = true
}

//line stdlib/set/set.kuki:41
func Remove[K comparable](s map[K]bool, item K) map[K]bool {
//line stdlib/set/set.kuki:42
	result := make(map[K]bool, len(s))
//line stdlib/set/set.kuki:43
	for k := range s {
//line stdlib/set/set.kuki:44
		if k != item {
//line stdlib/set/set.kuki:45
			result[k] = true
		}
	}
//line stdlib/set/set.kuki:46
	return result
}

//line stdlib/set/set.kuki:51
func RemoveIn[K comparable](s map[K]bool, item K) {
//line stdlib/set/set.kuki:52
	delete(s, item)
}

//line stdlib/set/set.kuki:56
func Contains[K comparable](s map[K]bool, item K) bool {
//line stdlib/set/set.kuki:57
	return s[item]
}

//line stdlib/set/set.kuki:62
func ToSlice[K comparable](s map[K]bool) []K {
//line stdlib/set/set.kuki:63
	result := make([]K, 0, len(s))
//line stdlib/set/set.kuki:64
	for k := range s {
//line stdlib/set/set.kuki:65
		result = append(result, k)
	}
//line stdlib/set/set.kuki:66
	return result
}

//line stdlib/set/set.kuki:70
func Union[K comparable](a map[K]bool, b map[K]bool) map[K]bool {
//line stdlib/set/set.kuki:71
	result := make(map[K]bool, (len(a) + len(b)))
//line stdlib/set/set.kuki:72
	for k := range a {
//line stdlib/set/set.kuki:73
		result[k] = true
	}
//line stdlib/set/set.kuki:74
	for k := range b {
//line stdlib/set/set.kuki:75
		result[k] = true
	}
//line stdlib/set/set.kuki:76
	return result
}

//line stdlib/set/set.kuki:80
func Intersect[K comparable](a map[K]bool, b map[K]bool) map[K]bool {
//line stdlib/set/set.kuki:81
	result := make(map[K]bool)
//line stdlib/set/set.kuki:82
	for k := range a {
//line stdlib/set/set.kuki:83
		if b[k] {
//line stdlib/set/set.kuki:84
			result[k] = true
		}
	}
//line stdlib/set/set.kuki:85
	return result
}

//line stdlib/set/set.kuki:89
func Difference[K comparable](a map[K]bool, b map[K]bool) map[K]bool {
//line stdlib/set/set.kuki:90
	result := make(map[K]bool)
//line stdlib/set/set.kuki:91
	for k := range a {
//line stdlib/set/set.kuki:92
		if !b[k] {
//line stdlib/set/set.kuki:93
			result[k] = true
		}
	}
//line stdlib/set/set.kuki:94
	return result
}

//line stdlib/set/set.kuki:98
func IsSubset[K comparable](sub map[K]bool, super map[K]bool) bool {
//line stdlib/set/set.kuki:99
	for k := range sub {
//line stdlib/set/set.kuki:100
		if !super[k] {
//line stdlib/set/set.kuki:101
			return false
		}
	}
//line stdlib/set/set.kuki:102
	return true
}

//line stdlib/set/set.kuki:106
func IsSuperset[K comparable](super map[K]bool, sub map[K]bool) bool {
//line stdlib/set/set.kuki:107
	return IsSubset(sub, super)
}

//line stdlib/set/set.kuki:111
func Equal[K comparable](a map[K]bool, b map[K]bool) bool {
//line stdlib/set/set.kuki:112
	if len(a) != len(b) {
//line stdlib/set/set.kuki:113
		return false
	}
//line stdlib/set/set.kuki:114
	return IsSubset(a, b)
}
