// Generated by Kukicha (requires Go 1.26+)

package regex_test

import (
	"fmt"
	"github.com/kukichalang/kukicha/stdlib/regex"
	"github.com/kukichalang/kukicha/stdlib/test"
	"testing"
)

//line stdlib/regex/regex_test.kuki:10
type MatchCase struct {
	name     string
	pattern  string
	text     string
	expected bool
}

//line stdlib/regex/regex_test.kuki:16
func TestMatch(t *testing.T) {
//line stdlib/regex/regex_test.kuki:17
	cases := []MatchCase{MatchCase{name: "digits match", pattern: `\d+`, text: "abc123", expected: true}, MatchCase{name: "no digits", pattern: `\d+`, text: "abcdef", expected: false}, MatchCase{name: "full match", pattern: "^hello$", text: "hello", expected: true}, MatchCase{name: "full no match", pattern: "^hello$", text: "hello world", expected: false}, MatchCase{name: "empty pattern matches all", pattern: "", text: "anything", expected: true}}
//line stdlib/regex/regex_test.kuki:25
	for _, tc := range cases {
//line stdlib/regex/regex_test.kuki:26
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/regex/regex_test.kuki:27
			got := regex.Match(tc.pattern, tc.text)
//line stdlib/regex/regex_test.kuki:28
			test.AssertEqual(t, got, tc.expected)
		})
	}
}

//line stdlib/regex/regex_test.kuki:32
type MatchSafeCase struct {
	name      string
	pattern   string
	text      string
	expected  bool
	expectErr bool
}

//line stdlib/regex/regex_test.kuki:39
func TestMatchSafe(t *testing.T) {
//line stdlib/regex/regex_test.kuki:40
	cases := []MatchSafeCase{MatchSafeCase{name: "valid pattern", pattern: `\d+`, text: "123", expected: true, expectErr: false}, MatchSafeCase{name: "invalid pattern", pattern: `[`, text: "", expected: false, expectErr: true}}
//line stdlib/regex/regex_test.kuki:57
	for _, tc := range cases {
//line stdlib/regex/regex_test.kuki:58
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/regex/regex_test.kuki:59
			got, err := regex.MatchSafe(tc.pattern, tc.text)
//line stdlib/regex/regex_test.kuki:60
			if tc.expectErr {
//line stdlib/regex/regex_test.kuki:61
				test.AssertError(t, err)
			} else {
//line stdlib/regex/regex_test.kuki:63
				test.AssertNoError(t, err)
//line stdlib/regex/regex_test.kuki:64
				test.AssertEqual(t, got, tc.expected)
			}
		})
	}
}

//line stdlib/regex/regex_test.kuki:68
type FindCase struct {
	name      string
	pattern   string
	text      string
	expected  string
	expectErr bool
}

//line stdlib/regex/regex_test.kuki:75
func TestFind(t *testing.T) {
//line stdlib/regex/regex_test.kuki:76
	cases := []FindCase{FindCase{name: "find digits", pattern: `\d+`, text: "abc123def456", expected: "123", expectErr: false}, FindCase{name: "find word", pattern: `\w+`, text: "  hello  ", expected: "hello", expectErr: false}, FindCase{name: "no match", pattern: `\d+`, text: "abcdef", expected: "", expectErr: true}}
//line stdlib/regex/regex_test.kuki:94
	for _, tc := range cases {
//line stdlib/regex/regex_test.kuki:95
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/regex/regex_test.kuki:96
			got, err := regex.Find(tc.pattern, tc.text)
//line stdlib/regex/regex_test.kuki:97
			if tc.expectErr {
//line stdlib/regex/regex_test.kuki:98
				test.AssertError(t, err)
			} else {
//line stdlib/regex/regex_test.kuki:100
				test.AssertNoError(t, err)
//line stdlib/regex/regex_test.kuki:101
				test.AssertEqual(t, got, tc.expected)
			}
		})
	}
}

//line stdlib/regex/regex_test.kuki:105
type FindAllCase struct {
	name        string
	pattern     string
	text        string
	expectedLen int
}

//line stdlib/regex/regex_test.kuki:111
func TestFindAll(t *testing.T) {
//line stdlib/regex/regex_test.kuki:112
	cases := []FindAllCase{FindAllCase{name: "find all digits", pattern: `\d+`, text: "a1 b2 c3", expectedLen: 3}, FindAllCase{name: "no matches", pattern: `\d+`, text: "abcdef", expectedLen: 0}, FindAllCase{name: "single match", pattern: "hello", text: "say hello there", expectedLen: 1}}
//line stdlib/regex/regex_test.kuki:118
	for _, tc := range cases {
//line stdlib/regex/regex_test.kuki:119
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/regex/regex_test.kuki:120
			got := regex.FindAll(tc.pattern, tc.text)
//line stdlib/regex/regex_test.kuki:121
			test.AssertEqual(t, len(got), tc.expectedLen)
		})
	}
}

//line stdlib/regex/regex_test.kuki:125
type FindGroupsCase struct {
	name        string
	pattern     string
	text        string
	expectErr   bool
	expectedLen int
}

//line stdlib/regex/regex_test.kuki:132
func TestFindGroups(t *testing.T) {
//line stdlib/regex/regex_test.kuki:133
	cases := []FindGroupsCase{FindGroupsCase{name: "semver groups", pattern: `^(v?)(\d+)\.(\d+)\.(\d+)$`, text: "v1.2.3", expectErr: false, expectedLen: 5}, FindGroupsCase{name: "no prefix", pattern: `^(v?)(\d+)\.(\d+)\.(\d+)$`, text: "1.2.3", expectErr: false, expectedLen: 5}, FindGroupsCase{name: "no match", pattern: `^(v?)(\d+)\.(\d+)\.(\d+)$`, text: "invalid", expectErr: true, expectedLen: 0}}
//line stdlib/regex/regex_test.kuki:157
	for _, tc := range cases {
//line stdlib/regex/regex_test.kuki:158
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/regex/regex_test.kuki:159
			got, err := regex.FindGroups(tc.pattern, tc.text)
//line stdlib/regex/regex_test.kuki:160
			if tc.expectErr {
//line stdlib/regex/regex_test.kuki:161
				test.AssertError(t, err)
			} else {
//line stdlib/regex/regex_test.kuki:163
				test.AssertNoError(t, err)
//line stdlib/regex/regex_test.kuki:164
				test.AssertEqual(t, len(got), tc.expectedLen)
			}
		})
	}
}

//line stdlib/regex/regex_test.kuki:168
type FindGroupsValuesCase struct {
	name string
}

//line stdlib/regex/regex_test.kuki:171
func TestFindGroupsValues(t *testing.T) {
//line stdlib/regex/regex_test.kuki:172
	cases := []FindGroupsValuesCase{FindGroupsValuesCase{name: "capture group values"}}
//line stdlib/regex/regex_test.kuki:174
	for _, tc := range cases {
//line stdlib/regex/regex_test.kuki:175
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/regex/regex_test.kuki:176
			groups, err := regex.FindGroups(`^(v?)(\d+\.\d+\.\d+)$`, "v1.2.3")
//line stdlib/regex/regex_test.kuki:177
			test.AssertNoError(t, err)
//line stdlib/regex/regex_test.kuki:178
			test.AssertEqual(t, groups[0], "v1.2.3")
//line stdlib/regex/regex_test.kuki:179
			test.AssertEqual(t, groups[1], "v")
//line stdlib/regex/regex_test.kuki:180
			test.AssertEqual(t, groups[2], "1.2.3")
		})
	}
}

//line stdlib/regex/regex_test.kuki:184
type FindAllGroupsCase struct {
	name        string
	pattern     string
	text        string
	expectedLen int
}

//line stdlib/regex/regex_test.kuki:190
func TestFindAllGroups(t *testing.T) {
//line stdlib/regex/regex_test.kuki:191
	cases := []FindAllGroupsCase{FindAllGroupsCase{name: "key-value pairs", pattern: `(\w+)=(\w+)`, text: "a=1 b=2 c=3", expectedLen: 3}, FindAllGroupsCase{name: "no matches", pattern: `(\d+)-(\d+)`, text: "no dashes here", expectedLen: 0}}
//line stdlib/regex/regex_test.kuki:206
	for _, tc := range cases {
//line stdlib/regex/regex_test.kuki:207
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/regex/regex_test.kuki:208
			got := regex.FindAllGroups(tc.pattern, tc.text)
//line stdlib/regex/regex_test.kuki:209
			test.AssertEqual(t, len(got), tc.expectedLen)
		})
	}
}

//line stdlib/regex/regex_test.kuki:213
type ReplaceCase struct {
	name        string
	pattern     string
	replacement string
	text        string
	expected    string
}

//line stdlib/regex/regex_test.kuki:220
func TestReplace(t *testing.T) {
//line stdlib/regex/regex_test.kuki:221
	cases := []ReplaceCase{ReplaceCase{name: "collapse spaces", pattern: `\s+`, replacement: " ", text: "too   many   spaces", expected: "too many spaces"}, ReplaceCase{name: "remove digits", pattern: `\d`, replacement: "", text: "a1b2c3", expected: "abc"}, ReplaceCase{name: "capture group ref", pattern: `(\w+)=(\w+)`, replacement: "$2=$1", text: "key=val", expected: "val=key"}}
//line stdlib/regex/regex_test.kuki:245
	for _, tc := range cases {
//line stdlib/regex/regex_test.kuki:246
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/regex/regex_test.kuki:247
			got := regex.Replace(tc.pattern, tc.replacement, tc.text)
//line stdlib/regex/regex_test.kuki:248
			test.AssertEqual(t, got, tc.expected)
		})
	}
}

//line stdlib/regex/regex_test.kuki:252
type ReplaceFuncCase struct {
	name string
}

//line stdlib/regex/regex_test.kuki:255
func TestReplaceFunc(t *testing.T) {
//line stdlib/regex/regex_test.kuki:256
	cases := []ReplaceFuncCase{ReplaceFuncCase{name: "wrap matches"}}
//line stdlib/regex/regex_test.kuki:258
	for _, tc := range cases {
//line stdlib/regex/regex_test.kuki:259
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/regex/regex_test.kuki:260
			got := regex.ReplaceFunc(`\d+`, func(m string) string { return fmt.Sprintf("[%v]", m) }, "a1 b2 c3")
//line stdlib/regex/regex_test.kuki:261
			test.AssertEqual(t, got, "a[1] b[2] c[3]")
		})
	}
}

//line stdlib/regex/regex_test.kuki:265
type SplitCase struct {
	name        string
	pattern     string
	text        string
	expectedLen int
}

//line stdlib/regex/regex_test.kuki:271
func TestSplit(t *testing.T) {
//line stdlib/regex/regex_test.kuki:272
	cases := []SplitCase{SplitCase{name: "split on comma-space", pattern: `[,;]\s*`, text: "a, b; c", expectedLen: 3}, SplitCase{name: "split on whitespace", pattern: `\s+`, text: "one two three", expectedLen: 3}, SplitCase{name: "no match splits whole", pattern: `\d+`, text: "no digits here", expectedLen: 1}}
//line stdlib/regex/regex_test.kuki:288
	for _, tc := range cases {
//line stdlib/regex/regex_test.kuki:289
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/regex/regex_test.kuki:290
			got := regex.Split(tc.pattern, tc.text)
//line stdlib/regex/regex_test.kuki:291
			test.AssertEqual(t, len(got), tc.expectedLen)
		})
	}
}

//line stdlib/regex/regex_test.kuki:295
type IsValidCase struct {
	name     string
	pattern  string
	expected bool
}

//line stdlib/regex/regex_test.kuki:300
func TestIsValid(t *testing.T) {
//line stdlib/regex/regex_test.kuki:301
	cases := []IsValidCase{IsValidCase{name: "valid pattern", pattern: `\d+`, expected: true}, IsValidCase{name: "valid complex", pattern: `^(v?)(\d+\.\d+\.\d+)$`, expected: true}, IsValidCase{name: "invalid pattern", pattern: "[unclosed", expected: false}, IsValidCase{name: "empty is valid", pattern: "", expected: true}}
//line stdlib/regex/regex_test.kuki:308
	for _, tc := range cases {
//line stdlib/regex/regex_test.kuki:309
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/regex/regex_test.kuki:310
			got := regex.IsValid(tc.pattern)
//line stdlib/regex/regex_test.kuki:311
			test.AssertEqual(t, got, tc.expected)
		})
	}
}

//line stdlib/regex/regex_test.kuki:315
type CompileCase struct {
	name      string
	pattern   string
	expectErr bool
}

//line stdlib/regex/regex_test.kuki:320
func TestCompile(t *testing.T) {
//line stdlib/regex/regex_test.kuki:321
	cases := []CompileCase{CompileCase{name: "valid compile", pattern: `\d+`, expectErr: false}, CompileCase{name: "invalid compile", pattern: "[bad", expectErr: true}}
//line stdlib/regex/regex_test.kuki:326
	for _, tc := range cases {
//line stdlib/regex/regex_test.kuki:327
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/regex/regex_test.kuki:328
			_, err := regex.Compile(tc.pattern)
//line stdlib/regex/regex_test.kuki:329
			if tc.expectErr {
//line stdlib/regex/regex_test.kuki:330
				test.AssertError(t, err)
			} else {
//line stdlib/regex/regex_test.kuki:332
				test.AssertNoError(t, err)
			}
		})
	}
}

//line stdlib/regex/regex_test.kuki:336
type CompiledMatchCase struct {
	name     string
	text     string
	expected bool
}

//line stdlib/regex/regex_test.kuki:341
func TestCompiledMatch(t *testing.T) {
//line stdlib/regex/regex_test.kuki:342
	cases := []CompiledMatchCase{CompiledMatchCase{name: "compiled match", text: "abc123", expected: true}, CompiledMatchCase{name: "compiled no match", text: "abcdef", expected: false}}
//line stdlib/regex/regex_test.kuki:347
	p := regex.MustCompile(`\d+`)
//line stdlib/regex/regex_test.kuki:348
	for _, tc := range cases {
//line stdlib/regex/regex_test.kuki:349
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/regex/regex_test.kuki:350
			got := regex.MatchCompiled(p, tc.text)
//line stdlib/regex/regex_test.kuki:351
			test.AssertEqual(t, got, tc.expected)
		})
	}
}

//line stdlib/regex/regex_test.kuki:355
type CompiledFindCase struct {
	name string
}

//line stdlib/regex/regex_test.kuki:358
func TestCompiledFind(t *testing.T) {
//line stdlib/regex/regex_test.kuki:359
	cases := []CompiledFindCase{CompiledFindCase{name: "compiled find"}}
//line stdlib/regex/regex_test.kuki:361
	p := regex.MustCompile(`\d+`)
//line stdlib/regex/regex_test.kuki:362
	for _, tc := range cases {
//line stdlib/regex/regex_test.kuki:363
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/regex/regex_test.kuki:364
			got, err := regex.FindCompiled(p, "abc123def456")
//line stdlib/regex/regex_test.kuki:365
			test.AssertNoError(t, err)
//line stdlib/regex/regex_test.kuki:366
			test.AssertEqual(t, got, "123")
//line stdlib/regex/regex_test.kuki:368
			all := regex.FindAllCompiled(p, "a1 b2 c3")
//line stdlib/regex/regex_test.kuki:369
			test.AssertEqual(t, len(all), 3)
		})
	}
}

//line stdlib/regex/regex_test.kuki:373
type CompiledFindAllGroupsCase struct {
	name string
}

//line stdlib/regex/regex_test.kuki:376
func TestCompiledFindAllGroups(t *testing.T) {
//line stdlib/regex/regex_test.kuki:377
	cases := []CompiledFindAllGroupsCase{CompiledFindAllGroupsCase{name: "compiled find all groups"}}
//line stdlib/regex/regex_test.kuki:379
	p := regex.MustCompile(`(\w+)=(\w+)`)
//line stdlib/regex/regex_test.kuki:380
	for _, tc := range cases {
//line stdlib/regex/regex_test.kuki:381
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/regex/regex_test.kuki:382
			got := regex.FindAllGroupsCompiled(p, "a=1 b=2")
//line stdlib/regex/regex_test.kuki:383
			test.AssertEqual(t, len(got), 2)
		})
	}
}

//line stdlib/regex/regex_test.kuki:387
type CompiledReplaceCase struct {
	name string
}

//line stdlib/regex/regex_test.kuki:390
func TestCompiledReplace(t *testing.T) {
//line stdlib/regex/regex_test.kuki:391
	cases := []CompiledReplaceCase{CompiledReplaceCase{name: "compiled replace"}}
//line stdlib/regex/regex_test.kuki:393
	p := regex.MustCompile(`\s+`)
//line stdlib/regex/regex_test.kuki:394
	for _, tc := range cases {
//line stdlib/regex/regex_test.kuki:395
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/regex/regex_test.kuki:396
			got := regex.ReplaceCompiled(p, "-", "a b  c")
//line stdlib/regex/regex_test.kuki:397
			test.AssertEqual(t, got, "a-b-c")
		})
	}
}

//line stdlib/regex/regex_test.kuki:401
type CompiledReplaceFuncCase struct {
	name string
}

//line stdlib/regex/regex_test.kuki:404
func TestCompiledReplaceFunc(t *testing.T) {
//line stdlib/regex/regex_test.kuki:405
	cases := []CompiledReplaceFuncCase{CompiledReplaceFuncCase{name: "compiled replace func"}}
//line stdlib/regex/regex_test.kuki:407
	p := regex.MustCompile(`\d+`)
//line stdlib/regex/regex_test.kuki:408
	for _, tc := range cases {
//line stdlib/regex/regex_test.kuki:409
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/regex/regex_test.kuki:410
			got := regex.ReplaceFuncCompiled(p, func(m string) string { return fmt.Sprintf("[%v]", m) }, "a1 b2")
//line stdlib/regex/regex_test.kuki:411
			test.AssertEqual(t, got, "a[1] b[2]")
		})
	}
}

//line stdlib/regex/regex_test.kuki:415
type CompiledSplitCase struct {
	name string
}

//line stdlib/regex/regex_test.kuki:418
func TestCompiledSplit(t *testing.T) {
//line stdlib/regex/regex_test.kuki:419
	cases := []CompiledSplitCase{CompiledSplitCase{name: "compiled split"}}
//line stdlib/regex/regex_test.kuki:421
	p := regex.MustCompile(`[,;]\s*`)
//line stdlib/regex/regex_test.kuki:422
	for _, tc := range cases {
//line stdlib/regex/regex_test.kuki:423
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/regex/regex_test.kuki:424
			got := regex.SplitCompiled(p, "a, b; c")
//line stdlib/regex/regex_test.kuki:425
			test.AssertEqual(t, len(got), 3)
		})
	}
}
