// Generated by Kukicha (requires Go 1.26+)

package regex

import (
	"errors"
	"fmt"
	"regexp"
)

//line stdlib/regex/regex.kuki:19
type Pattern struct {
	re *regexp.Regexp
}

//line stdlib/regex/regex.kuki:27
func Match(pattern string, text string) bool {
//line stdlib/regex/regex.kuki:28
	re := regexp.MustCompile(pattern)
//line stdlib/regex/regex.kuki:29
	return re.MatchString(text)
}

//line stdlib/regex/regex.kuki:36
func MatchSafe(pattern string, text string) (bool, error) {
//line stdlib/regex/regex.kuki:37
	re, err := regexp.Compile(pattern)
//line stdlib/regex/regex.kuki:38
	if err != nil {
//line stdlib/regex/regex.kuki:39
		return false, fmt.Errorf("invalid pattern: %v", err)
	}
//line stdlib/regex/regex.kuki:40
	return re.MatchString(text), nil
}

//line stdlib/regex/regex.kuki:46
func Find(pattern string, text string) (string, error) {
//line stdlib/regex/regex.kuki:47
	re := regexp.MustCompile(pattern)
//line stdlib/regex/regex.kuki:48
	result := re.FindString(text)
//line stdlib/regex/regex.kuki:49
	if result == "" {
//line stdlib/regex/regex.kuki:50
		return "", errors.New("no match found")
	}
//line stdlib/regex/regex.kuki:51
	return result, nil
}

//line stdlib/regex/regex.kuki:56
func FindAll(pattern string, text string) []string {
//line stdlib/regex/regex.kuki:57
	re := regexp.MustCompile(pattern)
//line stdlib/regex/regex.kuki:58
	matches := re.FindAllString(text, -1)
//line stdlib/regex/regex.kuki:59
	if matches == nil {
//line stdlib/regex/regex.kuki:60
		return []string{}
	}
//line stdlib/regex/regex.kuki:61
	return matches
}

//line stdlib/regex/regex.kuki:68
func FindGroups(pattern string, text string) ([]string, error) {
//line stdlib/regex/regex.kuki:69
	re := regexp.MustCompile(pattern)
//line stdlib/regex/regex.kuki:70
	matches := re.FindStringSubmatch(text)
//line stdlib/regex/regex.kuki:71
	if matches == nil {
//line stdlib/regex/regex.kuki:72
		return []string{}, errors.New("no match found")
	}
//line stdlib/regex/regex.kuki:73
	return matches, nil
}

//line stdlib/regex/regex.kuki:80
func FindAllGroups(pattern string, text string) [][]string {
//line stdlib/regex/regex.kuki:81
	re := regexp.MustCompile(pattern)
//line stdlib/regex/regex.kuki:82
	matches := re.FindAllStringSubmatch(text, -1)
//line stdlib/regex/regex.kuki:83
	if matches == nil {
//line stdlib/regex/regex.kuki:84
		return [][]string{}
	}
//line stdlib/regex/regex.kuki:85
	return matches
}

//line stdlib/regex/regex.kuki:93
func Replace(pattern string, replacement string, text string) string {
//line stdlib/regex/regex.kuki:94
	re := regexp.MustCompile(pattern)
//line stdlib/regex/regex.kuki:95
	return re.ReplaceAllString(text, replacement)
}

//line stdlib/regex/regex.kuki:101
func ReplaceFunc(pattern string, replacer func(string) string, text string) string {
//line stdlib/regex/regex.kuki:102
	re := regexp.MustCompile(pattern)
//line stdlib/regex/regex.kuki:103
	return re.ReplaceAllStringFunc(text, replacer)
}

//line stdlib/regex/regex.kuki:110
func Split(pattern string, text string) []string {
//line stdlib/regex/regex.kuki:111
	re := regexp.MustCompile(pattern)
//line stdlib/regex/regex.kuki:112
	return re.Split(text, -1)
}

//line stdlib/regex/regex.kuki:118
func IsValid(pattern string) bool {
//line stdlib/regex/regex.kuki:119
	_, err := regexp.Compile(pattern)
//line stdlib/regex/regex.kuki:120
	return (err == nil)
}

//line stdlib/regex/regex.kuki:126
func Compile(pattern string) (Pattern, error) {
//line stdlib/regex/regex.kuki:127
	re, err_1 := regexp.Compile(pattern)
//line stdlib/regex/regex.kuki:127
	if err_1 != nil {
//line stdlib/regex/regex.kuki:127
		return Pattern{}, fmt.Errorf("invalid pattern: %v", err_1)
	}
//line stdlib/regex/regex.kuki:128
	return Pattern{re: re}, nil
}

//line stdlib/regex/regex.kuki:133
func MustCompile(pattern string) Pattern {
//line stdlib/regex/regex.kuki:134
	re := regexp.MustCompile(pattern)
//line stdlib/regex/regex.kuki:135
	return Pattern{re: re}
}

//line stdlib/regex/regex.kuki:139
func MatchCompiled(p Pattern, text string) bool {
//line stdlib/regex/regex.kuki:140
	return p.re.MatchString(text)
}

//line stdlib/regex/regex.kuki:144
func FindCompiled(p Pattern, text string) (string, error) {
//line stdlib/regex/regex.kuki:145
	result := p.re.FindString(text)
//line stdlib/regex/regex.kuki:146
	if result == "" {
//line stdlib/regex/regex.kuki:147
		return "", errors.New("no match found")
	}
//line stdlib/regex/regex.kuki:148
	return result, nil
}

//line stdlib/regex/regex.kuki:152
func FindAllCompiled(p Pattern, text string) []string {
//line stdlib/regex/regex.kuki:153
	matches := p.re.FindAllString(text, -1)
//line stdlib/regex/regex.kuki:154
	if matches == nil {
//line stdlib/regex/regex.kuki:155
		return []string{}
	}
//line stdlib/regex/regex.kuki:156
	return matches
}

//line stdlib/regex/regex.kuki:160
func FindGroupsCompiled(p Pattern, text string) ([]string, error) {
//line stdlib/regex/regex.kuki:161
	matches := p.re.FindStringSubmatch(text)
//line stdlib/regex/regex.kuki:162
	if matches == nil {
//line stdlib/regex/regex.kuki:163
		return []string{}, errors.New("no match found")
	}
//line stdlib/regex/regex.kuki:164
	return matches, nil
}

//line stdlib/regex/regex.kuki:168
func FindAllGroupsCompiled(p Pattern, text string) [][]string {
//line stdlib/regex/regex.kuki:169
	matches := p.re.FindAllStringSubmatch(text, -1)
//line stdlib/regex/regex.kuki:170
	if matches == nil {
//line stdlib/regex/regex.kuki:171
		return [][]string{}
	}
//line stdlib/regex/regex.kuki:172
	return matches
}

//line stdlib/regex/regex.kuki:176
func ReplaceCompiled(p Pattern, replacement string, text string) string {
//line stdlib/regex/regex.kuki:177
	return p.re.ReplaceAllString(text, replacement)
}

//line stdlib/regex/regex.kuki:181
func ReplaceFuncCompiled(p Pattern, replacer func(string) string, text string) string {
//line stdlib/regex/regex.kuki:182
	return p.re.ReplaceAllStringFunc(text, replacer)
}

//line stdlib/regex/regex.kuki:186
func SplitCompiled(p Pattern, text string) []string {
//line stdlib/regex/regex.kuki:187
	return p.re.Split(text, -1)
}
