// Generated by Kukicha (requires Go 1.26+)

package db

import (
	"database/sql"
	"errors"
	"fmt"
	ctxpkg "github.com/kukichalang/kukicha/stdlib/ctx"
	"reflect"
	strpkg "strings"
	"unicode"
)

//line stdlib/db/db.kuki:23
type Pool struct {
	conn *sql.DB
}

//line stdlib/db/db.kuki:27
type Row struct {
	row *sql.Row
}

//line stdlib/db/db.kuki:31
type Rows struct {
	rows *sql.Rows
}

//line stdlib/db/db.kuki:35
type Tx struct {
	tx *sql.Tx
}

//line stdlib/db/db.kuki:42
type IsolationLevel string

const (
	IsolationLevelDefault         IsolationLevel = ""
	IsolationLevelReadUncommitted IsolationLevel = "read_uncommitted"
	IsolationLevelReadCommitted   IsolationLevel = "read_committed"
	IsolationLevelRepeatableRead  IsolationLevel = "repeatable_read"
	IsolationLevelSerializable    IsolationLevel = "serializable"
)

func (e IsolationLevel) String() string {
	return string(e)
}

func ParseIsolationLevel(s string) (IsolationLevel, bool) {
	switch s {
	case "":
		return IsolationLevelDefault, true
	case "read_uncommitted":
		return IsolationLevelReadUncommitted, true
	case "read_committed":
		return IsolationLevelReadCommitted, true
	case "repeatable_read":
		return IsolationLevelRepeatableRead, true
	case "serializable":
		return IsolationLevelSerializable, true
	}
	var zero IsolationLevel
	return zero, false
}

//line stdlib/db/db.kuki:51
type TxOptions struct {
	IsolationLevel IsolationLevel
	ReadOnly       bool
}

//line stdlib/db/db.kuki:61
func Open(driver string, connString string) (Pool, error) {
//line stdlib/db/db.kuki:62
	conn, err_1 := sql.Open(driver, connString)
//line stdlib/db/db.kuki:62
	if err_1 != nil {
		var _zero0 Pool
//line stdlib/db/db.kuki:62
		return _zero0, err_1
	}
//line stdlib/db/db.kuki:63
//line stdlib/db/db.kuki:63
	err_2 := conn.Ping()
//line stdlib/db/db.kuki:63
	if err_2 != nil {
		var _zero0 Pool
//line stdlib/db/db.kuki:63
		return _zero0, err_2
	}
//line stdlib/db/db.kuki:64
	pool := Pool{conn: conn}
//line stdlib/db/db.kuki:65
	return pool, nil
}

//line stdlib/db/db.kuki:69
func Close(pool Pool) error {
//line stdlib/db/db.kuki:70
	return pool.conn.Close()
}

//line stdlib/db/db.kuki:74
func Ping(pool Pool) error {
//line stdlib/db/db.kuki:75
	return pool.conn.Ping()
}

//line stdlib/db/db.kuki:85
func Query(pool Pool, query string, args ...any) (Rows, error) {
//line stdlib/db/db.kuki:86
	rows, err_3 := pool.conn.Query(query, args...)
//line stdlib/db/db.kuki:86
	if err_3 != nil {
		var _zero0 Rows
//line stdlib/db/db.kuki:86
		return _zero0, err_3
	}
//line stdlib/db/db.kuki:87
	result := Rows{rows: rows}
//line stdlib/db/db.kuki:88
	return result, nil
}

//line stdlib/db/db.kuki:92
func QueryCtx(h ctxpkg.Handle, pool Pool, query string, args ...any) (Rows, error) {
//line stdlib/db/db.kuki:93
	rows, err_4 := pool.conn.QueryContext(h.Ctx, query, args...)
//line stdlib/db/db.kuki:93
	if err_4 != nil {
		var _zero0 Rows
//line stdlib/db/db.kuki:93
		return _zero0, err_4
	}
//line stdlib/db/db.kuki:94
	result := Rows{rows: rows}
//line stdlib/db/db.kuki:95
	return result, nil
}

//line stdlib/db/db.kuki:100
func QueryRow(pool Pool, query string, args ...any) Row {
//line stdlib/db/db.kuki:101
	row := pool.conn.QueryRow(query, args...)
//line stdlib/db/db.kuki:102
	return Row{row: row}
}

//line stdlib/db/db.kuki:108
func Exec(pool Pool, query string, args ...any) (int64, error) {
//line stdlib/db/db.kuki:109
	result, err_5 := pool.conn.Exec(query, args...)
//line stdlib/db/db.kuki:109
	if err_5 != nil {
//line stdlib/db/db.kuki:109
		return 0, err_5
	}
//line stdlib/db/db.kuki:110
	affected, err_6 := result.RowsAffected()
//line stdlib/db/db.kuki:110
	if err_6 != nil {
//line stdlib/db/db.kuki:110
		return 0, err_6
	}
//line stdlib/db/db.kuki:111
	return affected, nil
}

//line stdlib/db/db.kuki:116
func ExecCtx(h ctxpkg.Handle, pool Pool, query string, args ...any) (int64, error) {
//line stdlib/db/db.kuki:117
	result, err_7 := pool.conn.ExecContext(h.Ctx, query, args...)
//line stdlib/db/db.kuki:117
	if err_7 != nil {
//line stdlib/db/db.kuki:117
		return 0, err_7
	}
//line stdlib/db/db.kuki:118
	affected, err_8 := result.RowsAffected()
//line stdlib/db/db.kuki:118
	if err_8 != nil {
//line stdlib/db/db.kuki:118
		return 0, err_8
	}
//line stdlib/db/db.kuki:119
	return affected, nil
}

//line stdlib/db/db.kuki:124
func LastInsertId(pool Pool, query string, args ...any) (int64, error) {
//line stdlib/db/db.kuki:125
	result, err_9 := pool.conn.Exec(query, args...)
//line stdlib/db/db.kuki:125
	if err_9 != nil {
//line stdlib/db/db.kuki:125
		return 0, err_9
	}
//line stdlib/db/db.kuki:126
	id, err_10 := result.LastInsertId()
//line stdlib/db/db.kuki:126
	if err_10 != nil {
//line stdlib/db/db.kuki:126
		return 0, err_10
	}
//line stdlib/db/db.kuki:127
	return id, nil
}

//line stdlib/db/db.kuki:138
func ScanAll[T any](rows Rows, sample []T) ([]T, error) {
//line stdlib/db/db.kuki:139
	defer rows.rows.Close()
//line stdlib/db/db.kuki:141
	columns, err_11 := rows.rows.Columns()
//line stdlib/db/db.kuki:141
	if err_11 != nil {
//line stdlib/db/db.kuki:141
		return []T{}, err_11
	}
//line stdlib/db/db.kuki:143
	sliceType := reflect.ValueOf(sample).Type()
//line stdlib/db/db.kuki:144
	elemType := sliceType.Elem()
//line stdlib/db/db.kuki:145
	resultSlice := reflect.MakeSlice(sliceType, 0, 0)
//line stdlib/db/db.kuki:147
	for rows.rows.Next() {
//line stdlib/db/db.kuki:148
		elemPtr := reflect.New(elemType)
//line stdlib/db/db.kuki:149
		fieldPtrs := structScanners(elemPtr.Elem(), elemType, columns)
//line stdlib/db/db.kuki:150
		// kukicha: could not infer return count; use explicit capture if incorrect
//line stdlib/db/db.kuki:150
		err_12 := rows.rows.Scan(fieldPtrs...)
//line stdlib/db/db.kuki:150
		if err_12 != nil {
//line stdlib/db/db.kuki:150
			return []T{}, err_12
		}
//line stdlib/db/db.kuki:151
		resultSlice = reflect.Append(resultSlice, elemPtr.Elem())
	}
//line stdlib/db/db.kuki:153
	// kukicha: could not infer return count; use explicit capture if incorrect
//line stdlib/db/db.kuki:153
	err_13 := rows.rows.Err()
//line stdlib/db/db.kuki:153
	if err_13 != nil {
//line stdlib/db/db.kuki:153
		return []T{}, err_13
	}
//line stdlib/db/db.kuki:154
	return resultSlice.Interface().([]T), nil
}

//line stdlib/db/db.kuki:160
func ScanOne[T any](rows Rows, sample T) (T, error) {
//line stdlib/db/db.kuki:161
	defer rows.rows.Close()
//line stdlib/db/db.kuki:163
	columns, err_14 := rows.rows.Columns()
//line stdlib/db/db.kuki:163
	if err_14 != nil {
		var _zero0 T
//line stdlib/db/db.kuki:163
		return _zero0, err_14
	}
//line stdlib/db/db.kuki:165
	elemType := reflect.TypeOf(sample)
//line stdlib/db/db.kuki:166
	elemPtr := reflect.New(elemType)
//line stdlib/db/db.kuki:168
	if !rows.rows.Next() {
//line stdlib/db/db.kuki:169
		// kukicha: could not infer return count; use explicit capture if incorrect
//line stdlib/db/db.kuki:169
		err_15 := rows.rows.Err()
//line stdlib/db/db.kuki:169
		if err_15 != nil {
			var _zero0 T
//line stdlib/db/db.kuki:169
			return _zero0, err_15
		}
//line stdlib/db/db.kuki:170
		return sample, errors.New("db.ScanOne: no rows returned")
	}
//line stdlib/db/db.kuki:172
	fieldPtrs := structScanners(elemPtr.Elem(), elemType, columns)
//line stdlib/db/db.kuki:173
	// kukicha: could not infer return count; use explicit capture if incorrect
//line stdlib/db/db.kuki:173
	err_16 := rows.rows.Scan(fieldPtrs...)
//line stdlib/db/db.kuki:173
	if err_16 != nil {
		var _zero0 T
//line stdlib/db/db.kuki:173
		return _zero0, err_16
	}
//line stdlib/db/db.kuki:175
	if rows.rows.Next() {
//line stdlib/db/db.kuki:176
		return sample, errors.New("db.ScanOne: more than one row returned")
	}
//line stdlib/db/db.kuki:178
	// kukicha: could not infer return count; use explicit capture if incorrect
//line stdlib/db/db.kuki:178
	err_17 := rows.rows.Err()
//line stdlib/db/db.kuki:178
	if err_17 != nil {
		var _zero0 T
//line stdlib/db/db.kuki:178
		return _zero0, err_17
	}
//line stdlib/db/db.kuki:179
	return elemPtr.Elem().Interface().(T), nil
}

//line stdlib/db/db.kuki:183
func ScanRow(row Row, sample any) (any, error) {
//line stdlib/db/db.kuki:184
	elemType := reflect.TypeOf(sample)
//line stdlib/db/db.kuki:185
	elemPtr := reflect.New(elemType)
//line stdlib/db/db.kuki:188
	numFields := elemType.NumField()
//line stdlib/db/db.kuki:189
	scanners := make([]any, 0, numFields)
//line stdlib/db/db.kuki:190
	for i := range numFields {
//line stdlib/db/db.kuki:191
		field := elemType.Field(i)
//line stdlib/db/db.kuki:192
		if field.IsExported() {
//line stdlib/db/db.kuki:193
			scanners = append(scanners, &nullSafeField{target: elemPtr.Elem().Field(i)})
		}
	}
//line stdlib/db/db.kuki:195
	// kukicha: could not infer return count; use explicit capture if incorrect
//line stdlib/db/db.kuki:195
	err_18 := row.row.Scan(scanners...)
//line stdlib/db/db.kuki:195
	if err_18 != nil {
		var _zero0 any
//line stdlib/db/db.kuki:195
		return _zero0, err_18
	}
//line stdlib/db/db.kuki:196
	return elemPtr.Elem().Interface(), nil
}

//line stdlib/db/db.kuki:201
func CloseRows(rows Rows) error {
//line stdlib/db/db.kuki:202
	return rows.rows.Close()
}

//line stdlib/db/db.kuki:216
func Transaction(pool Pool, fn func(Tx) error) error {
//line stdlib/db/db.kuki:217
	sqlTx, err_19 := pool.conn.Begin()
//line stdlib/db/db.kuki:217
	if err_19 != nil {
//line stdlib/db/db.kuki:217
		return err_19
	}
//line stdlib/db/db.kuki:218
	tx := Tx{tx: sqlTx}
//line stdlib/db/db.kuki:220
	defer func() {
//line stdlib/db/db.kuki:221
		if //line stdlib/db/db.kuki:221
		r := recover(); r != nil {
//line stdlib/db/db.kuki:222
			sqlTx.Rollback()
//line stdlib/db/db.kuki:223
			panic(r)
		}
	}()
//line stdlib/db/db.kuki:225
	err := fn(tx)
//line stdlib/db/db.kuki:226
	if err != nil {
//line stdlib/db/db.kuki:227
		sqlTx.Rollback()
//line stdlib/db/db.kuki:228
		return err
	}
//line stdlib/db/db.kuki:230
	return sqlTx.Commit()
}

//line stdlib/db/db.kuki:234
func TransactionWith(pool Pool, opts TxOptions, fn func(Tx) error) error {
//line stdlib/db/db.kuki:235
	txOpts := sql.TxOptions{ReadOnly: opts.ReadOnly}
//line stdlib/db/db.kuki:236
	switch opts.IsolationLevel {
	case IsolationLevelDefault:
//line stdlib/db/db.kuki:238
		txOpts.Isolation = sql.LevelDefault
	case IsolationLevelReadUncommitted:
//line stdlib/db/db.kuki:240
		txOpts.Isolation = sql.LevelReadUncommitted
	case IsolationLevelReadCommitted:
//line stdlib/db/db.kuki:242
		txOpts.Isolation = sql.LevelReadCommitted
	case IsolationLevelRepeatableRead:
//line stdlib/db/db.kuki:244
		txOpts.Isolation = sql.LevelRepeatableRead
	case IsolationLevelSerializable:
//line stdlib/db/db.kuki:246
		txOpts.Isolation = sql.LevelSerializable
	}
//line stdlib/db/db.kuki:248
	sqlTx, err_20 := pool.conn.BeginTx(ctxpkg.Background().Ctx, &txOpts)
//line stdlib/db/db.kuki:248
	if err_20 != nil {
//line stdlib/db/db.kuki:248
		return err_20
	}
//line stdlib/db/db.kuki:249
	tx := Tx{tx: sqlTx}
//line stdlib/db/db.kuki:251
	defer func() {
//line stdlib/db/db.kuki:252
		if //line stdlib/db/db.kuki:252
		r := recover(); r != nil {
//line stdlib/db/db.kuki:253
			sqlTx.Rollback()
//line stdlib/db/db.kuki:254
			panic(r)
		}
	}()
//line stdlib/db/db.kuki:256
	err := fn(tx)
//line stdlib/db/db.kuki:257
	if err != nil {
//line stdlib/db/db.kuki:258
		sqlTx.Rollback()
//line stdlib/db/db.kuki:259
		return err
	}
//line stdlib/db/db.kuki:261
	return sqlTx.Commit()
}

//line stdlib/db/db.kuki:266
func TxQuery(tx Tx, query string, args ...any) (Rows, error) {
//line stdlib/db/db.kuki:267
	rows, err_21 := tx.tx.Query(query, args...)
//line stdlib/db/db.kuki:267
	if err_21 != nil {
		var _zero0 Rows
//line stdlib/db/db.kuki:267
		return _zero0, err_21
	}
//line stdlib/db/db.kuki:268
	result := Rows{rows: rows}
//line stdlib/db/db.kuki:269
	return result, nil
}

//line stdlib/db/db.kuki:274
func TxQueryRow(tx Tx, query string, args ...any) Row {
//line stdlib/db/db.kuki:275
	row := tx.tx.QueryRow(query, args...)
//line stdlib/db/db.kuki:276
	return Row{row: row}
}

//line stdlib/db/db.kuki:282
func TxExec(tx Tx, query string, args ...any) (int64, error) {
//line stdlib/db/db.kuki:283
	result, err_22 := tx.tx.Exec(query, args...)
//line stdlib/db/db.kuki:283
	if err_22 != nil {
//line stdlib/db/db.kuki:283
		return 0, err_22
	}
//line stdlib/db/db.kuki:284
	affected, err_23 := result.RowsAffected()
//line stdlib/db/db.kuki:284
	if err_23 != nil {
//line stdlib/db/db.kuki:284
		return 0, err_23
	}
//line stdlib/db/db.kuki:285
	return affected, nil
}

//line stdlib/db/db.kuki:294
func Count(pool Pool, query string, args ...any) (int64, error) {
//line stdlib/db/db.kuki:295
	row := pool.conn.QueryRow(query, args...)
//line stdlib/db/db.kuki:296
	n := int64(0)
//line stdlib/db/db.kuki:297
	// kukicha: could not infer return count; use explicit capture if incorrect
//line stdlib/db/db.kuki:297
	err_24 := row.Scan(&n)
//line stdlib/db/db.kuki:297
	if err_24 != nil {
//line stdlib/db/db.kuki:297
		return 0, err_24
	}
//line stdlib/db/db.kuki:298
	return n, nil
}

//line stdlib/db/db.kuki:303
func Exists(pool Pool, query string, args ...any) (bool, error) {
//line stdlib/db/db.kuki:304
	row := pool.conn.QueryRow(query, args...)
//line stdlib/db/db.kuki:305
	dummy := 0
//line stdlib/db/db.kuki:306
	if //line stdlib/db/db.kuki:306
	err := row.Scan(&dummy); err != nil {
//line stdlib/db/db.kuki:307
		if errors.Is(err, sql.ErrNoRows) {
//line stdlib/db/db.kuki:308
			return false, nil
		}
//line stdlib/db/db.kuki:309
		return false, err
	}
//line stdlib/db/db.kuki:310
	return true, nil
}

//line stdlib/db/db.kuki:318
func RawDB(pool Pool) *sql.DB {
//line stdlib/db/db.kuki:319
	return pool.conn
}

//line stdlib/db/db.kuki:323
func NewPool(conn *sql.DB) Pool {
//line stdlib/db/db.kuki:324
	return Pool{conn: conn}
}

//line stdlib/db/db.kuki:332
type nullSafeField struct {
	target reflect.Value
}

//line stdlib/db/db.kuki:335
func (s *nullSafeField) Scan(value any) error {
//line stdlib/db/db.kuki:336
	if value == nil {
//line stdlib/db/db.kuki:338
		return nil
	}
//line stdlib/db/db.kuki:340
	src := reflect.ValueOf(value)
//line stdlib/db/db.kuki:341
	if src.Type().ConvertibleTo(s.target.Type()) {
//line stdlib/db/db.kuki:342
		s.target.Set(src.Convert(s.target.Type()))
	} else {
//line stdlib/db/db.kuki:345
		if s.target.Kind() == reflect.String {
//line stdlib/db/db.kuki:346
			s.target.SetString(fmt.Sprintf("%v", value))
		} else {
//line stdlib/db/db.kuki:348
			return fmt.Errorf("db: cannot convert %v to %v", src.Type(), s.target.Type())
		}
	}
//line stdlib/db/db.kuki:349
	return nil
}

//line stdlib/db/db.kuki:353
func structScanners(elem reflect.Value, elemType reflect.Type, columns []string) []any {
//line stdlib/db/db.kuki:354
	numFields := elemType.NumField()
//line stdlib/db/db.kuki:357
	tagMap := make(map[string]int)
//line stdlib/db/db.kuki:358
	nameMap := make(map[string]int)
//line stdlib/db/db.kuki:359
	snakeMap := make(map[string]int)
//line stdlib/db/db.kuki:361
	for i := range numFields {
//line stdlib/db/db.kuki:362
		field := elemType.Field(i)
//line stdlib/db/db.kuki:363
		if !field.IsExported() {
//line stdlib/db/db.kuki:364
			continue
		}
//line stdlib/db/db.kuki:367
		tag := field.Tag.Get("json")
//line stdlib/db/db.kuki:368
		if (tag != "") && (tag != "-") {
//line stdlib/db/db.kuki:369
			parts := strpkg.Split(tag, ",")
//line stdlib/db/db.kuki:370
			tagMap[parts[0]] = i
		}
//line stdlib/db/db.kuki:373
		nameMap[strpkg.ToLower(field.Name)] = i
//line stdlib/db/db.kuki:376
		snakeMap[camelToSnake(field.Name)] = i
	}
//line stdlib/db/db.kuki:379
	ptrs := make([]any, len(columns))
//line stdlib/db/db.kuki:380
	for ci, col := range columns {
//line stdlib/db/db.kuki:381
		lowerCol := strpkg.ToLower(col)
//line stdlib/db/db.kuki:382
		if //line stdlib/db/db.kuki:382
		idx, ok := tagMap[col]; ok {
//line stdlib/db/db.kuki:383
			ptrs[ci] = &nullSafeField{target: elem.Field(idx)}
		} else if //line stdlib/db/db.kuki:384
		idx, ok := nameMap[lowerCol]; ok {
//line stdlib/db/db.kuki:385
			ptrs[ci] = &nullSafeField{target: elem.Field(idx)}
		} else if //line stdlib/db/db.kuki:386
		idx, ok := snakeMap[lowerCol]; ok {
//line stdlib/db/db.kuki:387
			ptrs[ci] = &nullSafeField{target: elem.Field(idx)}
		} else {
//line stdlib/db/db.kuki:389
			throwaway := ""
//line stdlib/db/db.kuki:390
			ptrs[ci] = &throwaway
		}
	}
//line stdlib/db/db.kuki:392
	return ptrs
}

//line stdlib/db/db.kuki:395
func camelToSnake(s string) string {
//line stdlib/db/db.kuki:396
	result := ""
//line stdlib/db/db.kuki:397
	for i, r := range s {
//line stdlib/db/db.kuki:398
		if unicode.IsUpper(r) {
//line stdlib/db/db.kuki:399
			if i > 0 {
//line stdlib/db/db.kuki:400
				result = (result + "_")
			}
//line stdlib/db/db.kuki:401
			result = strpkg.ToLower((result + fmt.Sprintf("%c", r)))
		} else {
//line stdlib/db/db.kuki:403
			result = (result + fmt.Sprintf("%c", r))
		}
	}
//line stdlib/db/db.kuki:404
	return result
}
