// Generated by Kukicha (requires Go 1.26+)

package db_test

import (
	"errors"
	"fmt"
	ctxpkg "github.com/kukichalang/kukicha/stdlib/ctx"
	"github.com/kukichalang/kukicha/stdlib/db"
	"github.com/kukichalang/kukicha/stdlib/test"
	_ "github.com/ncruces/go-sqlite3/driver"
	"testing"
)

//line stdlib/db/db_test.kuki:13
type User struct {
	Id    int64  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

//line stdlib/db/db_test.kuki:18
func setupTestDB(t *testing.T) db.Pool {
//line stdlib/db/db_test.kuki:19
	pool, err_1 := db.Open("sqlite3", ":memory:")
//line stdlib/db/db_test.kuki:19
	if err_1 != nil {
//line stdlib/db/db_test.kuki:19
		panic(fmt.Sprintf("open failed: %v", err_1))
	}
//line stdlib/db/db_test.kuki:20
//line stdlib/db/db_test.kuki:20
	_, err_2 := db.Exec(pool, "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT, email TEXT)")
//line stdlib/db/db_test.kuki:20
	if err_2 != nil {
//line stdlib/db/db_test.kuki:20
		panic(fmt.Sprintf("create failed: %v", err_2))
	}
//line stdlib/db/db_test.kuki:21
//line stdlib/db/db_test.kuki:21
	_, err_3 := db.Exec(pool, "INSERT INTO users (id, name, email) VALUES (?, ?, ?)", 1, "Alice", "alice@example.com")
//line stdlib/db/db_test.kuki:27
	if err_3 != nil {
//line stdlib/db/db_test.kuki:27
		panic(fmt.Sprintf("insert failed: %v", err_3))
	}
//line stdlib/db/db_test.kuki:28
//line stdlib/db/db_test.kuki:28
	_, err_4 := db.Exec(pool, "INSERT INTO users (id, name, email) VALUES (?, ?, ?)", 2, "Bob", "bob@example.com")
//line stdlib/db/db_test.kuki:34
	if err_4 != nil {
//line stdlib/db/db_test.kuki:34
		panic(fmt.Sprintf("insert failed: %v", err_4))
	}
//line stdlib/db/db_test.kuki:35
//line stdlib/db/db_test.kuki:35
	_, err_5 := db.Exec(pool, "INSERT INTO users (id, name, email) VALUES (?, ?, ?)", 3, "Charlie", "charlie@example.com")
//line stdlib/db/db_test.kuki:41
	if err_5 != nil {
//line stdlib/db/db_test.kuki:41
		panic(fmt.Sprintf("insert failed: %v", err_5))
	}
//line stdlib/db/db_test.kuki:42
	return pool
}

//line stdlib/db/db_test.kuki:45
type OpenCloseCase struct {
	name string
}

//line stdlib/db/db_test.kuki:48
func TestOpenAndClose(t *testing.T) {
//line stdlib/db/db_test.kuki:49
	cases := []OpenCloseCase{OpenCloseCase{name: "open and close in-memory"}}
//line stdlib/db/db_test.kuki:51
	for _, tc := range cases {
//line stdlib/db/db_test.kuki:52
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/db/db_test.kuki:53
			pool, err_1 := db.Open("sqlite3", ":memory:")
//line stdlib/db/db_test.kuki:53
			if err_1 != nil {
//line stdlib/db/db_test.kuki:53
				panic(fmt.Sprintf("open: %v", err_1))
			}
//line stdlib/db/db_test.kuki:54
			err := db.Ping(pool)
//line stdlib/db/db_test.kuki:55
			test.AssertNoError(t, err)
//line stdlib/db/db_test.kuki:56
			err = db.Close(pool)
//line stdlib/db/db_test.kuki:57
			test.AssertNoError(t, err)
		})
	}
}

//line stdlib/db/db_test.kuki:61
type OpenInvalidCase struct {
	name    string
	driver  string
	connStr string
}

//line stdlib/db/db_test.kuki:66
func TestOpenInvalidDriver(t *testing.T) {
//line stdlib/db/db_test.kuki:67
	cases := []OpenInvalidCase{OpenInvalidCase{name: "unknown driver", driver: "nosuchdriver", connStr: ""}}
//line stdlib/db/db_test.kuki:71
	for _, tc := range cases {
//line stdlib/db/db_test.kuki:72
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/db/db_test.kuki:73
			_, err := db.Open(tc.driver, tc.connStr)
//line stdlib/db/db_test.kuki:74
			test.AssertError(t, err)
		})
	}
}

//line stdlib/db/db_test.kuki:78
type ExecCase struct {
	name         string
	query        string
	wantAffected int64
}

//line stdlib/db/db_test.kuki:83
func TestExec(t *testing.T) {
//line stdlib/db/db_test.kuki:84
	pool := setupTestDB(t)
//line stdlib/db/db_test.kuki:85
	defer db.Close(pool)
//line stdlib/db/db_test.kuki:86
	cases := []ExecCase{ExecCase{name: "update one row", query: "UPDATE users SET name = 'Alice2' WHERE id = 1", wantAffected: 1}, ExecCase{name: "delete one row", query: "DELETE FROM users WHERE id = 2", wantAffected: 1}}
//line stdlib/db/db_test.kuki:95
	for _, tc := range cases {
//line stdlib/db/db_test.kuki:96
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/db/db_test.kuki:97
			affected, err_1 := db.Exec(pool, tc.query)
//line stdlib/db/db_test.kuki:97
			if err_1 != nil {
//line stdlib/db/db_test.kuki:97
				panic(fmt.Sprintf("exec: %v", err_1))
			}
//line stdlib/db/db_test.kuki:98
			test.AssertEqual(t, affected, tc.wantAffected)
		})
	}
}

//line stdlib/db/db_test.kuki:102
type ScanAllCase struct {
	name    string
	query   string
	wantLen int
}

//line stdlib/db/db_test.kuki:107
func TestScanAll(t *testing.T) {
//line stdlib/db/db_test.kuki:108
	pool := setupTestDB(t)
//line stdlib/db/db_test.kuki:109
	defer db.Close(pool)
//line stdlib/db/db_test.kuki:110
	cases := []ScanAllCase{ScanAllCase{name: "all users", query: "SELECT id, name, email FROM users ORDER BY id", wantLen: 3}, ScanAllCase{name: "filtered", query: "SELECT id, name, email FROM users WHERE id = 1", wantLen: 1}, ScanAllCase{name: "no results", query: "SELECT id, name, email FROM users WHERE id = 999", wantLen: 0}}
//line stdlib/db/db_test.kuki:128
	for _, tc := range cases {
//line stdlib/db/db_test.kuki:129
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/db/db_test.kuki:130
			// pipe step 1: db.Query(...)
//line stdlib/db/db_test.kuki:130
			pipe_1, err_2 := db.Query(pool, tc.query)
//line stdlib/db/db_test.kuki:130
			if err_2 != nil {
//line stdlib/db/db_test.kuki:130
				panic(fmt.Sprintf("scan: %v", err_2))
			}
			// pipe step 2: db.ScanAll(...)
//line stdlib/db/db_test.kuki:130
			users, err_4 := db.ScanAll(pipe_1, []User{})
//line stdlib/db/db_test.kuki:130
			if err_4 != nil {
//line stdlib/db/db_test.kuki:130
				panic(fmt.Sprintf("scan: %v", err_4))
			}
//line stdlib/db/db_test.kuki:131
			test.AssertEqual(t, len(users), tc.wantLen)
		})
	}
}

//line stdlib/db/db_test.kuki:135
type ScanAllValuesCase struct {
	name string
}

//line stdlib/db/db_test.kuki:138
func TestScanAllValues(t *testing.T) {
//line stdlib/db/db_test.kuki:139
	pool := setupTestDB(t)
//line stdlib/db/db_test.kuki:140
	defer db.Close(pool)
//line stdlib/db/db_test.kuki:141
	cases := []ScanAllValuesCase{ScanAllValuesCase{name: "verify field values"}}
//line stdlib/db/db_test.kuki:143
	for _, tc := range cases {
//line stdlib/db/db_test.kuki:144
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/db/db_test.kuki:145
			// pipe step 1: db.Query(...)
//line stdlib/db/db_test.kuki:145
			pipe_1, err_2 := db.Query(pool, "SELECT id, name, email FROM users WHERE id = 1")
//line stdlib/db/db_test.kuki:146
			if err_2 != nil {
//line stdlib/db/db_test.kuki:146
				panic(fmt.Sprintf("scan: %v", err_2))
			}
			// pipe step 2: db.ScanAll(...)
//line stdlib/db/db_test.kuki:146
			users, err_4 := db.ScanAll(pipe_1, []User{})
//line stdlib/db/db_test.kuki:146
			if err_4 != nil {
//line stdlib/db/db_test.kuki:146
				panic(fmt.Sprintf("scan: %v", err_4))
			}
//line stdlib/db/db_test.kuki:148
			test.AssertEqual(t, len(users), 1)
//line stdlib/db/db_test.kuki:149
			test.AssertEqual(t, users[0].Id, int64(1))
//line stdlib/db/db_test.kuki:150
			test.AssertEqual(t, users[0].Name, "Alice")
//line stdlib/db/db_test.kuki:151
			test.AssertEqual(t, users[0].Email, "alice@example.com")
		})
	}
}

//line stdlib/db/db_test.kuki:155
type ScanOneCase struct {
	name    string
	query   string
	wantErr bool
}

//line stdlib/db/db_test.kuki:160
func TestScanOne(t *testing.T) {
//line stdlib/db/db_test.kuki:161
	pool := setupTestDB(t)
//line stdlib/db/db_test.kuki:162
	defer db.Close(pool)
//line stdlib/db/db_test.kuki:163
	cases := []ScanOneCase{ScanOneCase{name: "one row", query: "SELECT id, name, email FROM users WHERE id = 1", wantErr: false}, ScanOneCase{name: "no rows", query: "SELECT id, name, email FROM users WHERE id = 999", wantErr: true}}
//line stdlib/db/db_test.kuki:176
	for _, tc := range cases {
//line stdlib/db/db_test.kuki:177
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/db/db_test.kuki:178
			user, err := db.ScanOne(func() db.Rows { val, _ := db.Query(pool, tc.query); return val }(), User{})
//line stdlib/db/db_test.kuki:179
			if tc.wantErr {
//line stdlib/db/db_test.kuki:180
				test.AssertError(t, err)
			} else {
//line stdlib/db/db_test.kuki:182
				test.AssertNoError(t, err)
//line stdlib/db/db_test.kuki:183
				test.AssertEqual(t, user.Id, int64(1))
//line stdlib/db/db_test.kuki:184
				test.AssertEqual(t, user.Name, "Alice")
			}
		})
	}
}

//line stdlib/db/db_test.kuki:188
type ScanRowCase struct {
	name string
}

//line stdlib/db/db_test.kuki:191
func TestScanRow(t *testing.T) {
//line stdlib/db/db_test.kuki:192
	pool := setupTestDB(t)
//line stdlib/db/db_test.kuki:193
	defer db.Close(pool)
//line stdlib/db/db_test.kuki:194
	cases := []ScanRowCase{ScanRowCase{name: "single row via QueryRow"}}
//line stdlib/db/db_test.kuki:196
	for _, tc := range cases {
//line stdlib/db/db_test.kuki:197
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/db/db_test.kuki:198
			row := db.QueryRow(pool, "SELECT id, name, email FROM users WHERE id = 1")
//line stdlib/db/db_test.kuki:199
			result, err_1 := db.ScanRow(row, User{})
//line stdlib/db/db_test.kuki:199
			if err_1 != nil {
//line stdlib/db/db_test.kuki:199
				panic(fmt.Sprintf("scan: %v", err_1))
			}
//line stdlib/db/db_test.kuki:200
			user := result.(User)
//line stdlib/db/db_test.kuki:201
			test.AssertEqual(t, user.Name, "Alice")
		})
	}
}

//line stdlib/db/db_test.kuki:205
type TransactionCase struct {
	name string
}

//line stdlib/db/db_test.kuki:208
func TestTransaction(t *testing.T) {
//line stdlib/db/db_test.kuki:209
	pool := setupTestDB(t)
//line stdlib/db/db_test.kuki:210
	defer db.Close(pool)
//line stdlib/db/db_test.kuki:211
	cases := []TransactionCase{TransactionCase{name: "commit on success"}}
//line stdlib/db/db_test.kuki:213
	for _, tc := range cases {
//line stdlib/db/db_test.kuki:214
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/db/db_test.kuki:215
			err := db.Transaction(pool, func(tx db.Tx) error {
//line stdlib/db/db_test.kuki:216
//line stdlib/db/db_test.kuki:216
				_, err_1 := db.TxExec(tx, "INSERT INTO users (id, name, email) VALUES (?, ?, ?)", 4, "Diana", "diana@example.com")
//line stdlib/db/db_test.kuki:222
				if err_1 != nil {
//line stdlib/db/db_test.kuki:222
					return err_1
				}
//line stdlib/db/db_test.kuki:223
				return nil
			})
//line stdlib/db/db_test.kuki:226
			test.AssertNoError(t, err)
//line stdlib/db/db_test.kuki:228
			found, err_1 := db.Exists(pool, "SELECT 1 FROM users WHERE id = 4")
//line stdlib/db/db_test.kuki:228
			if err_1 != nil {
//line stdlib/db/db_test.kuki:228
				panic(fmt.Sprintf("exists: %v", err_1))
			}
//line stdlib/db/db_test.kuki:229
			test.AssertTrue(t, found)
		})
	}
}

//line stdlib/db/db_test.kuki:233
type TransactionRollbackCase struct {
	name string
}

//line stdlib/db/db_test.kuki:236
func TestTransactionRollback(t *testing.T) {
//line stdlib/db/db_test.kuki:237
	pool := setupTestDB(t)
//line stdlib/db/db_test.kuki:238
	defer db.Close(pool)
//line stdlib/db/db_test.kuki:239
	cases := []TransactionRollbackCase{TransactionRollbackCase{name: "rollback on error"}}
//line stdlib/db/db_test.kuki:241
	for _, tc := range cases {
//line stdlib/db/db_test.kuki:242
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/db/db_test.kuki:243
			err := db.Transaction(pool, func(tx db.Tx) error {
//line stdlib/db/db_test.kuki:244
//line stdlib/db/db_test.kuki:244
				_, err_1 := db.TxExec(tx, "INSERT INTO users (id, name, email) VALUES (?, ?, ?)", 5, "Eve", "eve@example.com")
//line stdlib/db/db_test.kuki:250
				if err_1 != nil {
//line stdlib/db/db_test.kuki:250
					return err_1
				}
//line stdlib/db/db_test.kuki:251
				return errors.New("deliberate rollback")
			})
//line stdlib/db/db_test.kuki:254
			test.AssertError(t, err)
//line stdlib/db/db_test.kuki:256
			found, err_1 := db.Exists(pool, "SELECT 1 FROM users WHERE id = 5")
//line stdlib/db/db_test.kuki:256
			if err_1 != nil {
//line stdlib/db/db_test.kuki:256
				panic(fmt.Sprintf("exists: %v", err_1))
			}
//line stdlib/db/db_test.kuki:257
			test.AssertFalse(t, found)
		})
	}
}

//line stdlib/db/db_test.kuki:261
type CountCase struct {
	name      string
	query     string
	wantCount int64
}

//line stdlib/db/db_test.kuki:266
func TestCount(t *testing.T) {
//line stdlib/db/db_test.kuki:267
	pool := setupTestDB(t)
//line stdlib/db/db_test.kuki:268
	defer db.Close(pool)
//line stdlib/db/db_test.kuki:269
	cases := []CountCase{CountCase{name: "all users", query: "SELECT COUNT(*) FROM users", wantCount: 3}, CountCase{name: "filtered", query: "SELECT COUNT(*) FROM users WHERE id > 1", wantCount: 2}}
//line stdlib/db/db_test.kuki:274
	for _, tc := range cases {
//line stdlib/db/db_test.kuki:275
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/db/db_test.kuki:276
			n, err_1 := db.Count(pool, tc.query)
//line stdlib/db/db_test.kuki:276
			if err_1 != nil {
//line stdlib/db/db_test.kuki:276
				panic(fmt.Sprintf("count: %v", err_1))
			}
//line stdlib/db/db_test.kuki:277
			test.AssertEqual(t, n, tc.wantCount)
		})
	}
}

//line stdlib/db/db_test.kuki:281
type ExistsCase struct {
	name       string
	query      string
	wantExists bool
}

//line stdlib/db/db_test.kuki:286
func TestExists(t *testing.T) {
//line stdlib/db/db_test.kuki:287
	pool := setupTestDB(t)
//line stdlib/db/db_test.kuki:288
	defer db.Close(pool)
//line stdlib/db/db_test.kuki:289
	cases := []ExistsCase{ExistsCase{name: "exists", query: "SELECT 1 FROM users WHERE id = 1", wantExists: true}, ExistsCase{name: "not exists", query: "SELECT 1 FROM users WHERE id = 999", wantExists: false}}
//line stdlib/db/db_test.kuki:298
	for _, tc := range cases {
//line stdlib/db/db_test.kuki:299
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/db/db_test.kuki:300
			found, err_1 := db.Exists(pool, tc.query)
//line stdlib/db/db_test.kuki:300
			if err_1 != nil {
//line stdlib/db/db_test.kuki:300
				panic(fmt.Sprintf("exists: %v", err_1))
			}
//line stdlib/db/db_test.kuki:301
			test.AssertEqual(t, found, tc.wantExists)
		})
	}
}

//line stdlib/db/db_test.kuki:305
type NullUser struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
	Bio  string `json:"bio"`
}

//line stdlib/db/db_test.kuki:310
type NullCase struct {
	name string
}

//line stdlib/db/db_test.kuki:313
func TestNullHandling(t *testing.T) {
//line stdlib/db/db_test.kuki:314
	pool, err_6 := db.Open("sqlite3", ":memory:")
//line stdlib/db/db_test.kuki:314
	if err_6 != nil {
//line stdlib/db/db_test.kuki:314
		panic(fmt.Sprintf("open: %v", err_6))
	}
//line stdlib/db/db_test.kuki:315
	defer db.Close(pool)
//line stdlib/db/db_test.kuki:316
//line stdlib/db/db_test.kuki:316
	_, err_7 := db.Exec(pool, "CREATE TABLE null_test (id INTEGER PRIMARY KEY, name TEXT, bio TEXT)")
//line stdlib/db/db_test.kuki:316
	if err_7 != nil {
//line stdlib/db/db_test.kuki:316
		panic(fmt.Sprintf("create: %v", err_7))
	}
//line stdlib/db/db_test.kuki:317
//line stdlib/db/db_test.kuki:317
	_, err_8 := db.Exec(pool, "INSERT INTO null_test (id, name) VALUES (?, ?)", 1, "Alice")
//line stdlib/db/db_test.kuki:317
	if err_8 != nil {
//line stdlib/db/db_test.kuki:317
		panic(fmt.Sprintf("insert: %v", err_8))
	}
//line stdlib/db/db_test.kuki:319
	cases := []NullCase{NullCase{name: "null becomes zero value"}}
//line stdlib/db/db_test.kuki:321
	for _, tc := range cases {
//line stdlib/db/db_test.kuki:322
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/db/db_test.kuki:323
			row := db.QueryRow(pool, "SELECT id, name, bio FROM null_test WHERE id = 1")
//line stdlib/db/db_test.kuki:324
			result, err_1 := db.ScanRow(row, NullUser{})
//line stdlib/db/db_test.kuki:324
			if err_1 != nil {
//line stdlib/db/db_test.kuki:324
				panic(fmt.Sprintf("scan: %v", err_1))
			}
//line stdlib/db/db_test.kuki:325
			user := result.(NullUser)
//line stdlib/db/db_test.kuki:326
			test.AssertEqual(t, user.Name, "Alice")
//line stdlib/db/db_test.kuki:327
			test.AssertEqual(t, user.Bio, "")
		})
	}
}

//line stdlib/db/db_test.kuki:331
func TestQueryCtx(t *testing.T) {
//line stdlib/db/db_test.kuki:332
	pool := setupTestDB(t)
//line stdlib/db/db_test.kuki:333
	defer db.Close(pool)
//line stdlib/db/db_test.kuki:334
	h := ctxpkg.WithCancel(ctxpkg.Background())
//line stdlib/db/db_test.kuki:335
	defer h.Cancel()
//line stdlib/db/db_test.kuki:337
	// pipe step 1: db.QueryCtx(...)
//line stdlib/db/db_test.kuki:337
	pipe_9, err_10 := db.QueryCtx(h, pool, "SELECT id, name, email FROM users WHERE id = 1")
//line stdlib/db/db_test.kuki:338
	if err_10 != nil {
//line stdlib/db/db_test.kuki:338
		panic(fmt.Sprintf("scan: %v", err_10))
	}
	// pipe step 2: db.ScanAll(...)
//line stdlib/db/db_test.kuki:338
	users, err_12 := db.ScanAll(pipe_9, []User{})
//line stdlib/db/db_test.kuki:338
	if err_12 != nil {
//line stdlib/db/db_test.kuki:338
		panic(fmt.Sprintf("scan: %v", err_12))
	}
//line stdlib/db/db_test.kuki:339
	test.AssertEqual(t, len(users), 1)
}

//line stdlib/db/db_test.kuki:342
func TestExecCtx(t *testing.T) {
//line stdlib/db/db_test.kuki:343
	pool := setupTestDB(t)
//line stdlib/db/db_test.kuki:344
	defer db.Close(pool)
//line stdlib/db/db_test.kuki:345
	h := ctxpkg.WithCancel(ctxpkg.Background())
//line stdlib/db/db_test.kuki:346
	defer h.Cancel()
//line stdlib/db/db_test.kuki:348
	affected, err_13 := db.ExecCtx(h, pool, "UPDATE users SET name = 'Alice3' WHERE id = 1")
//line stdlib/db/db_test.kuki:348
	if err_13 != nil {
//line stdlib/db/db_test.kuki:348
		panic(fmt.Sprintf("exec: %v", err_13))
	}
//line stdlib/db/db_test.kuki:349
	test.AssertEqual(t, affected, int64(1))
}

//line stdlib/db/db_test.kuki:352
func TestLastInsertId(t *testing.T) {
//line stdlib/db/db_test.kuki:353
	pool := setupTestDB(t)
//line stdlib/db/db_test.kuki:354
	defer db.Close(pool)
//line stdlib/db/db_test.kuki:356
	id, err_14 := db.LastInsertId(pool, "INSERT INTO users (name, email) VALUES (?, ?)", "Dave", "dave@example.com")
//line stdlib/db/db_test.kuki:361
	if err_14 != nil {
//line stdlib/db/db_test.kuki:361
		panic(fmt.Sprintf("exec: %v", err_14))
	}
//line stdlib/db/db_test.kuki:362
	test.AssertEqual(t, id, int64(4))
}
