// Generated by Kukicha (requires Go 1.26+)

package term

import (
	"os"
	"strconv"
	"unicode/utf8"
)

//line stdlib/term/term.kuki:25
var colorOverridden bool

//line stdlib/term/term.kuki:27
var colorOverrideValue bool

//line stdlib/term/term.kuki:31
func IsTTY(f *os.File) bool {
//line stdlib/term/term.kuki:32
	if f == nil {
//line stdlib/term/term.kuki:33
		return false
	}
//line stdlib/term/term.kuki:34
	info, err_1 := f.Stat()
//line stdlib/term/term.kuki:34
	if err_1 != nil {
//line stdlib/term/term.kuki:34
		return false
	}
//line stdlib/term/term.kuki:35
	return ((info.Mode() & os.ModeCharDevice) != 0)
}

//line stdlib/term/term.kuki:44
func ColorEnabledFor(w *os.File) bool {
//line stdlib/term/term.kuki:45
	if colorOverridden {
//line stdlib/term/term.kuki:46
		return colorOverrideValue
	}
//line stdlib/term/term.kuki:47
	if os.Getenv("FORCE_COLOR") != "" {
//line stdlib/term/term.kuki:48
		return true
	}
//line stdlib/term/term.kuki:49
	if os.Getenv("NO_COLOR") != "" {
//line stdlib/term/term.kuki:50
		return false
	}
//line stdlib/term/term.kuki:51
	return IsTTY(w)
}

//line stdlib/term/term.kuki:54
func ColorEnabled() bool {
//line stdlib/term/term.kuki:55
	return ColorEnabledFor(os.Stdout)
}

//line stdlib/term/term.kuki:60
func SetColorEnabled(enabled bool) {
//line stdlib/term/term.kuki:61
	colorOverridden = true
//line stdlib/term/term.kuki:62
	colorOverrideValue = enabled
}

//line stdlib/term/term.kuki:66
func ResetColorOverride() {
//line stdlib/term/term.kuki:67
	colorOverridden = false
//line stdlib/term/term.kuki:68
	colorOverrideValue = false
}

//line stdlib/term/term.kuki:78
func VisibleWidth(s string) int {
//line stdlib/term/term.kuki:79
	width := 0
//line stdlib/term/term.kuki:80
	i := 0
//line stdlib/term/term.kuki:81
	n := len(s)
//line stdlib/term/term.kuki:82
	for i < n {
//line stdlib/term/term.kuki:83
		if ((s[i] == 0x1b) && ((i + 1) < n)) && (s[(i+1)] == 0x5b) {
//line stdlib/term/term.kuki:85
			i = (i + 2)
//line stdlib/term/term.kuki:86
			for i < n {
//line stdlib/term/term.kuki:87
				b := s[i]
//line stdlib/term/term.kuki:88
				i = (i + 1)
//line stdlib/term/term.kuki:89
				if (b >= 0x40) && (b <= 0x7e) {
//line stdlib/term/term.kuki:90
					break
				}
			}
//line stdlib/term/term.kuki:91
			continue
		}
//line stdlib/term/term.kuki:92
		_, size := utf8.DecodeRuneInString(s[i:])
//line stdlib/term/term.kuki:93
		if size == 0 {
//line stdlib/term/term.kuki:94
			i = (i + 1)
		} else {
//line stdlib/term/term.kuki:96
			i = (i + size)
		}
//line stdlib/term/term.kuki:97
		width = (width + 1)
	}
//line stdlib/term/term.kuki:98
	return width
}

//line stdlib/term/term.kuki:103
func PadRightVisible(s string, n int) string {
//line stdlib/term/term.kuki:104
	w := VisibleWidth(s)
//line stdlib/term/term.kuki:105
	if w >= n {
//line stdlib/term/term.kuki:106
		return s
	}
//line stdlib/term/term.kuki:107
	pad := (n - w)
//line stdlib/term/term.kuki:108
	out := s
//line stdlib/term/term.kuki:109
	j := 0
//line stdlib/term/term.kuki:110
	for j < pad {
//line stdlib/term/term.kuki:111
		out = (out + " ")
//line stdlib/term/term.kuki:112
		j = (j + 1)
	}
//line stdlib/term/term.kuki:113
	return out
}

//line stdlib/term/term.kuki:119
func Width() int {
//line stdlib/term/term.kuki:120
	cols := os.Getenv("COLUMNS")
//line stdlib/term/term.kuki:121
	if cols == "" {
//line stdlib/term/term.kuki:122
		return 80
	}
//line stdlib/term/term.kuki:123
	n, err := strconv.Atoi(cols)
//line stdlib/term/term.kuki:124
	if (err != nil) || (n <= 0) {
//line stdlib/term/term.kuki:125
		return 80
	}
//line stdlib/term/term.kuki:126
	return n
}
