// Generated by Kukicha (requires Go 1.26+)

package random

import "math/rand"

//line stdlib/random/random.kuki:20
func String(length int) string {
//line stdlib/random/random.kuki:21
	charset := "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
//line stdlib/random/random.kuki:22
	b := make([]byte, length)
//line stdlib/random/random.kuki:23
	for i := range length {
//line stdlib/random/random.kuki:24
		b[i] = charset[rand.Intn(len(charset))]
	}
//line stdlib/random/random.kuki:25
	return string(b)
}

//line stdlib/random/random.kuki:29
func Int(min int, max int) int {
//line stdlib/random/random.kuki:30
	if min >= max {
//line stdlib/random/random.kuki:31
		return min
	}
//line stdlib/random/random.kuki:32
	return (min + rand.Intn((max - min)))
}

//line stdlib/random/random.kuki:36
func Float(min float64, max float64) float64 {
//line stdlib/random/random.kuki:37
	if min >= max {
//line stdlib/random/random.kuki:38
		return min
	}
//line stdlib/random/random.kuki:39
	return (min + (rand.Float64() * (max - min)))
}
