// Generated by Kukicha (requires Go 1.26+)

package cli

import (
	"context"
	"fmt"
	"github.com/kukichalang/kukicha/stdlib/color"
	"github.com/kukichalang/kukicha/stdlib/json"
	kukistring "github.com/kukichalang/kukicha/stdlib/string"
	"os"
	"strconv"
)

//line stdlib/cli/cli.kuki:14
type ArgDef struct {
	Name        string
	Description string
	Required    bool
}

//line stdlib/cli/cli.kuki:20
type FlagDef struct {
	Name         string
	Description  string
	DefaultValue string
	Required     bool
	Type         string
	Aliases      []string
}

//line stdlib/cli/cli.kuki:29
type SubcommandDef struct {
	Name        string
	Description string
	Args        []ArgDef
	Flags       []FlagDef
	Subcommands []*SubcommandDef
	ActionFunc  func(Args)
	RestArgName string
}

//line stdlib/cli/cli.kuki:42
func (cmd *SubcommandDef) Flag(name string, desc string, defaultValue string) *SubcommandDef {
//line stdlib/cli/cli.kuki:43
	cmd.Flags = append(cmd.Flags, FlagDef{Name: name, Description: desc, DefaultValue: defaultValue, Required: false, Aliases: make([]string, 0)})
//line stdlib/cli/cli.kuki:50
	return cmd
}

//line stdlib/cli/cli.kuki:53
func (cmd *SubcommandDef) StringFlag(name string, desc string, defaultValue string) *SubcommandDef {
//line stdlib/cli/cli.kuki:54
	cmd.Flags = append(cmd.Flags, FlagDef{Name: name, Description: desc, DefaultValue: defaultValue, Required: false, Type: "string", Aliases: make([]string, 0)})
//line stdlib/cli/cli.kuki:62
	return cmd
}

//line stdlib/cli/cli.kuki:66
func (cmd *SubcommandDef) BoolFlag(name string, desc string, defaultValue bool) *SubcommandDef {
//line stdlib/cli/cli.kuki:67
	dv := func() string {
		if defaultValue {
			return "true"
		} else {
			return "false"
		}
	}()
//line stdlib/cli/cli.kuki:68
	cmd.Flags = append(cmd.Flags, FlagDef{Name: name, Description: desc, DefaultValue: dv, Required: false, Type: "bool", Aliases: make([]string, 0)})
//line stdlib/cli/cli.kuki:76
	return cmd
}

//line stdlib/cli/cli.kuki:80
func (cmd *SubcommandDef) IntFlag(name string, desc string, defaultValue int) *SubcommandDef {
//line stdlib/cli/cli.kuki:81
	cmd.Flags = append(cmd.Flags, FlagDef{Name: name, Description: desc, DefaultValue: fmt.Sprintf("%d", defaultValue), Required: false, Type: "int", Aliases: make([]string, 0)})
//line stdlib/cli/cli.kuki:89
	return cmd
}

//line stdlib/cli/cli.kuki:95
func (cmd *SubcommandDef) Short(alias string) *SubcommandDef {
//line stdlib/cli/cli.kuki:96
	if len(cmd.Flags) == 0 {
//line stdlib/cli/cli.kuki:97
		panic(fmt.Sprintf("cli.Short(%v): no flag to attach alias to — call Short after a Flag/StringFlag/BoolFlag/IntFlag/RequiredFlag in the builder chain", alias))
	}
//line stdlib/cli/cli.kuki:98
	last := (len(cmd.Flags) - 1)
//line stdlib/cli/cli.kuki:99
	cmd.Flags[last].Aliases = append(cmd.Flags[last].Aliases, alias)
//line stdlib/cli/cli.kuki:100
	return cmd
}

//line stdlib/cli/cli.kuki:103
func (cmd *SubcommandDef) RequiredFlag(name string, desc string) *SubcommandDef {
//line stdlib/cli/cli.kuki:104
	cmd.Flags = append(cmd.Flags, FlagDef{Name: name, Description: desc, DefaultValue: "", Required: true, Aliases: make([]string, 0)})
//line stdlib/cli/cli.kuki:111
	return cmd
}

//line stdlib/cli/cli.kuki:115
func (cmd *SubcommandDef) Arg(name string, description string) *SubcommandDef {
//line stdlib/cli/cli.kuki:116
	cmd.Args = append(cmd.Args, ArgDef{Name: name, Description: description, Required: false})
//line stdlib/cli/cli.kuki:117
	return cmd
}

//line stdlib/cli/cli.kuki:120
func (cmd *SubcommandDef) RequiredArg(name string, description string) *SubcommandDef {
//line stdlib/cli/cli.kuki:121
	cmd.Args = append(cmd.Args, ArgDef{Name: name, Description: description, Required: true})
//line stdlib/cli/cli.kuki:122
	return cmd
}

//line stdlib/cli/cli.kuki:127
func (cmd *SubcommandDef) RestArg(name string, description string) *SubcommandDef {
//line stdlib/cli/cli.kuki:128
	cmd.RestArgName = name
//line stdlib/cli/cli.kuki:129
	return cmd
}

//line stdlib/cli/cli.kuki:133
func (cmd *SubcommandDef) Action(handler func(Args)) *SubcommandDef {
//line stdlib/cli/cli.kuki:134
	cmd.ActionFunc = handler
//line stdlib/cli/cli.kuki:135
	return cmd
}

//line stdlib/cli/cli.kuki:139
func (cmd *SubcommandDef) WithCommands(subs ...*SubcommandDef) *SubcommandDef {
//line stdlib/cli/cli.kuki:140
	for _, s := range subs {
//line stdlib/cli/cli.kuki:141
		cmd.Subcommands = append(cmd.Subcommands, s)
	}
//line stdlib/cli/cli.kuki:142
	return cmd
}

//line stdlib/cli/cli.kuki:151
func NewCommand(name string, desc string) *SubcommandDef {
//line stdlib/cli/cli.kuki:152
	return &SubcommandDef{Name: name, Description: desc, Args: make([]ArgDef, 0), Flags: make([]FlagDef, 0), Subcommands: make([]*SubcommandDef, 0), ActionFunc: nil, RestArgName: ""}
}

//line stdlib/cli/cli.kuki:163
type App struct {
	Name          string
	Description   string
	Version       string
	Args          []ArgDef
	Flags         []FlagDef
	GlobalFlags   []FlagDef
	Subcommands   []*SubcommandDef
	ActionFunc    func(Args)
	DefaultAction func(Args)
	RestArgName   string
}

//line stdlib/cli/cli.kuki:176
type Args struct {
	values map[string]string
	rest   map[string][]string
}

//line stdlib/cli/cli.kuki:182
func NewArgs(values map[string]string) Args {
//line stdlib/cli/cli.kuki:183
	return Args{values: values, rest: make(map[string][]string)}
}

//line stdlib/cli/cli.kuki:189
func New(name string) *App {
//line stdlib/cli/cli.kuki:190
	return &App{Name: name, Description: "", Version: "", Args: make([]ArgDef, 0), Flags: make([]FlagDef, 0), GlobalFlags: make([]FlagDef, 0), Subcommands: make([]*SubcommandDef, 0), ActionFunc: nil, DefaultAction: nil, RestArgName: ""}
}

//line stdlib/cli/cli.kuki:205
func Version(app *App, version string) *App {
//line stdlib/cli/cli.kuki:206
	app.Version = version
//line stdlib/cli/cli.kuki:207
	return app
}

//line stdlib/cli/cli.kuki:211
func Description(app *App, desc string) *App {
//line stdlib/cli/cli.kuki:212
	app.Description = desc
//line stdlib/cli/cli.kuki:213
	return app
}

//line stdlib/cli/cli.kuki:217
func Arg(app *App, name string, description string) *App {
//line stdlib/cli/cli.kuki:218
	app.Args = append(app.Args, ArgDef{Name: name, Description: description, Required: false})
//line stdlib/cli/cli.kuki:219
	return app
}

//line stdlib/cli/cli.kuki:222
func RequiredArg(app *App, name string, description string) *App {
//line stdlib/cli/cli.kuki:223
	app.Args = append(app.Args, ArgDef{Name: name, Description: description, Required: true})
//line stdlib/cli/cli.kuki:224
	return app
}

//line stdlib/cli/cli.kuki:228
func AddFlag(app *App, name string, description string, defaultValue string) *App {
//line stdlib/cli/cli.kuki:229
	app.Flags = append(app.Flags, FlagDef{Name: name, Description: description, DefaultValue: defaultValue, Required: false, Aliases: make([]string, 0)})
//line stdlib/cli/cli.kuki:236
	return app
}

//line stdlib/cli/cli.kuki:240
func StringFlag(app *App, name string, desc string, defaultValue string) *App {
//line stdlib/cli/cli.kuki:241
	app.Flags = append(app.Flags, FlagDef{Name: name, Description: desc, DefaultValue: defaultValue, Required: false, Type: "string", Aliases: make([]string, 0)})
//line stdlib/cli/cli.kuki:249
	return app
}

//line stdlib/cli/cli.kuki:253
func BoolFlag(app *App, name string, desc string, defaultValue bool) *App {
//line stdlib/cli/cli.kuki:254
	dv := func() string {
		if defaultValue {
			return "true"
		} else {
			return "false"
		}
	}()
//line stdlib/cli/cli.kuki:255
	app.Flags = append(app.Flags, FlagDef{Name: name, Description: desc, DefaultValue: dv, Required: false, Type: "bool", Aliases: make([]string, 0)})
//line stdlib/cli/cli.kuki:263
	return app
}

//line stdlib/cli/cli.kuki:267
func IntFlag(app *App, name string, desc string, defaultValue int) *App {
//line stdlib/cli/cli.kuki:268
	app.Flags = append(app.Flags, FlagDef{Name: name, Description: desc, DefaultValue: fmt.Sprintf("%d", defaultValue), Required: false, Type: "int", Aliases: make([]string, 0)})
//line stdlib/cli/cli.kuki:276
	return app
}

//line stdlib/cli/cli.kuki:282
func Short(app *App, alias string) *App {
//line stdlib/cli/cli.kuki:283
	if len(app.Flags) == 0 {
//line stdlib/cli/cli.kuki:284
		panic(fmt.Sprintf("cli.Short(%v): no flag to attach alias to — call Short after a Flag/StringFlag/BoolFlag/IntFlag/RequiredFlag in the builder chain", alias))
	}
//line stdlib/cli/cli.kuki:285
	last := (len(app.Flags) - 1)
//line stdlib/cli/cli.kuki:286
	app.Flags[last].Aliases = append(app.Flags[last].Aliases, alias)
//line stdlib/cli/cli.kuki:287
	return app
}

//line stdlib/cli/cli.kuki:292
func RestArg(app *App, name string, description string) *App {
//line stdlib/cli/cli.kuki:293
	app.RestArgName = name
//line stdlib/cli/cli.kuki:294
	return app
}

//line stdlib/cli/cli.kuki:297
func RequiredFlag(app *App, name string, description string) *App {
//line stdlib/cli/cli.kuki:298
	app.Flags = append(app.Flags, FlagDef{Name: name, Description: description, DefaultValue: "", Required: true, Aliases: make([]string, 0)})
//line stdlib/cli/cli.kuki:305
	return app
}

//line stdlib/cli/cli.kuki:309
func Action(app *App, handler func(Args)) *App {
//line stdlib/cli/cli.kuki:310
	app.ActionFunc = handler
//line stdlib/cli/cli.kuki:311
	return app
}

//line stdlib/cli/cli.kuki:314
func DefaultAction(app *App, handler func(Args)) *App {
//line stdlib/cli/cli.kuki:315
	app.DefaultAction = handler
//line stdlib/cli/cli.kuki:316
	return app
}

//line stdlib/cli/cli.kuki:326
func WithCommands(app *App, cmds ...*SubcommandDef) *App {
//line stdlib/cli/cli.kuki:327
	for _, c := range cmds {
//line stdlib/cli/cli.kuki:328
		app.Subcommands = append(app.Subcommands, c)
	}
//line stdlib/cli/cli.kuki:329
	return app
}

//line stdlib/cli/cli.kuki:333
func GlobalFlag(app *App, name string, desc string, defaultValue string) *App {
//line stdlib/cli/cli.kuki:334
	app.GlobalFlags = append(app.GlobalFlags, FlagDef{Name: name, Description: desc, DefaultValue: defaultValue, Required: false, Aliases: make([]string, 0)})
//line stdlib/cli/cli.kuki:341
	return app
}

//line stdlib/cli/cli.kuki:345
func BoolGlobalFlag(app *App, name string, desc string, defaultValue bool) *App {
//line stdlib/cli/cli.kuki:346
	dv := func() string {
		if defaultValue {
			return "true"
		} else {
			return "false"
		}
	}()
//line stdlib/cli/cli.kuki:347
	app.GlobalFlags = append(app.GlobalFlags, FlagDef{Name: name, Description: desc, DefaultValue: dv, Required: false, Type: "bool", Aliases: make([]string, 0)})
//line stdlib/cli/cli.kuki:355
	return app
}

//line stdlib/cli/cli.kuki:359
func IntGlobalFlag(app *App, name string, desc string, defaultValue int) *App {
//line stdlib/cli/cli.kuki:360
	app.GlobalFlags = append(app.GlobalFlags, FlagDef{Name: name, Description: desc, DefaultValue: fmt.Sprintf("%d", defaultValue), Required: false, Type: "int", Aliases: make([]string, 0)})
//line stdlib/cli/cli.kuki:368
	return app
}

//line stdlib/cli/cli.kuki:371
func RunApp(app *App) error {
//line stdlib/cli/cli.kuki:372
	return Run(app)
}

//line stdlib/cli/cli.kuki:375
func Error(msg string) {
//line stdlib/cli/cli.kuki:376
	fmt.Fprintln(os.Stderr, msg)
}

//line stdlib/cli/cli.kuki:379
func Run(app *App) error {
//line stdlib/cli/cli.kuki:380
	args := os.Args
//line stdlib/cli/cli.kuki:381
	if len(args) < 2 {
//line stdlib/cli/cli.kuki:382
		values := defaultValues(app, nil)
//line stdlib/cli/cli.kuki:383
		rootArgs := Args{values: values, rest: make(map[string][]string)}
//line stdlib/cli/cli.kuki:384
		if app.ActionFunc != nil {
//line stdlib/cli/cli.kuki:385
			app.ActionFunc(rootArgs)
//line stdlib/cli/cli.kuki:386
			return nil
		}
//line stdlib/cli/cli.kuki:387
		if app.DefaultAction != nil {
//line stdlib/cli/cli.kuki:388
			app.DefaultAction(rootArgs)
//line stdlib/cli/cli.kuki:389
			return nil
		}
//line stdlib/cli/cli.kuki:390
		printHelp(app)
//line stdlib/cli/cli.kuki:391
		return nil
	}
//line stdlib/cli/cli.kuki:393
	sub := args[1]
//line stdlib/cli/cli.kuki:394
	if (sub == "--version") || (sub == "-v") {
//line stdlib/cli/cli.kuki:395
		if app.Version != "" {
//line stdlib/cli/cli.kuki:396
			fmt.Println(fmt.Sprintf("%v %v", app.Name, app.Version))
		} else {
//line stdlib/cli/cli.kuki:398
			fmt.Println(app.Name)
		}
//line stdlib/cli/cli.kuki:399
		return nil
	}
//line stdlib/cli/cli.kuki:400
	if ((sub == "help") || (sub == "-h")) || (sub == "--help") {
//line stdlib/cli/cli.kuki:401
		printHelp(app)
//line stdlib/cli/cli.kuki:402
		return nil
	}
//line stdlib/cli/cli.kuki:405
	leaf, leafArgStart := findLeaf(app, args)
//line stdlib/cli/cli.kuki:406
	if leaf != nil {
//line stdlib/cli/cli.kuki:407
		return runLeaf(app, leaf, args, leafArgStart)
	}
//line stdlib/cli/cli.kuki:410
	rootAction := app.DefaultAction
//line stdlib/cli/cli.kuki:411
	if rootAction == nil {
//line stdlib/cli/cli.kuki:412
		rootAction = app.ActionFunc
	}
//line stdlib/cli/cli.kuki:413
	if rootAction != nil {
//line stdlib/cli/cli.kuki:414
		values := defaultValues(app, nil)
//line stdlib/cli/cli.kuki:415
		positionalNames := make([]string, 0)
//line stdlib/cli/cli.kuki:416
		for _, a := range app.Args {
//line stdlib/cli/cli.kuki:417
			positionalNames = append(positionalNames, a.Name)
		}
//line stdlib/cli/cli.kuki:418
		allFlagDefs := make([]FlagDef, 0)
//line stdlib/cli/cli.kuki:419
		allFlagDefs = append(allFlagDefs, app.GlobalFlags...)
//line stdlib/cli/cli.kuki:420
		allFlagDefs = append(allFlagDefs, app.Flags...)
//line stdlib/cli/cli.kuki:421
		restMap := make(map[string][]string)
//line stdlib/cli/cli.kuki:430
		parseFlagsAndPositionals(args, 1, values, restMap, positionalNames, allFlagDefs, app.RestArgName)
//line stdlib/cli/cli.kuki:431
		rootArgs := Args{values: values, rest: restMap}
//line stdlib/cli/cli.kuki:432
		rootAction(rootArgs)
//line stdlib/cli/cli.kuki:433
		return nil
	}
//line stdlib/cli/cli.kuki:435
	printHelp(app)
//line stdlib/cli/cli.kuki:436
	return nil
}

//line stdlib/cli/cli.kuki:439
func defaultValues(app *App, leaf *SubcommandDef) map[string]string {
//line stdlib/cli/cli.kuki:440
	values := make(map[string]string)
//line stdlib/cli/cli.kuki:441
	for _, f := range app.GlobalFlags {
//line stdlib/cli/cli.kuki:442
		values[f.Name] = f.DefaultValue
	}
//line stdlib/cli/cli.kuki:443
	if leaf == nil {
//line stdlib/cli/cli.kuki:444
		for _, f := range app.Flags {
//line stdlib/cli/cli.kuki:445
			values[f.Name] = f.DefaultValue
		}
	} else {
//line stdlib/cli/cli.kuki:447
		for _, f := range leaf.Flags {
//line stdlib/cli/cli.kuki:448
			values[f.Name] = f.DefaultValue
		}
	}
//line stdlib/cli/cli.kuki:449
	return values
}

//line stdlib/cli/cli.kuki:456
func parseFlagsAndPositionals(args []string, start int, values map[string]string, rest map[string][]string, positionalNames []string, flagDefs []FlagDef, restArgName string) {
//line stdlib/cli/cli.kuki:457
	aliasMap := make(map[string]string)
//line stdlib/cli/cli.kuki:458
	typeMap := make(map[string]string)
//line stdlib/cli/cli.kuki:459
	for _, f := range flagDefs {
//line stdlib/cli/cli.kuki:460
		if f.Type != "" {
//line stdlib/cli/cli.kuki:461
			typeMap[f.Name] = f.Type
		}
//line stdlib/cli/cli.kuki:462
		for _, a := range f.Aliases {
//line stdlib/cli/cli.kuki:463
			aliasMap[a] = f.Name
		}
	}
//line stdlib/cli/cli.kuki:465
	posIndex := 0
//line stdlib/cli/cli.kuki:466
	i := start
//line stdlib/cli/cli.kuki:467
	for i < len(args) {
//line stdlib/cli/cli.kuki:468
		arg := args[i]
//line stdlib/cli/cli.kuki:469
		if kukistring.HasPrefix(arg, "-") && kukistring.Contains(arg, "=") {
//line stdlib/cli/cli.kuki:471
			parts := kukistring.SplitN(arg, "=", 2)
//line stdlib/cli/cli.kuki:472
			rawName := kukistring.TrimPrefix(parts[0], "--")
//line stdlib/cli/cli.kuki:473
			rawName = kukistring.TrimPrefix(rawName, "-")
//line stdlib/cli/cli.kuki:474
			canonical := func() string {
				if aliasMap[rawName] != "" {
					return aliasMap[rawName]
				} else {
					return rawName
				}
			}()
//line stdlib/cli/cli.kuki:475
			values[canonical] = parts[1]
//line stdlib/cli/cli.kuki:476
			i = (i + 1)
		} else if kukistring.HasPrefix(arg, "--") {
//line stdlib/cli/cli.kuki:478
			name := kukistring.TrimPrefix(arg, "--")
//line stdlib/cli/cli.kuki:479
			canonical := func() string {
				if aliasMap[name] != "" {
					return aliasMap[name]
				} else {
					return name
				}
			}()
//line stdlib/cli/cli.kuki:480
			if typeMap[canonical] == "bool" {
//line stdlib/cli/cli.kuki:481
				values[canonical] = "true"
//line stdlib/cli/cli.kuki:482
				i = (i + 1)
			} else if (typeMap[canonical] != "") && ((i + 1) < len(args)) {
//line stdlib/cli/cli.kuki:484
				values[canonical] = args[(i + 1)]
//line stdlib/cli/cli.kuki:485
				i = (i + 2)
			} else if typeMap[canonical] != "" {
//line stdlib/cli/cli.kuki:487
				i = (i + 1)
			} else if ((i + 1) < len(args)) && !kukistring.HasPrefix(args[(i+1)], "-") {
//line stdlib/cli/cli.kuki:489
				values[canonical] = args[(i + 1)]
//line stdlib/cli/cli.kuki:490
				i = (i + 2)
			} else {
//line stdlib/cli/cli.kuki:492
				values[canonical] = "true"
//line stdlib/cli/cli.kuki:493
				i = (i + 1)
			}
		} else if kukistring.HasPrefix(arg, "-") {
//line stdlib/cli/cli.kuki:495
			name := kukistring.TrimPrefix(arg, "-")
//line stdlib/cli/cli.kuki:496
			canonical := func() string {
				if aliasMap[name] != "" {
					return aliasMap[name]
				} else {
					return name
				}
			}()
//line stdlib/cli/cli.kuki:497
			if typeMap[canonical] == "bool" {
//line stdlib/cli/cli.kuki:498
				values[canonical] = "true"
//line stdlib/cli/cli.kuki:499
				i = (i + 1)
			} else if (typeMap[canonical] != "") && ((i + 1) < len(args)) {
//line stdlib/cli/cli.kuki:501
				values[canonical] = args[(i + 1)]
//line stdlib/cli/cli.kuki:502
				i = (i + 2)
			} else if typeMap[canonical] != "" {
//line stdlib/cli/cli.kuki:504
				i = (i + 1)
			} else if ((i + 1) < len(args)) && !kukistring.HasPrefix(args[(i+1)], "-") {
//line stdlib/cli/cli.kuki:506
				values[canonical] = args[(i + 1)]
//line stdlib/cli/cli.kuki:507
				i = (i + 2)
			} else {
//line stdlib/cli/cli.kuki:509
				values[canonical] = "true"
//line stdlib/cli/cli.kuki:510
				i = (i + 1)
			}
		} else {
//line stdlib/cli/cli.kuki:512
			if posIndex < len(positionalNames) {
//line stdlib/cli/cli.kuki:513
				values[positionalNames[posIndex]] = arg
//line stdlib/cli/cli.kuki:514
				posIndex = (posIndex + 1)
			} else if restArgName != "" {
//line stdlib/cli/cli.kuki:516
				rest[restArgName] = append(rest[restArgName], arg)
			}
//line stdlib/cli/cli.kuki:517
			i = (i + 1)
		}
	}
}

//line stdlib/cli/cli.kuki:520
func runLeaf(app *App, leaf *SubcommandDef, args []string, argStart int) error {
//line stdlib/cli/cli.kuki:521
	values := defaultValues(app, leaf)
//line stdlib/cli/cli.kuki:523
	positionalNames := make([]string, 0)
//line stdlib/cli/cli.kuki:524
	for _, a := range leaf.Args {
//line stdlib/cli/cli.kuki:525
		positionalNames = append(positionalNames, a.Name)
	}
//line stdlib/cli/cli.kuki:526
	allFlagDefs := make([]FlagDef, 0)
//line stdlib/cli/cli.kuki:527
	allFlagDefs = append(allFlagDefs, app.GlobalFlags...)
//line stdlib/cli/cli.kuki:528
	allFlagDefs = append(allFlagDefs, leaf.Flags...)
//line stdlib/cli/cli.kuki:529
	restMap := make(map[string][]string)
//line stdlib/cli/cli.kuki:538
	parseFlagsAndPositionals(args, argStart, values, restMap, positionalNames, allFlagDefs, leaf.RestArgName)
//line stdlib/cli/cli.kuki:540
	for _, f := range leaf.Flags {
//line stdlib/cli/cli.kuki:541
		if f.Required && (values[f.Name] == "") {
//line stdlib/cli/cli.kuki:542
			return fmt.Errorf("flag --%v is required", f.Name)
		}
	}
//line stdlib/cli/cli.kuki:543
	for _, a := range leaf.Args {
//line stdlib/cli/cli.kuki:544
		if a.Required && (values[a.Name] == "") {
//line stdlib/cli/cli.kuki:545
			return fmt.Errorf("argument %v is required", a.Name)
		}
	}
//line stdlib/cli/cli.kuki:547
	leafArgs := Args{values: values, rest: restMap}
//line stdlib/cli/cli.kuki:548
	if leaf.ActionFunc == nil {
//line stdlib/cli/cli.kuki:549
		return fmt.Errorf("no action defined for command %v", leaf.Name)
	}
//line stdlib/cli/cli.kuki:550
	leaf.ActionFunc(leafArgs)
//line stdlib/cli/cli.kuki:551
	return nil
}

//line stdlib/cli/cli.kuki:555
func findLeaf(app *App, args []string) (*SubcommandDef, int) {
//line stdlib/cli/cli.kuki:556
	if len(args) < 2 {
//line stdlib/cli/cli.kuki:557
		return nil, 0
	}
//line stdlib/cli/cli.kuki:558
	subName := args[1]
//line stdlib/cli/cli.kuki:559
	for _, s := range app.Subcommands {
//line stdlib/cli/cli.kuki:560
		if s.Name == subName {
//line stdlib/cli/cli.kuki:561
			return matchNested(s, args, 2)
		}
	}
//line stdlib/cli/cli.kuki:562
	return nil, 0
}

//line stdlib/cli/cli.kuki:564
func matchNested(cmd *SubcommandDef, args []string, index int) (*SubcommandDef, int) {
//line stdlib/cli/cli.kuki:565
	if index >= len(args) {
//line stdlib/cli/cli.kuki:566
		return cmd, index
	}
//line stdlib/cli/cli.kuki:567
	nextSub := args[index]
//line stdlib/cli/cli.kuki:568
	for _, s := range cmd.Subcommands {
//line stdlib/cli/cli.kuki:569
		if s.Name == nextSub {
//line stdlib/cli/cli.kuki:570
			return matchNested(s, args, (index + 1))
		}
	}
//line stdlib/cli/cli.kuki:571
	return cmd, index
}

//line stdlib/cli/cli.kuki:575
func printHelp(app *App) {
//line stdlib/cli/cli.kuki:576
	s := color.NewStyler(os.Stdout)
//line stdlib/cli/cli.kuki:579
	usageLabel := s.Bold("Usage:")
//line stdlib/cli/cli.kuki:580
	nameStyled := s.Cyan(app.Name)
//line stdlib/cli/cli.kuki:581
	fmt.Println(fmt.Sprintf("%v %v [flags] [subcommand]", usageLabel, nameStyled))
//line stdlib/cli/cli.kuki:583
	if app.Description != "" {
//line stdlib/cli/cli.kuki:584
		fmt.Println("")
//line stdlib/cli/cli.kuki:585
		fmt.Println(app.Description)
	}
//line stdlib/cli/cli.kuki:587
	if (len(app.GlobalFlags) > 0) || (len(app.Flags) > 0) {
//line stdlib/cli/cli.kuki:588
		fmt.Println("")
//line stdlib/cli/cli.kuki:589
		fmt.Println(s.Bold("Flags:"))
//line stdlib/cli/cli.kuki:590
		nameWidth := flagNameWidth(app)
//line stdlib/cli/cli.kuki:591
		for _, f := range app.GlobalFlags {
//line stdlib/cli/cli.kuki:592
			printFlagRow(s, f, nameWidth)
		}
//line stdlib/cli/cli.kuki:593
		for _, f := range app.Flags {
//line stdlib/cli/cli.kuki:594
			printFlagRow(s, f, nameWidth)
		}
	}
//line stdlib/cli/cli.kuki:596
	if len(app.Subcommands) > 0 {
//line stdlib/cli/cli.kuki:597
		fmt.Println("")
//line stdlib/cli/cli.kuki:598
		fmt.Println(s.Bold("Subcommands:"))
//line stdlib/cli/cli.kuki:599
		nameWidth := subcommandNameWidth(app)
//line stdlib/cli/cli.kuki:600
		for _, sub := range app.Subcommands {
//line stdlib/cli/cli.kuki:601
			padded := padRight(sub.Name, nameWidth)
//line stdlib/cli/cli.kuki:602
			fmt.Println(fmt.Sprintf("  %v  %v", s.Cyan(padded), s.Dim(sub.Description)))
		}
	}
//line stdlib/cli/cli.kuki:604
	if app.Version != "" {
//line stdlib/cli/cli.kuki:605
		fmt.Println("")
//line stdlib/cli/cli.kuki:606
		versionLabel := s.Dim("Version:")
//line stdlib/cli/cli.kuki:607
		fmt.Println(fmt.Sprintf("%v %v", versionLabel, app.Version))
	}
}

//line stdlib/cli/cli.kuki:611
func printFlagRow(s color.Styler, f FlagDef, width int) {
//line stdlib/cli/cli.kuki:612
	flagName := fmt.Sprintf("--%v", f.Name)
//line stdlib/cli/cli.kuki:613
	padded := padRight(flagName, width)
//line stdlib/cli/cli.kuki:614
	suffix := ""
//line stdlib/cli/cli.kuki:615
	if (f.DefaultValue != "") && (f.DefaultValue != "false") {
//line stdlib/cli/cli.kuki:616
		suffix = fmt.Sprintf(" (default: %v)", f.DefaultValue)
	}
//line stdlib/cli/cli.kuki:617
	fmt.Println(fmt.Sprintf("  %v  %v", s.Cyan(padded), s.Dim((f.Description + suffix))))
}

//line stdlib/cli/cli.kuki:622
func flagNameWidth(app *App) int {
//line stdlib/cli/cli.kuki:623
	max := 0
//line stdlib/cli/cli.kuki:624
	for _, f := range app.GlobalFlags {
//line stdlib/cli/cli.kuki:625
		n := len(fmt.Sprintf("--%v", f.Name))
//line stdlib/cli/cli.kuki:626
		if n > max {
//line stdlib/cli/cli.kuki:627
			max = n
		}
	}
//line stdlib/cli/cli.kuki:628
	for _, f := range app.Flags {
//line stdlib/cli/cli.kuki:629
		n := len(fmt.Sprintf("--%v", f.Name))
//line stdlib/cli/cli.kuki:630
		if n > max {
//line stdlib/cli/cli.kuki:631
			max = n
		}
	}
//line stdlib/cli/cli.kuki:632
	if max > 24 {
//line stdlib/cli/cli.kuki:633
		return 24
	}
//line stdlib/cli/cli.kuki:634
	return max
}

//line stdlib/cli/cli.kuki:637
func subcommandNameWidth(app *App) int {
//line stdlib/cli/cli.kuki:638
	max := 0
//line stdlib/cli/cli.kuki:639
	for _, sub := range app.Subcommands {
//line stdlib/cli/cli.kuki:640
		if len(sub.Name) > max {
//line stdlib/cli/cli.kuki:641
			max = len(sub.Name)
		}
	}
//line stdlib/cli/cli.kuki:642
	if max > 20 {
//line stdlib/cli/cli.kuki:643
		return 20
	}
//line stdlib/cli/cli.kuki:644
	return max
}

//line stdlib/cli/cli.kuki:648
func padRight(text string, n int) string {
//line stdlib/cli/cli.kuki:649
	if len(text) >= n {
//line stdlib/cli/cli.kuki:650
		return text
	}
//line stdlib/cli/cli.kuki:651
	pad := (n - len(text))
//line stdlib/cli/cli.kuki:652
	return (text + kukistring.Repeat(" ", pad))
}

//line stdlib/cli/cli.kuki:655
func IsJSON(args Args) bool {
//line stdlib/cli/cli.kuki:656
	val := args.values["json"]
//line stdlib/cli/cli.kuki:657
	if ((val == "true") || (val == "1")) || (val == "yes") {
//line stdlib/cli/cli.kuki:658
		return true
	}
//line stdlib/cli/cli.kuki:659
	val = args.values["output"]
//line stdlib/cli/cli.kuki:660
	return (val == "json")
}

//line stdlib/cli/cli.kuki:663
func (args Args) Context() context.Context {
//line stdlib/cli/cli.kuki:664
	return context.Background()
}

//line stdlib/cli/cli.kuki:667
func (args Args) Respond(data any) {
//line stdlib/cli/cli.kuki:668
	if IsJSON(args) {
//line stdlib/cli/cli.kuki:669
//line stdlib/cli/cli.kuki:669
		err_1 := json.WriteOutput(data)
//line stdlib/cli/cli.kuki:669
		if err_1 != nil {
//line stdlib/cli/cli.kuki:669
			Fatal(fmt.Sprintf("failed to encode json: %v", err_1))
		}
	} else {
//line stdlib/cli/cli.kuki:671
		fmt.Println(fmt.Sprint(data))
	}
}

//line stdlib/cli/cli.kuki:674
func IsTTY() bool {
//line stdlib/cli/cli.kuki:675
	info, err_2 := os.Stdout.Stat()
//line stdlib/cli/cli.kuki:675
	if err_2 != nil {
//line stdlib/cli/cli.kuki:675
		return false
	}
//line stdlib/cli/cli.kuki:676
	return ((info.Mode() & os.ModeCharDevice) != 0)
}

//line stdlib/cli/cli.kuki:679
func Info(msg string) {
//line stdlib/cli/cli.kuki:680
	fmt.Println(msg)
}

//line stdlib/cli/cli.kuki:683
func Success(msg string) {
//line stdlib/cli/cli.kuki:684
	fmt.Println(msg)
}

//line stdlib/cli/cli.kuki:687
func Fatal(msg string) {
//line stdlib/cli/cli.kuki:688
	fmt.Fprintln(os.Stderr, msg)
//line stdlib/cli/cli.kuki:689
	os.Exit(1)
}

//line stdlib/cli/cli.kuki:692
func GetString(args Args, name string) string {
//line stdlib/cli/cli.kuki:693
	return args.values[name]
}

//line stdlib/cli/cli.kuki:696
func GetBool(args Args, name string) bool {
//line stdlib/cli/cli.kuki:697
	val := args.values[name]
//line stdlib/cli/cli.kuki:698
	return (((val == "true") || (val == "1")) || (val == "yes"))
}

//line stdlib/cli/cli.kuki:701
func GetInt(args Args, name string) (int, error) {
//line stdlib/cli/cli.kuki:702
	strVal := args.values[name]
//line stdlib/cli/cli.kuki:703
	if strVal == "" {
//line stdlib/cli/cli.kuki:704
		return 0, fmt.Errorf("argument %v not found", name)
	}
//line stdlib/cli/cli.kuki:706
	return strconv.Atoi(strVal)
}

//line stdlib/cli/cli.kuki:710
func GetRest(args Args, name string) []string {
//line stdlib/cli/cli.kuki:711
	vals := args.rest[name]
//line stdlib/cli/cli.kuki:712
	if vals == nil {
//line stdlib/cli/cli.kuki:713
		return make([]string, 0)
	}
//line stdlib/cli/cli.kuki:714
	return vals
}

//line stdlib/cli/cli.kuki:720
func ParseArgs(app *App, osArgs []string) Args {
//line stdlib/cli/cli.kuki:721
	values := make(map[string]string)
//line stdlib/cli/cli.kuki:722
	for _, f := range app.GlobalFlags {
//line stdlib/cli/cli.kuki:723
		values[f.Name] = f.DefaultValue
	}
//line stdlib/cli/cli.kuki:724
	for _, f := range app.Flags {
//line stdlib/cli/cli.kuki:725
		values[f.Name] = f.DefaultValue
	}
//line stdlib/cli/cli.kuki:726
	positionalNames := make([]string, 0)
//line stdlib/cli/cli.kuki:727
	for _, a := range app.Args {
//line stdlib/cli/cli.kuki:728
		positionalNames = append(positionalNames, a.Name)
	}
//line stdlib/cli/cli.kuki:729
	allFlagDefs := make([]FlagDef, 0)
//line stdlib/cli/cli.kuki:730
	allFlagDefs = append(allFlagDefs, app.GlobalFlags...)
//line stdlib/cli/cli.kuki:731
	allFlagDefs = append(allFlagDefs, app.Flags...)
//line stdlib/cli/cli.kuki:732
	restMap := make(map[string][]string)
//line stdlib/cli/cli.kuki:733
	start := func() int {
		if len(osArgs) > 0 {
			return 1
		} else {
			return 0
		}
	}()
//line stdlib/cli/cli.kuki:742
	parseFlagsAndPositionals(osArgs, start, values, restMap, positionalNames, allFlagDefs, app.RestArgName)
//line stdlib/cli/cli.kuki:743
	return Args{values: values, rest: restMap}
}
