// Generated by Kukicha (requires Go 1.26+)

package test_test

import (
	"errors"
	kukistring "github.com/kukichalang/kukicha/stdlib/string"
	"github.com/kukichalang/kukicha/stdlib/test"
	"testing"
)

//line stdlib/test/test_test.kuki:19
func TestAssertEqualPass(t *testing.T) {
//line stdlib/test/test_test.kuki:20
	test.AssertEqual(t, 1, 1)
//line stdlib/test/test_test.kuki:21
	test.AssertEqual(t, "foo", "foo")
//line stdlib/test/test_test.kuki:22
	test.AssertEqual(t, []int{1, 2, 3}, []int{1, 2, 3})
//line stdlib/test/test_test.kuki:23
	test.AssertEqual(t, map[string]int{"a": 1}, map[string]int{"a": 1})
}

//line stdlib/test/test_test.kuki:25
func TestAssertNotEqualPass(t *testing.T) {
//line stdlib/test/test_test.kuki:26
	test.AssertNotEqual(t, 1, 2)
//line stdlib/test/test_test.kuki:27
	test.AssertNotEqual(t, "foo", "bar")
//line stdlib/test/test_test.kuki:28
	test.AssertNotEqual(t, []int{1}, []int{2})
}

//line stdlib/test/test_test.kuki:30
func TestAssertTrueFalsePass(t *testing.T) {
//line stdlib/test/test_test.kuki:31
	test.AssertTrue(t, true)
//line stdlib/test/test_test.kuki:32
	test.AssertTrue(t, (1 == 1))
//line stdlib/test/test_test.kuki:33
	test.AssertFalse(t, false)
//line stdlib/test/test_test.kuki:34
	test.AssertFalse(t, (1 == 2))
}

//line stdlib/test/test_test.kuki:36
func TestAssertNoErrorPass(t *testing.T) {
//line stdlib/test/test_test.kuki:37
	test.AssertNoError(t, nil)
}

//line stdlib/test/test_test.kuki:39
func TestAssertErrorPass(t *testing.T) {
//line stdlib/test/test_test.kuki:40
	test.AssertError(t, errors.New("boom"))
}

//line stdlib/test/test_test.kuki:42
func TestAssertNilNotNilPass(t *testing.T) {
//line stdlib/test/test_test.kuki:43
	test.AssertNil(t, nil)
//line stdlib/test/test_test.kuki:44
	test.AssertNotNil(t, "value")
//line stdlib/test/test_test.kuki:45
	test.AssertNotNil(t, 42)
}

//line stdlib/test/test_test.kuki:47
func TestAssertNotEmptyPass(t *testing.T) {
//line stdlib/test/test_test.kuki:48
	test.AssertNotEmpty(t, "hello")
//line stdlib/test/test_test.kuki:49
	test.AssertNotEmpty(t, 42)
//line stdlib/test/test_test.kuki:50
	test.AssertNotEmpty(t, errors.New("oops"))
}

//line stdlib/test/test_test.kuki:56
func TestFormatArgsDoNotPanic(t *testing.T) {
//line stdlib/test/test_test.kuki:57
	test.AssertEqual(t, 1, 1, "case %s at %d", "foo", 3)
//line stdlib/test/test_test.kuki:58
	test.AssertTrue(t, true, "flag=%v", true)
}

//line stdlib/test/test_test.kuki:62
func TestAssertEqualFail(t *testing.T) {
//line stdlib/test/test_test.kuki:63
	f := &FakeTB{}
//line stdlib/test/test_test.kuki:64
	test.AssertEqual(f, 1, 2)
//line stdlib/test/test_test.kuki:65
	if len(f.Errs) == 0 {
//line stdlib/test/test_test.kuki:66
		t.Fatalf("expected Errorf to be called")
	}
//line stdlib/test/test_test.kuki:67
	if !kukistring.Contains(f.Errs[0], "expected 2, got 1") {
//line stdlib/test/test_test.kuki:68
		t.Errorf("bad message: %s", f.Errs[0])
	}
}

//line stdlib/test/test_test.kuki:70
func TestAssertEqualFailWithMessage(t *testing.T) {
//line stdlib/test/test_test.kuki:71
	f := &FakeTB{}
//line stdlib/test/test_test.kuki:72
	test.AssertEqual(f, 1, 2, "case %s", "foo")
//line stdlib/test/test_test.kuki:73
	if len(f.Errs) == 0 {
//line stdlib/test/test_test.kuki:74
		t.Fatalf("expected Errorf to be called")
	}
//line stdlib/test/test_test.kuki:75
	if !kukistring.Contains(f.Errs[0], "case foo: expected 2, got 1") {
//line stdlib/test/test_test.kuki:76
		t.Errorf("bad message: %s", f.Errs[0])
	}
}

//line stdlib/test/test_test.kuki:78
func TestAssertNotEqualFail(t *testing.T) {
//line stdlib/test/test_test.kuki:79
	f := &FakeTB{}
//line stdlib/test/test_test.kuki:80
	test.AssertNotEqual(f, 5, 5)
//line stdlib/test/test_test.kuki:81
	if (len(f.Errs) == 0) || !kukistring.Contains(f.Errs[0], "expected values to differ") {
//line stdlib/test/test_test.kuki:82
		t.Errorf("bad message: %v", f.Errs)
	}
}

//line stdlib/test/test_test.kuki:84
func TestAssertTrueFail(t *testing.T) {
//line stdlib/test/test_test.kuki:85
	f := &FakeTB{}
//line stdlib/test/test_test.kuki:86
	test.AssertTrue(f, false)
//line stdlib/test/test_test.kuki:87
	if (len(f.Errs) == 0) || !kukistring.Contains(f.Errs[0], "expected true") {
//line stdlib/test/test_test.kuki:88
		t.Errorf("bad message: %v", f.Errs)
	}
}

//line stdlib/test/test_test.kuki:90
func TestAssertFalseFail(t *testing.T) {
//line stdlib/test/test_test.kuki:91
	f := &FakeTB{}
//line stdlib/test/test_test.kuki:92
	test.AssertFalse(f, true)
//line stdlib/test/test_test.kuki:93
	if (len(f.Errs) == 0) || !kukistring.Contains(f.Errs[0], "expected false") {
//line stdlib/test/test_test.kuki:94
		t.Errorf("bad message: %v", f.Errs)
	}
}

//line stdlib/test/test_test.kuki:96
func TestAssertNoErrorFail(t *testing.T) {
//line stdlib/test/test_test.kuki:97
	f := &FakeTB{}
//line stdlib/test/test_test.kuki:98
	test.AssertNoError(f, errors.New("boom"))
//line stdlib/test/test_test.kuki:99
	if (len(f.Errs) == 0) || !kukistring.Contains(f.Errs[0], "unexpected error") {
//line stdlib/test/test_test.kuki:100
		t.Errorf("bad message: %v", f.Errs)
	}
}

//line stdlib/test/test_test.kuki:102
func TestAssertErrorFail(t *testing.T) {
//line stdlib/test/test_test.kuki:103
	f := &FakeTB{}
//line stdlib/test/test_test.kuki:104
	test.AssertError(f, nil)
//line stdlib/test/test_test.kuki:105
	if (len(f.Errs) == 0) || !kukistring.Contains(f.Errs[0], "expected an error") {
//line stdlib/test/test_test.kuki:106
		t.Errorf("bad message: %v", f.Errs)
	}
}

//line stdlib/test/test_test.kuki:108
func TestAssertNilFail(t *testing.T) {
//line stdlib/test/test_test.kuki:109
	f := &FakeTB{}
//line stdlib/test/test_test.kuki:110
	test.AssertNil(f, "not nil")
//line stdlib/test/test_test.kuki:111
	if (len(f.Errs) == 0) || !kukistring.Contains(f.Errs[0], "expected nil") {
//line stdlib/test/test_test.kuki:112
		t.Errorf("bad message: %v", f.Errs)
	}
}

//line stdlib/test/test_test.kuki:114
func TestAssertNotNilFail(t *testing.T) {
//line stdlib/test/test_test.kuki:115
	f := &FakeTB{}
//line stdlib/test/test_test.kuki:116
	test.AssertNotNil(f, nil)
//line stdlib/test/test_test.kuki:117
	if (len(f.Errs) == 0) || !kukistring.Contains(f.Errs[0], "expected non-nil") {
//line stdlib/test/test_test.kuki:118
		t.Errorf("bad message: %v", f.Errs)
	}
}

//line stdlib/test/test_test.kuki:120
func TestAssertNotEmptyFailNil(t *testing.T) {
//line stdlib/test/test_test.kuki:121
	f := &FakeTB{}
//line stdlib/test/test_test.kuki:122
	test.AssertNotEmpty(f, nil)
//line stdlib/test/test_test.kuki:123
	if (len(f.Errs) == 0) || !kukistring.Contains(f.Errs[0], "got nil") {
//line stdlib/test/test_test.kuki:124
		t.Errorf("bad message: %v", f.Errs)
	}
}

//line stdlib/test/test_test.kuki:126
func TestAssertNotEmptyFailZero(t *testing.T) {
//line stdlib/test/test_test.kuki:127
	f := &FakeTB{}
//line stdlib/test/test_test.kuki:128
	test.AssertNotEmpty(f, "")
//line stdlib/test/test_test.kuki:129
	if (len(f.Errs) == 0) || !kukistring.Contains(f.Errs[0], "zero value") {
//line stdlib/test/test_test.kuki:130
		t.Errorf("bad message: %v", f.Errs)
	}
}
