// Generated by Kukicha (requires Go 1.26+)

package test

import (
	"fmt"
	"reflect"
	"testing"
)

//line stdlib/test/test.kuki:14
func formatMessage(defaultMsg string, msgAndArgs []any) string {
//line stdlib/test/test.kuki:15
	if len(msgAndArgs) == 0 {
//line stdlib/test/test.kuki:16
		return defaultMsg
	}
//line stdlib/test/test.kuki:17
	if len(msgAndArgs) == 1 {
//line stdlib/test/test.kuki:18
		return fmt.Sprintf("%v", msgAndArgs[0])
	}
//line stdlib/test/test.kuki:19
	format, ok := msgAndArgs[0].(string)
//line stdlib/test/test.kuki:20
	if ok {
//line stdlib/test/test.kuki:21
		return fmt.Sprintf(format, msgAndArgs[1:]...)
	}
//line stdlib/test/test.kuki:22
	return fmt.Sprintf("%v", msgAndArgs[0])
}

//line stdlib/test/test.kuki:25
func AssertEqual(t testing.TB, got any, want any, msgAndArgs ...any) {
//line stdlib/test/test.kuki:26
	t.Helper()
//line stdlib/test/test.kuki:27
	if !reflect.DeepEqual(got, want) {
//line stdlib/test/test.kuki:28
		msg := formatMessage("", msgAndArgs)
//line stdlib/test/test.kuki:29
		if msg != "" {
//line stdlib/test/test.kuki:30
			t.Errorf("%s: expected %v, got %v", msg, want, got)
		} else {
//line stdlib/test/test.kuki:32
			t.Errorf("expected %v, got %v", want, got)
		}
	}
}

//line stdlib/test/test.kuki:35
func AssertNotEqual(t testing.TB, got any, want any, msgAndArgs ...any) {
//line stdlib/test/test.kuki:36
	t.Helper()
//line stdlib/test/test.kuki:37
	if reflect.DeepEqual(got, want) {
//line stdlib/test/test.kuki:38
		msg := formatMessage("", msgAndArgs)
//line stdlib/test/test.kuki:39
		if msg != "" {
//line stdlib/test/test.kuki:40
			t.Errorf("%s: expected values to differ, but both are %v", msg, got)
		} else {
//line stdlib/test/test.kuki:42
			t.Errorf("expected values to differ, but both are %v", got)
		}
	}
}

//line stdlib/test/test.kuki:45
func AssertTrue(t testing.TB, condition bool, msgAndArgs ...any) {
//line stdlib/test/test.kuki:46
	t.Helper()
//line stdlib/test/test.kuki:47
	if !condition {
//line stdlib/test/test.kuki:48
		t.Errorf("%s", formatMessage("expected true", msgAndArgs))
	}
}

//line stdlib/test/test.kuki:51
func AssertFalse(t testing.TB, condition bool, msgAndArgs ...any) {
//line stdlib/test/test.kuki:52
	t.Helper()
//line stdlib/test/test.kuki:53
	if condition {
//line stdlib/test/test.kuki:54
		t.Errorf("%s", formatMessage("expected false", msgAndArgs))
	}
}

//line stdlib/test/test.kuki:57
func AssertNoError(t testing.TB, err error, msgAndArgs ...any) {
//line stdlib/test/test.kuki:58
	t.Helper()
//line stdlib/test/test.kuki:59
	if err != nil {
//line stdlib/test/test.kuki:60
		msg := formatMessage("", msgAndArgs)
//line stdlib/test/test.kuki:61
		if msg != "" {
//line stdlib/test/test.kuki:62
			t.Errorf("%s: unexpected error: %v", msg, err)
		} else {
//line stdlib/test/test.kuki:64
			t.Errorf("unexpected error: %v", err)
		}
	}
}

//line stdlib/test/test.kuki:67
func AssertError(t testing.TB, err error, msgAndArgs ...any) {
//line stdlib/test/test.kuki:68
	t.Helper()
//line stdlib/test/test.kuki:69
	if err == nil {
//line stdlib/test/test.kuki:70
		t.Errorf("%s", formatMessage("expected an error, got nil", msgAndArgs))
	}
}

//line stdlib/test/test.kuki:77
func AssertNotEmpty(t testing.TB, val any, msgAndArgs ...any) {
//line stdlib/test/test.kuki:78
	t.Helper()
//line stdlib/test/test.kuki:79
	if val == nil {
//line stdlib/test/test.kuki:80
		t.Errorf("%s", formatMessage("expected non-empty value, got nil", msgAndArgs))
//line stdlib/test/test.kuki:81
		return
	}
//line stdlib/test/test.kuki:82
	v := reflect.ValueOf(val)
//line stdlib/test/test.kuki:83
	if v.IsZero() {
//line stdlib/test/test.kuki:84
		t.Errorf("%s", formatMessage("expected non-empty value, got zero value", msgAndArgs))
	}
}

//line stdlib/test/test.kuki:87
func AssertNil(t testing.TB, val any, msgAndArgs ...any) {
//line stdlib/test/test.kuki:88
	t.Helper()
//line stdlib/test/test.kuki:89
	if val != nil {
//line stdlib/test/test.kuki:90
		t.Errorf("%s: got %v", formatMessage("expected nil", msgAndArgs), val)
	}
}

//line stdlib/test/test.kuki:93
func AssertNotNil(t testing.TB, val any, msgAndArgs ...any) {
//line stdlib/test/test.kuki:94
	t.Helper()
//line stdlib/test/test.kuki:95
	if val == nil {
//line stdlib/test/test.kuki:96
		t.Errorf("%s", formatMessage("expected non-nil value", msgAndArgs))
	}
}
