// Generated by Kukicha (requires Go 1.26+)

package llm_test

import (
	"github.com/kukichalang/kukicha/stdlib/llm"
	"github.com/kukichalang/kukicha/stdlib/llm/anthropic"
	"github.com/kukichalang/kukicha/stdlib/llm/chat"
	"github.com/kukichalang/kukicha/stdlib/llm/responses"
	"github.com/kukichalang/kukicha/stdlib/test"
	"testing"
)

//line stdlib/llm/llm_test.kuki:13
type GetTextCase struct {
	name    string
	content string
	want    string
}

//line stdlib/llm/llm_test.kuki:18
func TestChatGetText(t *testing.T) {
//line stdlib/llm/llm_test.kuki:19
	cases := []GetTextCase{GetTextCase{name: "basic content", content: "response text", want: "response text"}, GetTextCase{name: "empty content", content: "", want: ""}}
//line stdlib/llm/llm_test.kuki:24
	for _, tc := range cases {
//line stdlib/llm/llm_test.kuki:25
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/llm/llm_test.kuki:26
			msg := chat.ResponseMessage{}
//line stdlib/llm/llm_test.kuki:27
			msg.Role = "assistant"
//line stdlib/llm/llm_test.kuki:28
			msg.Content = tc.content
//line stdlib/llm/llm_test.kuki:30
			choice := chat.Choice{}
//line stdlib/llm/llm_test.kuki:31
			choice.Message = msg
//line stdlib/llm/llm_test.kuki:33
			comp := chat.Completion{}
//line stdlib/llm/llm_test.kuki:34
			comp.Choices = []chat.Choice{choice}
//line stdlib/llm/llm_test.kuki:36
			test.AssertEqual(t, chat.GetText(comp), tc.want)
		})
	}
}

//line stdlib/llm/llm_test.kuki:40
type GetToolCallsCase struct {
	name      string
	callID    string
	funcName  string
	wantCount int
}

//line stdlib/llm/llm_test.kuki:46
func TestChatGetToolCalls(t *testing.T) {
//line stdlib/llm/llm_test.kuki:47
	cases := []GetToolCallsCase{GetToolCallsCase{name: "one tool call", callID: "call-1", funcName: "do_thing", wantCount: 1}}
//line stdlib/llm/llm_test.kuki:56
	for _, tc := range cases {
//line stdlib/llm/llm_test.kuki:57
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/llm/llm_test.kuki:58
			toolFunc := chat.ToolCallFunction{}
//line stdlib/llm/llm_test.kuki:59
			toolFunc.Name = tc.funcName
//line stdlib/llm/llm_test.kuki:60
			toolFunc.Arguments = "{}"
//line stdlib/llm/llm_test.kuki:62
			toolCall := chat.ToolCall{}
//line stdlib/llm/llm_test.kuki:63
			toolCall.ID = tc.callID
//line stdlib/llm/llm_test.kuki:64
			toolCall.Type = "function"
//line stdlib/llm/llm_test.kuki:65
			toolCall.Function = toolFunc
//line stdlib/llm/llm_test.kuki:67
			msg := chat.ResponseMessage{}
//line stdlib/llm/llm_test.kuki:68
			msg.Role = "assistant"
//line stdlib/llm/llm_test.kuki:69
			msg.ToolCalls = []chat.ToolCall{toolCall}
//line stdlib/llm/llm_test.kuki:71
			choice := chat.Choice{}
//line stdlib/llm/llm_test.kuki:72
			choice.Message = msg
//line stdlib/llm/llm_test.kuki:73
			comp := chat.Completion{}
//line stdlib/llm/llm_test.kuki:74
			comp.Choices = []chat.Choice{choice}
//line stdlib/llm/llm_test.kuki:76
			calls := chat.GetToolCalls(comp)
//line stdlib/llm/llm_test.kuki:77
			test.AssertEqual(t, len(calls), tc.wantCount)
//line stdlib/llm/llm_test.kuki:78
			if len(calls) > 0 {
//line stdlib/llm/llm_test.kuki:79
				test.AssertEqual(t, calls[0].Function.Name, tc.funcName)
			}
		})
	}
}

//line stdlib/llm/llm_test.kuki:83
type HasToolCallsCase struct {
	name     string
	hasCalls bool
	want     bool
}

//line stdlib/llm/llm_test.kuki:88
func TestChatHasToolCalls(t *testing.T) {
//line stdlib/llm/llm_test.kuki:89
	cases := []HasToolCallsCase{HasToolCallsCase{name: "no calls", hasCalls: false, want: false}, HasToolCallsCase{name: "has calls", hasCalls: true, want: true}}
//line stdlib/llm/llm_test.kuki:94
	for _, tc := range cases {
//line stdlib/llm/llm_test.kuki:95
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/llm/llm_test.kuki:96
			comp := chat.Completion{}
//line stdlib/llm/llm_test.kuki:97
			if tc.hasCalls {
//line stdlib/llm/llm_test.kuki:98
				toolCall := chat.ToolCall{}
//line stdlib/llm/llm_test.kuki:99
				toolCall.ID = "call-1"
//line stdlib/llm/llm_test.kuki:100
				msg := chat.ResponseMessage{}
//line stdlib/llm/llm_test.kuki:101
				msg.ToolCalls = []chat.ToolCall{toolCall}
//line stdlib/llm/llm_test.kuki:102
				choice := chat.Choice{}
//line stdlib/llm/llm_test.kuki:103
				choice.Message = msg
//line stdlib/llm/llm_test.kuki:104
				comp.Choices = []chat.Choice{choice}
			}
//line stdlib/llm/llm_test.kuki:106
			test.AssertEqual(t, chat.HasToolCalls(comp), tc.want)
		})
	}
}

//line stdlib/llm/llm_test.kuki:110
func TestResponsesGetText(t *testing.T) {
//line stdlib/llm/llm_test.kuki:111
	t.Run("extracts output_text from message item", func(t *testing.T) {
//line stdlib/llm/llm_test.kuki:112
		textPart := map[string]any{"type": "output_text", "text": "hello world"}
//line stdlib/llm/llm_test.kuki:113
		item := responses.OutputItem{}
//line stdlib/llm/llm_test.kuki:114
		item.Type = "message"
//line stdlib/llm/llm_test.kuki:115
		item.Role = "assistant"
//line stdlib/llm/llm_test.kuki:116
		item.Content = []any{textPart}
//line stdlib/llm/llm_test.kuki:118
		resp := responses.Response{}
//line stdlib/llm/llm_test.kuki:119
		resp.Output = []responses.OutputItem{item}
//line stdlib/llm/llm_test.kuki:121
		test.AssertEqual(t, responses.GetText(resp), "hello world")
	})
//line stdlib/llm/llm_test.kuki:124
	t.Run("returns empty string when no message items", func(t *testing.T) {
//line stdlib/llm/llm_test.kuki:125
		resp := responses.Response{}
//line stdlib/llm/llm_test.kuki:126
		test.AssertEqual(t, responses.GetText(resp), "")
	})
//line stdlib/llm/llm_test.kuki:129
	t.Run("skips non-message output items", func(t *testing.T) {
//line stdlib/llm/llm_test.kuki:130
		call := responses.OutputItem{}
//line stdlib/llm/llm_test.kuki:131
		call.Type = "function_call"
//line stdlib/llm/llm_test.kuki:132
		call.Name = "get_weather"
//line stdlib/llm/llm_test.kuki:134
		resp := responses.Response{}
//line stdlib/llm/llm_test.kuki:135
		resp.Output = []responses.OutputItem{call}
//line stdlib/llm/llm_test.kuki:137
		test.AssertEqual(t, responses.GetText(resp), "")
	})
}

//line stdlib/llm/llm_test.kuki:141
func TestResponsesGetFunctionCalls(t *testing.T) {
//line stdlib/llm/llm_test.kuki:142
	t.Run("returns only function_call items", func(t *testing.T) {
//line stdlib/llm/llm_test.kuki:143
		msgItem := responses.OutputItem{Type: "message", Role: "assistant"}
//line stdlib/llm/llm_test.kuki:144
		callItem := responses.OutputItem{Type: "function_call", Name: "get_weather", CallID: "call-1"}
//line stdlib/llm/llm_test.kuki:146
		resp := responses.Response{}
//line stdlib/llm/llm_test.kuki:147
		resp.Output = []responses.OutputItem{msgItem, callItem}
//line stdlib/llm/llm_test.kuki:149
		calls := responses.GetFunctionCalls(resp)
//line stdlib/llm/llm_test.kuki:150
		test.AssertEqual(t, len(calls), 1)
//line stdlib/llm/llm_test.kuki:151
		test.AssertEqual(t, calls[0].Name, "get_weather")
	})
//line stdlib/llm/llm_test.kuki:154
	t.Run("returns empty list when no function calls", func(t *testing.T) {
//line stdlib/llm/llm_test.kuki:155
		resp := responses.Response{}
//line stdlib/llm/llm_test.kuki:156
		resp.Output = []responses.OutputItem{responses.OutputItem{Type: "message"}}
//line stdlib/llm/llm_test.kuki:158
		test.AssertEqual(t, len(responses.GetFunctionCalls(resp)), 0)
	})
}

//line stdlib/llm/llm_test.kuki:162
func TestResponsesHasFunctionCalls(t *testing.T) {
//line stdlib/llm/llm_test.kuki:163
	t.Run("true when at least one function_call", func(t *testing.T) {
//line stdlib/llm/llm_test.kuki:164
		resp := responses.Response{}
//line stdlib/llm/llm_test.kuki:165
		resp.Output = []responses.OutputItem{responses.OutputItem{Type: "function_call", Name: "f"}}
//line stdlib/llm/llm_test.kuki:166
		test.AssertTrue(t, responses.HasFunctionCalls(resp))
	})
//line stdlib/llm/llm_test.kuki:169
	t.Run("false when no function calls", func(t *testing.T) {
//line stdlib/llm/llm_test.kuki:170
		resp := responses.Response{}
//line stdlib/llm/llm_test.kuki:171
		test.AssertFalse(t, responses.HasFunctionCalls(resp))
	})
}

//line stdlib/llm/llm_test.kuki:175
func TestResponsesFromResponse(t *testing.T) {
//line stdlib/llm/llm_test.kuki:176
	t.Run("sets previous response ID", func(t *testing.T) {
//line stdlib/llm/llm_test.kuki:177
		resp := responses.Response{ID: "resp_abc123"}
//line stdlib/llm/llm_test.kuki:178
		c := responses.FromResponse(responses.New("openai:gpt-4o"), resp)
//line stdlib/llm/llm_test.kuki:179
		_ = c
	})
//line stdlib/llm/llm_test.kuki:182
	t.Run("empty ID is a no-op on previous_response_id", func(t *testing.T) {
//line stdlib/llm/llm_test.kuki:183
		c := responses.FromResponse(responses.New("openai:gpt-4o"), responses.Response{})
//line stdlib/llm/llm_test.kuki:184
		_ = c
	})
}

//line stdlib/llm/llm_test.kuki:188
func TestResponsesExecuteFunctionCalls(t *testing.T) {
//line stdlib/llm/llm_test.kuki:189
	t.Run("calls handler for matching function", func(t *testing.T) {
//line stdlib/llm/llm_test.kuki:190
		call := responses.OutputItem{Type: "function_call", Name: "get_weather", CallID: "call-1", Arguments: "{\"city\":\"Paris\"}"}
//line stdlib/llm/llm_test.kuki:196
		resp := responses.Response{ID: "resp_xyz", Output: []responses.OutputItem{call}}
//line stdlib/llm/llm_test.kuki:198
		handlers := make(map[string]func(string) string)
//line stdlib/llm/llm_test.kuki:199
		handlers["get_weather"] = func(args string) string { return "sunny" }
//line stdlib/llm/llm_test.kuki:200
		_, err := responses.ExecuteFunctionCalls(responses.New("openai:gpt-4o"), resp, handlers)
//line stdlib/llm/llm_test.kuki:201
		test.AssertEqual(t, err, nil)
	})
//line stdlib/llm/llm_test.kuki:204
	t.Run("returns error for unknown function", func(t *testing.T) {
//line stdlib/llm/llm_test.kuki:205
		call := responses.OutputItem{Type: "function_call", Name: "unknown_fn", CallID: "call-1", Arguments: "{}"}
//line stdlib/llm/llm_test.kuki:211
		resp := responses.Response{ID: "resp_xyz", Output: []responses.OutputItem{call}}
//line stdlib/llm/llm_test.kuki:213
		handlers := make(map[string]func(string) string)
//line stdlib/llm/llm_test.kuki:214
		_, err := responses.ExecuteFunctionCalls(responses.New("openai:gpt-4o"), resp, handlers)
//line stdlib/llm/llm_test.kuki:215
		test.AssertTrue(t, (err != nil))
	})
//line stdlib/llm/llm_test.kuki:218
	t.Run("no-op when response has no function calls", func(t *testing.T) {
//line stdlib/llm/llm_test.kuki:219
		resp := responses.Response{ID: "resp_xyz", Output: []responses.OutputItem{responses.OutputItem{Type: "message", Role: "assistant"}}}
//line stdlib/llm/llm_test.kuki:225
		handlers := make(map[string]func(string) string)
//line stdlib/llm/llm_test.kuki:226
		_, err := responses.ExecuteFunctionCalls(responses.New("openai:gpt-4o"), resp, handlers)
//line stdlib/llm/llm_test.kuki:227
		test.AssertEqual(t, err, nil)
	})
}

//line stdlib/llm/llm_test.kuki:231
func TestAnthropicGetText(t *testing.T) {
//line stdlib/llm/llm_test.kuki:232
	t.Run("concatenates text blocks", func(t *testing.T) {
//line stdlib/llm/llm_test.kuki:233
		b1 := anthropic.ContentBlock{Type: "text", Text: "Hello "}
//line stdlib/llm/llm_test.kuki:234
		b2 := anthropic.ContentBlock{Type: "thinking", Thinking: "ignored"}
//line stdlib/llm/llm_test.kuki:235
		b3 := anthropic.ContentBlock{Type: "text", Text: "world"}
//line stdlib/llm/llm_test.kuki:237
		resp := anthropic.Response{}
//line stdlib/llm/llm_test.kuki:238
		resp.Content = []anthropic.ContentBlock{b1, b2, b3}
//line stdlib/llm/llm_test.kuki:240
		test.AssertEqual(t, anthropic.GetText(resp), "Hello world")
	})
//line stdlib/llm/llm_test.kuki:243
	t.Run("returns empty when no text blocks", func(t *testing.T) {
//line stdlib/llm/llm_test.kuki:244
		resp := anthropic.Response{}
//line stdlib/llm/llm_test.kuki:245
		test.AssertEqual(t, anthropic.GetText(resp), "")
	})
}

//line stdlib/llm/llm_test.kuki:249
func TestAnthropicGetThinking(t *testing.T) {
//line stdlib/llm/llm_test.kuki:250
	t.Run("concatenates thinking blocks only", func(t *testing.T) {
//line stdlib/llm/llm_test.kuki:251
		b1 := anthropic.ContentBlock{Type: "thinking", Thinking: "step 1. "}
//line stdlib/llm/llm_test.kuki:252
		b2 := anthropic.ContentBlock{Type: "text", Text: "ignored"}
//line stdlib/llm/llm_test.kuki:253
		b3 := anthropic.ContentBlock{Type: "thinking", Thinking: "step 2."}
//line stdlib/llm/llm_test.kuki:255
		resp := anthropic.Response{}
//line stdlib/llm/llm_test.kuki:256
		resp.Content = []anthropic.ContentBlock{b1, b2, b3}
//line stdlib/llm/llm_test.kuki:258
		test.AssertEqual(t, anthropic.GetThinking(resp), "step 1. step 2.")
	})
}

//line stdlib/llm/llm_test.kuki:262
func TestAnthropicGetToolUses(t *testing.T) {
//line stdlib/llm/llm_test.kuki:263
	t.Run("returns only tool_use blocks", func(t *testing.T) {
//line stdlib/llm/llm_test.kuki:264
		text := anthropic.ContentBlock{Type: "text", Text: "using tool..."}
//line stdlib/llm/llm_test.kuki:265
		tool := anthropic.ContentBlock{Type: "tool_use", ID: "toolu_1", Name: "get_weather"}
//line stdlib/llm/llm_test.kuki:267
		resp := anthropic.Response{}
//line stdlib/llm/llm_test.kuki:268
		resp.Content = []anthropic.ContentBlock{text, tool}
//line stdlib/llm/llm_test.kuki:270
		uses := anthropic.GetToolUses(resp)
//line stdlib/llm/llm_test.kuki:271
		test.AssertEqual(t, len(uses), 1)
//line stdlib/llm/llm_test.kuki:272
		test.AssertEqual(t, uses[0].Name, "get_weather")
	})
}

//line stdlib/llm/llm_test.kuki:276
func TestAnthropicHasToolUses(t *testing.T) {
//line stdlib/llm/llm_test.kuki:277
	t.Run("true when stop_reason is tool_use", func(t *testing.T) {
//line stdlib/llm/llm_test.kuki:278
		resp := anthropic.Response{StopReason: "tool_use"}
//line stdlib/llm/llm_test.kuki:279
		test.AssertTrue(t, anthropic.HasToolUses(resp))
	})
//line stdlib/llm/llm_test.kuki:282
	t.Run("false when stop_reason is end_turn", func(t *testing.T) {
//line stdlib/llm/llm_test.kuki:283
		resp := anthropic.Response{StopReason: "end_turn"}
//line stdlib/llm/llm_test.kuki:284
		test.AssertFalse(t, anthropic.HasToolUses(resp))
	})
}

//line stdlib/llm/llm_test.kuki:288
func TestSchemaHelpers(t *testing.T) {
//line stdlib/llm/llm_test.kuki:289
	t.Run("Prop builds a SchemaProperty", func(t *testing.T) {
//line stdlib/llm/llm_test.kuki:290
		p := llm.Prop("path", "string", "File path")
//line stdlib/llm/llm_test.kuki:291
		test.AssertEqual(t, p.Name, "path")
//line stdlib/llm/llm_test.kuki:292
		test.AssertEqual(t, p.Type, "string")
//line stdlib/llm/llm_test.kuki:293
		test.AssertEqual(t, p.Description, "File path")
	})
//line stdlib/llm/llm_test.kuki:296
	t.Run("Schema produces an object with properties", func(t *testing.T) {
//line stdlib/llm/llm_test.kuki:297
		s := llm.Schema([]llm.SchemaProperty{llm.Prop("path", "string", "File path"), llm.Prop("limit", "integer", "Max items")})
//line stdlib/llm/llm_test.kuki:301
		test.AssertEqual(t, s["type"], "object")
//line stdlib/llm/llm_test.kuki:303
		props, ok := s["properties"].(map[string]any)
//line stdlib/llm/llm_test.kuki:304
		test.AssertTrue(t, ok)
//line stdlib/llm/llm_test.kuki:305
		pathProp, ok2 := props["path"].(map[string]any)
//line stdlib/llm/llm_test.kuki:306
		test.AssertTrue(t, ok2)
//line stdlib/llm/llm_test.kuki:307
		test.AssertEqual(t, pathProp["type"], "string")
//line stdlib/llm/llm_test.kuki:308
		test.AssertEqual(t, pathProp["description"], "File path")
	})
//line stdlib/llm/llm_test.kuki:311
	t.Run("Required adds a required list", func(t *testing.T) {
//line stdlib/llm/llm_test.kuki:312
		s := llm.Required(llm.Schema([]llm.SchemaProperty{llm.Prop("path", "string", "File path")}), []string{"path"})
//line stdlib/llm/llm_test.kuki:317
		required, ok := s["required"].([]string)
//line stdlib/llm/llm_test.kuki:318
		test.AssertTrue(t, ok)
//line stdlib/llm/llm_test.kuki:319
		test.AssertEqual(t, len(required), 1)
//line stdlib/llm/llm_test.kuki:320
		test.AssertEqual(t, required[0], "path")
	})
}

//line stdlib/llm/llm_test.kuki:324
func TestChatFromCompletion(t *testing.T) {
//line stdlib/llm/llm_test.kuki:325
	t.Run("no choices returns unchanged client", func(t *testing.T) {
//line stdlib/llm/llm_test.kuki:326
		c := chat.FromCompletion(chat.New("openai:gpt-4o-mini"), chat.Completion{})
//line stdlib/llm/llm_test.kuki:327
		_ = c
	})
//line stdlib/llm/llm_test.kuki:330
	t.Run("appends assistant message from completion", func(t *testing.T) {
//line stdlib/llm/llm_test.kuki:331
		msg := chat.ResponseMessage{Role: "assistant", Content: "Paris"}
//line stdlib/llm/llm_test.kuki:332
		comp := chat.Completion{Choices: []chat.Choice{chat.Choice{Message: msg}}}
//line stdlib/llm/llm_test.kuki:333
		c := chat.FromCompletion(chat.User(chat.New("openai:gpt-4o-mini"), "Capital of France?"), comp)
//line stdlib/llm/llm_test.kuki:336
		_ = c
	})
//line stdlib/llm/llm_test.kuki:339
	t.Run("preserves tool calls in assistant message", func(t *testing.T) {
//line stdlib/llm/llm_test.kuki:340
		toolCall := chat.ToolCall{ID: "call-1", Type: "function"}
//line stdlib/llm/llm_test.kuki:341
		toolCall.Function = chat.ToolCallFunction{Name: "get_capital", Arguments: "{}"}
//line stdlib/llm/llm_test.kuki:342
		msg := chat.ResponseMessage{Role: "assistant", ToolCalls: []chat.ToolCall{toolCall}}
//line stdlib/llm/llm_test.kuki:343
		comp := chat.Completion{Choices: []chat.Choice{chat.Choice{Message: msg}}}
//line stdlib/llm/llm_test.kuki:344
		c := chat.FromCompletion(chat.New("openai:gpt-4o-mini"), comp)
//line stdlib/llm/llm_test.kuki:345
		_ = c
	})
}

//line stdlib/llm/llm_test.kuki:349
func TestChatExecuteToolCalls(t *testing.T) {
//line stdlib/llm/llm_test.kuki:350
	t.Run("calls handler for matching tool", func(t *testing.T) {
//line stdlib/llm/llm_test.kuki:351
		toolCall := chat.ToolCall{ID: "call-1", Type: "function"}
//line stdlib/llm/llm_test.kuki:352
		toolCall.Function = chat.ToolCallFunction{Name: "get_weather", Arguments: "{}"}
//line stdlib/llm/llm_test.kuki:353
		msg := chat.ResponseMessage{Role: "assistant", ToolCalls: []chat.ToolCall{toolCall}}
//line stdlib/llm/llm_test.kuki:354
		comp := chat.Completion{Choices: []chat.Choice{chat.Choice{Message: msg}}}
//line stdlib/llm/llm_test.kuki:356
		handlers := make(map[string]func(string) string)
//line stdlib/llm/llm_test.kuki:357
		handlers["get_weather"] = func(args string) string { return "sunny" }
//line stdlib/llm/llm_test.kuki:358
		_, err := chat.ExecuteToolCalls(chat.New("openai:gpt-4o-mini"), comp, handlers)
//line stdlib/llm/llm_test.kuki:359
		test.AssertEqual(t, err, nil)
	})
//line stdlib/llm/llm_test.kuki:362
	t.Run("returns error for unknown tool", func(t *testing.T) {
//line stdlib/llm/llm_test.kuki:363
		toolCall := chat.ToolCall{ID: "call-1", Type: "function"}
//line stdlib/llm/llm_test.kuki:364
		toolCall.Function = chat.ToolCallFunction{Name: "unknown_tool", Arguments: "{}"}
//line stdlib/llm/llm_test.kuki:365
		msg := chat.ResponseMessage{Role: "assistant", ToolCalls: []chat.ToolCall{toolCall}}
//line stdlib/llm/llm_test.kuki:366
		comp := chat.Completion{Choices: []chat.Choice{chat.Choice{Message: msg}}}
//line stdlib/llm/llm_test.kuki:368
		handlers := make(map[string]func(string) string)
//line stdlib/llm/llm_test.kuki:369
		_, err := chat.ExecuteToolCalls(chat.New("openai:gpt-4o-mini"), comp, handlers)
//line stdlib/llm/llm_test.kuki:370
		test.AssertTrue(t, (err != nil))
	})
//line stdlib/llm/llm_test.kuki:373
	t.Run("no-op when completion has no choices", func(t *testing.T) {
//line stdlib/llm/llm_test.kuki:374
		handlers := make(map[string]func(string) string)
//line stdlib/llm/llm_test.kuki:375
		_, err := chat.ExecuteToolCalls(chat.New("openai:gpt-4o-mini"), chat.Completion{}, handlers)
//line stdlib/llm/llm_test.kuki:376
		test.AssertEqual(t, err, nil)
	})
}

//line stdlib/llm/llm_test.kuki:380
func TestAnthropicFromResponse(t *testing.T) {
//line stdlib/llm/llm_test.kuki:381
	t.Run("appends assistant message from response", func(t *testing.T) {
//line stdlib/llm/llm_test.kuki:382
		b1 := anthropic.ContentBlock{Type: "text", Text: "Hello"}
//line stdlib/llm/llm_test.kuki:383
		resp := anthropic.Response{Content: []anthropic.ContentBlock{b1}}
//line stdlib/llm/llm_test.kuki:384
		c := anthropic.FromResponse(anthropic.New("claude-opus-4-6"), resp)
//line stdlib/llm/llm_test.kuki:385
		_ = c
	})
//line stdlib/llm/llm_test.kuki:388
	t.Run("empty response still appends an assistant message", func(t *testing.T) {
//line stdlib/llm/llm_test.kuki:389
		c := anthropic.FromResponse(anthropic.New("claude-opus-4-6"), anthropic.Response{})
//line stdlib/llm/llm_test.kuki:390
		_ = c
	})
}

//line stdlib/llm/llm_test.kuki:394
func TestAnthropicExecuteToolUses(t *testing.T) {
//line stdlib/llm/llm_test.kuki:395
	t.Run("calls handler for matching tool use", func(t *testing.T) {
//line stdlib/llm/llm_test.kuki:396
		toolUse := anthropic.ContentBlock{Type: "tool_use", ID: "toolu_1", Name: "get_weather", Input: "{\"city\":\"Paris\"}"}
//line stdlib/llm/llm_test.kuki:402
		resp := anthropic.Response{StopReason: "tool_use", Content: []anthropic.ContentBlock{toolUse}}
//line stdlib/llm/llm_test.kuki:404
		handlers := make(map[string]func(string) string)
//line stdlib/llm/llm_test.kuki:405
		handlers["get_weather"] = func(args string) string { return "sunny" }
//line stdlib/llm/llm_test.kuki:406
		_, err := anthropic.ExecuteToolUses(anthropic.New("claude-opus-4-6"), resp, handlers)
//line stdlib/llm/llm_test.kuki:407
		test.AssertEqual(t, err, nil)
	})
//line stdlib/llm/llm_test.kuki:410
	t.Run("returns error for unknown tool", func(t *testing.T) {
//line stdlib/llm/llm_test.kuki:411
		toolUse := anthropic.ContentBlock{Type: "tool_use", ID: "toolu_1", Name: "unknown_tool", Input: "{}"}
//line stdlib/llm/llm_test.kuki:412
		resp := anthropic.Response{StopReason: "tool_use", Content: []anthropic.ContentBlock{toolUse}}
//line stdlib/llm/llm_test.kuki:414
		handlers := make(map[string]func(string) string)
//line stdlib/llm/llm_test.kuki:415
		_, err := anthropic.ExecuteToolUses(anthropic.New("claude-opus-4-6"), resp, handlers)
//line stdlib/llm/llm_test.kuki:416
		test.AssertTrue(t, (err != nil))
	})
//line stdlib/llm/llm_test.kuki:419
	t.Run("no-op when response has no tool uses", func(t *testing.T) {
//line stdlib/llm/llm_test.kuki:420
		resp := anthropic.Response{Content: []anthropic.ContentBlock{anthropic.ContentBlock{Type: "text", Text: "no tools here"}}}
//line stdlib/llm/llm_test.kuki:425
		handlers := make(map[string]func(string) string)
//line stdlib/llm/llm_test.kuki:426
		_, err := anthropic.ExecuteToolUses(anthropic.New("claude-opus-4-6"), resp, handlers)
//line stdlib/llm/llm_test.kuki:427
		test.AssertEqual(t, err, nil)
	})
}
