// Generated by Kukicha (requires Go 1.26+)

package color_test

import (
	"fmt"
	"github.com/kukichalang/kukicha/stdlib/color"
	"github.com/kukichalang/kukicha/stdlib/term"
	"github.com/kukichalang/kukicha/stdlib/test"
	"os"
	"testing"
)

//line stdlib/color/color_test.kuki:13
type BoldCase struct {
	name  string
	input string
	want  string
}

//line stdlib/color/color_test.kuki:18
func TestBoldEnabled(t *testing.T) {
//line stdlib/color/color_test.kuki:19
	color.SetEnabled(true)
//line stdlib/color/color_test.kuki:20
	cases := []BoldCase{BoldCase{name: "simple", input: "hello", want: "\x1b[1mhello\x1b[0m"}, BoldCase{name: "empty", input: "", want: "\x1b[1m\x1b[0m"}}
//line stdlib/color/color_test.kuki:24
	for _, tc := range cases {
//line stdlib/color/color_test.kuki:25
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/color/color_test.kuki:26
			test.AssertEqual(t, color.Bold(tc.input), tc.want)
		})
	}
}

//line stdlib/color/color_test.kuki:31
type StyleCase struct {
	name string
	fn   func(string) string
	code string
}

//line stdlib/color/color_test.kuki:36
func TestStylesEnabled(t *testing.T) {
//line stdlib/color/color_test.kuki:37
	color.SetEnabled(true)
//line stdlib/color/color_test.kuki:38
	cases := []StyleCase{StyleCase{name: "Bold", fn: color.Bold, code: "1"}, StyleCase{name: "Dim", fn: color.Dim, code: "2"}, StyleCase{name: "Italic", fn: color.Italic, code: "3"}, StyleCase{name: "Underline", fn: color.Underline, code: "4"}}
//line stdlib/color/color_test.kuki:44
	for _, tc := range cases {
//line stdlib/color/color_test.kuki:45
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/color/color_test.kuki:46
			got := tc.fn("x")
//line stdlib/color/color_test.kuki:47
			want := fmt.Sprintf("\x1b[%vmx\x1b[0m", tc.code)
//line stdlib/color/color_test.kuki:48
			test.AssertEqual(t, got, want)
		})
	}
}

//line stdlib/color/color_test.kuki:53
type ColorCase struct {
	name string
	fn   func(string) string
	code string
}

//line stdlib/color/color_test.kuki:58
func TestColorsEnabled(t *testing.T) {
//line stdlib/color/color_test.kuki:59
	color.SetEnabled(true)
//line stdlib/color/color_test.kuki:60
	cases := []ColorCase{ColorCase{name: "Red", fn: color.Red, code: "31"}, ColorCase{name: "Green", fn: color.Green, code: "32"}, ColorCase{name: "Yellow", fn: color.Yellow, code: "33"}, ColorCase{name: "Blue", fn: color.Blue, code: "34"}, ColorCase{name: "Magenta", fn: color.Magenta, code: "35"}, ColorCase{name: "Cyan", fn: color.Cyan, code: "36"}, ColorCase{name: "Gray", fn: color.Gray, code: "90"}, ColorCase{name: "BrightRed", fn: color.BrightRed, code: "91"}, ColorCase{name: "BrightGreen", fn: color.BrightGreen, code: "92"}, ColorCase{name: "BrightYellow", fn: color.BrightYellow, code: "93"}, ColorCase{name: "BrightBlue", fn: color.BrightBlue, code: "94"}, ColorCase{name: "BrightMagenta", fn: color.BrightMagenta, code: "95"}, ColorCase{name: "BrightCyan", fn: color.BrightCyan, code: "96"}, ColorCase{name: "BrightWhite", fn: color.BrightWhite, code: "97"}}
//line stdlib/color/color_test.kuki:76
	for _, tc := range cases {
//line stdlib/color/color_test.kuki:77
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/color/color_test.kuki:78
			got := tc.fn("x")
//line stdlib/color/color_test.kuki:79
			want := fmt.Sprintf("\x1b[%vmx\x1b[0m", tc.code)
//line stdlib/color/color_test.kuki:80
			test.AssertEqual(t, got, want)
		})
	}
}

//line stdlib/color/color_test.kuki:85
type DisabledCase struct {
	name string
	fn   func(string) string
}

//line stdlib/color/color_test.kuki:89
func TestDisabled(t *testing.T) {
//line stdlib/color/color_test.kuki:90
	color.SetEnabled(false)
//line stdlib/color/color_test.kuki:91
	cases := []DisabledCase{DisabledCase{name: "Bold", fn: color.Bold}, DisabledCase{name: "Dim", fn: color.Dim}, DisabledCase{name: "Italic", fn: color.Italic}, DisabledCase{name: "Underline", fn: color.Underline}, DisabledCase{name: "Red", fn: color.Red}, DisabledCase{name: "Green", fn: color.Green}, DisabledCase{name: "Yellow", fn: color.Yellow}, DisabledCase{name: "Blue", fn: color.Blue}, DisabledCase{name: "Magenta", fn: color.Magenta}, DisabledCase{name: "Cyan", fn: color.Cyan}, DisabledCase{name: "Gray", fn: color.Gray}, DisabledCase{name: "BrightRed", fn: color.BrightRed}, DisabledCase{name: "BrightGreen", fn: color.BrightGreen}, DisabledCase{name: "BrightYellow", fn: color.BrightYellow}, DisabledCase{name: "BrightBlue", fn: color.BrightBlue}, DisabledCase{name: "BrightMagenta", fn: color.BrightMagenta}, DisabledCase{name: "BrightCyan", fn: color.BrightCyan}, DisabledCase{name: "BrightWhite", fn: color.BrightWhite}}
//line stdlib/color/color_test.kuki:111
	for _, tc := range cases {
//line stdlib/color/color_test.kuki:112
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/color/color_test.kuki:113
			test.AssertEqual(t, tc.fn("hello"), "hello")
		})
	}
}

//line stdlib/color/color_test.kuki:118
type SemanticCase struct {
	name string
	fn   func(string) string
	want string
}

//line stdlib/color/color_test.kuki:123
func TestSemanticHelpers(t *testing.T) {
//line stdlib/color/color_test.kuki:124
	color.SetEnabled(true)
//line stdlib/color/color_test.kuki:125
	cases := []SemanticCase{SemanticCase{name: "Error", fn: color.Error, want: "\x1b[1;91mtest\x1b[0m"}}
//line stdlib/color/color_test.kuki:128
	for _, tc := range cases {
//line stdlib/color/color_test.kuki:129
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/color/color_test.kuki:130
			test.AssertEqual(t, tc.fn("test"), tc.want)
		})
	}
}

//line stdlib/color/color_test.kuki:135
func TestSemanticDisabled(t *testing.T) {
//line stdlib/color/color_test.kuki:136
	color.SetEnabled(false)
//line stdlib/color/color_test.kuki:137
	cases := []DisabledCase{DisabledCase{name: "Error", fn: color.Error}}
//line stdlib/color/color_test.kuki:140
	for _, tc := range cases {
//line stdlib/color/color_test.kuki:141
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/color/color_test.kuki:142
			test.AssertEqual(t, tc.fn("hello"), "hello")
		})
	}
}

//line stdlib/color/color_test.kuki:147
func TestNesting(t *testing.T) {
//line stdlib/color/color_test.kuki:148
	color.SetEnabled(true)
//line stdlib/color/color_test.kuki:151
	t.Run("inner reset re-opens outer style", func(t *testing.T) {
//line stdlib/color/color_test.kuki:152
		inner := color.Bold("b")
//line stdlib/color/color_test.kuki:153
		got := color.Red(inner)
//line stdlib/color/color_test.kuki:154
		want := "\x1b[31m\x1b[1mb\x1b[0m\x1b[31m\x1b[0m"
//line stdlib/color/color_test.kuki:155
		test.AssertEqual(t, got, want)
	})
//line stdlib/color/color_test.kuki:159
	t.Run("no inner reset is unchanged", func(t *testing.T) {
//line stdlib/color/color_test.kuki:160
		got := color.Red("plain")
//line stdlib/color/color_test.kuki:161
		want := "\x1b[31mplain\x1b[0m"
//line stdlib/color/color_test.kuki:162
		test.AssertEqual(t, got, want)
	})
}

//line stdlib/color/color_test.kuki:167
func TestSetEnabled(t *testing.T) {
//line stdlib/color/color_test.kuki:168
	color.SetEnabled(true)
//line stdlib/color/color_test.kuki:169
	test.AssertTrue(t, color.Enabled())
//line stdlib/color/color_test.kuki:172
	test.AssertTrue(t, term.ColorEnabled())
//line stdlib/color/color_test.kuki:174
	color.SetEnabled(false)
//line stdlib/color/color_test.kuki:175
	test.AssertFalse(t, color.Enabled())
//line stdlib/color/color_test.kuki:176
	test.AssertFalse(t, term.ColorEnabled())
//line stdlib/color/color_test.kuki:178
	color.SetEnabled(true)
//line stdlib/color/color_test.kuki:179
	test.AssertTrue(t, color.Enabled())
}

//line stdlib/color/color_test.kuki:183
func TestStylerHonorsOverride(t *testing.T) {
//line stdlib/color/color_test.kuki:184
	term.SetColorEnabled(true)
//line stdlib/color/color_test.kuki:185
	defer term.ResetColorOverride()
//line stdlib/color/color_test.kuki:187
	s := color.NewStyler(os.Stderr)
//line stdlib/color/color_test.kuki:188
	test.AssertEqual(t, s.Red("x"), "\x1b[31mx\x1b[0m")
//line stdlib/color/color_test.kuki:190
	term.SetColorEnabled(false)
//line stdlib/color/color_test.kuki:191
	test.AssertEqual(t, s.Red("x"), "x")
}

//line stdlib/color/color_test.kuki:195
func TestStylerNonTTY(t *testing.T) {
//line stdlib/color/color_test.kuki:196
	term.ResetColorOverride()
//line stdlib/color/color_test.kuki:197
	defer term.ResetColorOverride()
//line stdlib/color/color_test.kuki:198
	os.Unsetenv("FORCE_COLOR")
//line stdlib/color/color_test.kuki:199
	os.Unsetenv("NO_COLOR")
//line stdlib/color/color_test.kuki:201
	f, err_1 := os.Open("color.kuki")
//line stdlib/color/color_test.kuki:201
	if err_1 != nil {
//line stdlib/color/color_test.kuki:201
		panic("open failed")
	}
//line stdlib/color/color_test.kuki:202
	defer f.Close()
//line stdlib/color/color_test.kuki:203
	s := color.NewStyler(f)
//line stdlib/color/color_test.kuki:205
	test.AssertEqual(t, s.Red("x"), "x")
}
