// Generated by Kukicha (requires Go 1.26+)

package datetime

import "time"

//line stdlib/datetime/datetime.kuki:16
func Format(t time.Time, format string) string {
//line stdlib/datetime/datetime.kuki:17
	layout := getLayout(format)
//line stdlib/datetime/datetime.kuki:18
	return t.Format(layout)
}

//line stdlib/datetime/datetime.kuki:23
func Parse(value string, format string) (time.Time, error) {
//line stdlib/datetime/datetime.kuki:24
	layout := getLayout(format)
//line stdlib/datetime/datetime.kuki:25
	return time.Parse(layout, value)
}

//line stdlib/datetime/datetime.kuki:29
func ParseInLocation(value string, format string, location string) (time.Time, error) {
//line stdlib/datetime/datetime.kuki:30
	layout := getLayout(format)
//line stdlib/datetime/datetime.kuki:31
	loc, err_1 := time.LoadLocation(location)
//line stdlib/datetime/datetime.kuki:31
	if err_1 != nil {
		var _zero0 time.Time
//line stdlib/datetime/datetime.kuki:31
		return _zero0, err_1
	}
//line stdlib/datetime/datetime.kuki:32
	return time.ParseInLocation(layout, value, loc)
}

//line stdlib/datetime/datetime.kuki:36
func Now() time.Time {
//line stdlib/datetime/datetime.kuki:37
	return time.Now()
}

//line stdlib/datetime/datetime.kuki:41
func Today() time.Time {
//line stdlib/datetime/datetime.kuki:42
	now := time.Now()
//line stdlib/datetime/datetime.kuki:43
	return time.Date(now.Year(), now.Month(), now.Day(), 0, 0, 0, 0, now.Location())
}

//line stdlib/datetime/datetime.kuki:47
func Tomorrow() time.Time {
//line stdlib/datetime/datetime.kuki:48
	return Today().AddDate(0, 0, 1)
}

//line stdlib/datetime/datetime.kuki:52
func Yesterday() time.Time {
//line stdlib/datetime/datetime.kuki:53
	return Today().AddDate(0, 0, -1)
}

//line stdlib/datetime/datetime.kuki:60
func Nanoseconds(n int64) time.Duration {
//line stdlib/datetime/datetime.kuki:61
	return time.Duration((n * 1))
}

//line stdlib/datetime/datetime.kuki:65
func Microseconds(n int64) time.Duration {
//line stdlib/datetime/datetime.kuki:66
	return time.Duration((n * 1000))
}

//line stdlib/datetime/datetime.kuki:70
func Milliseconds(n int64) time.Duration {
//line stdlib/datetime/datetime.kuki:71
	return time.Duration((n * 1000000))
}

//line stdlib/datetime/datetime.kuki:75
func Seconds(n int64) time.Duration {
//line stdlib/datetime/datetime.kuki:76
	return time.Duration((n * 1000000000))
}

//line stdlib/datetime/datetime.kuki:80
func Minutes(n int64) time.Duration {
//line stdlib/datetime/datetime.kuki:81
	return time.Duration((n * 60000000000))
}

//line stdlib/datetime/datetime.kuki:85
func Hours(n int64) time.Duration {
//line stdlib/datetime/datetime.kuki:86
	return time.Duration((n * 3600000000000))
}

//line stdlib/datetime/datetime.kuki:90
func Days(n int64) time.Duration {
//line stdlib/datetime/datetime.kuki:91
	return time.Duration((n * 86400000000000))
}

//line stdlib/datetime/datetime.kuki:95
func Weeks(n int64) time.Duration {
//line stdlib/datetime/datetime.kuki:96
	return time.Duration((n * 604800000000000))
}

//line stdlib/datetime/datetime.kuki:104
func Intervals(elapsed time.Duration, interval time.Duration) int64 {
//line stdlib/datetime/datetime.kuki:105
	if interval == 0 {
//line stdlib/datetime/datetime.kuki:106
		return 0
	}
//line stdlib/datetime/datetime.kuki:107
	return int64((elapsed / interval))
}

//line stdlib/datetime/datetime.kuki:113
func AddDays(t time.Time, days int) time.Time {
//line stdlib/datetime/datetime.kuki:114
	return t.AddDate(0, 0, days)
}

//line stdlib/datetime/datetime.kuki:118
func AddWeeks(t time.Time, weeks int) time.Time {
//line stdlib/datetime/datetime.kuki:119
	return t.AddDate(0, 0, (weeks * 7))
}

//line stdlib/datetime/datetime.kuki:123
func AddMonths(t time.Time, months int) time.Time {
//line stdlib/datetime/datetime.kuki:124
	return t.AddDate(0, months, 0)
}

//line stdlib/datetime/datetime.kuki:128
func AddYears(t time.Time, years int) time.Time {
//line stdlib/datetime/datetime.kuki:129
	return t.AddDate(years, 0, 0)
}

//line stdlib/datetime/datetime.kuki:133
func SubDays(t time.Time, days int) time.Time {
//line stdlib/datetime/datetime.kuki:134
	return t.AddDate(0, 0, -days)
}

//line stdlib/datetime/datetime.kuki:138
func SubWeeks(t time.Time, weeks int) time.Time {
//line stdlib/datetime/datetime.kuki:139
	return t.AddDate(0, 0, (-weeks * 7))
}

//line stdlib/datetime/datetime.kuki:143
func SubMonths(t time.Time, months int) time.Time {
//line stdlib/datetime/datetime.kuki:144
	return t.AddDate(0, -months, 0)
}

//line stdlib/datetime/datetime.kuki:148
func SubYears(t time.Time, years int) time.Time {
//line stdlib/datetime/datetime.kuki:149
	return t.AddDate(-years, 0, 0)
}

//line stdlib/datetime/datetime.kuki:155
func IsBetween(t time.Time, start time.Time, end time.Time) bool {
//line stdlib/datetime/datetime.kuki:156
	atOrAfterStart := t.Equal(start)
//line stdlib/datetime/datetime.kuki:157
	afterStart := t.After(start)
//line stdlib/datetime/datetime.kuki:158
	atOrBeforeEnd := t.Equal(end)
//line stdlib/datetime/datetime.kuki:159
	beforeEnd := t.Before(end)
//line stdlib/datetime/datetime.kuki:160
	return ((atOrAfterStart || afterStart) && (atOrBeforeEnd || beforeEnd))
}

//line stdlib/datetime/datetime.kuki:164
func IsSameDay(t1 time.Time, t2 time.Time) bool {
//line stdlib/datetime/datetime.kuki:165
	y1 := t1.Year()
//line stdlib/datetime/datetime.kuki:166
	m1 := t1.Month()
//line stdlib/datetime/datetime.kuki:167
	d1 := t1.Day()
//line stdlib/datetime/datetime.kuki:168
	y2 := t2.Year()
//line stdlib/datetime/datetime.kuki:169
	m2 := t2.Month()
//line stdlib/datetime/datetime.kuki:170
	d2 := t2.Day()
//line stdlib/datetime/datetime.kuki:171
	return (((y1 == y2) && (m1 == m2)) && (d1 == d2))
}

//line stdlib/datetime/datetime.kuki:175
func IsToday(t time.Time) bool {
//line stdlib/datetime/datetime.kuki:176
	return IsSameDay(t, time.Now())
}

//line stdlib/datetime/datetime.kuki:180
func IsYesterday(t time.Time) bool {
//line stdlib/datetime/datetime.kuki:181
	return IsSameDay(t, Yesterday())
}

//line stdlib/datetime/datetime.kuki:185
func IsTomorrow(t time.Time) bool {
//line stdlib/datetime/datetime.kuki:186
	return IsSameDay(t, Tomorrow())
}

//line stdlib/datetime/datetime.kuki:190
func IsPast(t time.Time) bool {
//line stdlib/datetime/datetime.kuki:191
	return t.Before(time.Now())
}

//line stdlib/datetime/datetime.kuki:195
func IsFuture(t time.Time) bool {
//line stdlib/datetime/datetime.kuki:196
	return t.After(time.Now())
}

//line stdlib/datetime/datetime.kuki:203
func Month(t time.Time) int {
//line stdlib/datetime/datetime.kuki:204
	return int(t.Month())
}

//line stdlib/datetime/datetime.kuki:209
func Weekday(t time.Time) int {
//line stdlib/datetime/datetime.kuki:210
	return int(t.Weekday())
}

//line stdlib/datetime/datetime.kuki:214
func WeekdayName(t time.Time) string {
//line stdlib/datetime/datetime.kuki:215
	return t.Weekday().String()
}

//line stdlib/datetime/datetime.kuki:221
func FromUnix(sec int64) time.Time {
//line stdlib/datetime/datetime.kuki:222
	return time.Unix(sec, 0)
}

//line stdlib/datetime/datetime.kuki:226
func FromUnixMilli(msec int64) time.Time {
//line stdlib/datetime/datetime.kuki:227
	return time.UnixMilli(msec)
}

//line stdlib/datetime/datetime.kuki:233
func Sleep(d time.Duration) {
//line stdlib/datetime/datetime.kuki:234
	time.Sleep(d)
}

//line stdlib/datetime/datetime.kuki:238
func SleepSeconds(n int64) {
//line stdlib/datetime/datetime.kuki:239
	time.Sleep((time.Duration(n) * time.Second))
}

//line stdlib/datetime/datetime.kuki:243
func SleepMilliseconds(n int64) {
//line stdlib/datetime/datetime.kuki:244
	time.Sleep((time.Duration(n) * time.Millisecond))
}

//line stdlib/datetime/datetime.kuki:250
func InLocation(t time.Time, location string) (time.Time, error) {
//line stdlib/datetime/datetime.kuki:251
	loc, err_2 := time.LoadLocation(location)
//line stdlib/datetime/datetime.kuki:251
	if err_2 != nil {
		var _zero0 time.Time
//line stdlib/datetime/datetime.kuki:251
		return _zero0, err_2
	}
//line stdlib/datetime/datetime.kuki:252
	return t.In(loc), nil
}

//line stdlib/datetime/datetime.kuki:255
func getLayout(format string) string {
//line stdlib/datetime/datetime.kuki:256
	if (format == "iso8601") || (format == "ISO8601") {
//line stdlib/datetime/datetime.kuki:257
		return "2006-01-02T15:04:05Z07:00"
	}
//line stdlib/datetime/datetime.kuki:258
	if (format == "rfc3339") || (format == "RFC3339") {
//line stdlib/datetime/datetime.kuki:259
		return time.RFC3339
	}
//line stdlib/datetime/datetime.kuki:260
	if (format == "rfc3339nano") || (format == "RFC3339Nano") {
//line stdlib/datetime/datetime.kuki:261
		return time.RFC3339Nano
	}
//line stdlib/datetime/datetime.kuki:262
	if format == "date" {
//line stdlib/datetime/datetime.kuki:263
		return "2006-01-02"
	}
//line stdlib/datetime/datetime.kuki:264
	if format == "time" {
//line stdlib/datetime/datetime.kuki:265
		return "15:04:05"
	}
//line stdlib/datetime/datetime.kuki:266
	if format == "datetime" {
//line stdlib/datetime/datetime.kuki:267
		return "2006-01-02 15:04:05"
	}
//line stdlib/datetime/datetime.kuki:268
	if format == "dateTimeT" {
//line stdlib/datetime/datetime.kuki:269
		return "2006-01-02T15:04:05"
	}
//line stdlib/datetime/datetime.kuki:270
	if format == "kitchen" {
//line stdlib/datetime/datetime.kuki:271
		return time.Kitchen
	}
//line stdlib/datetime/datetime.kuki:272
	if format == "stamp" {
//line stdlib/datetime/datetime.kuki:273
		return time.Stamp
	}
//line stdlib/datetime/datetime.kuki:274
	if format == "rfc822" {
//line stdlib/datetime/datetime.kuki:275
		return time.RFC822
	}
//line stdlib/datetime/datetime.kuki:276
	if format == "rfc1123" {
//line stdlib/datetime/datetime.kuki:277
		return time.RFC1123
	}
//line stdlib/datetime/datetime.kuki:278
	if format == "ansic" {
//line stdlib/datetime/datetime.kuki:279
		return time.ANSIC
	}
//line stdlib/datetime/datetime.kuki:280
	if format == "unixdate" {
//line stdlib/datetime/datetime.kuki:281
		return time.UnixDate
	}
//line stdlib/datetime/datetime.kuki:283
	return format
}
