// Generated by Kukicha (requires Go 1.26+)

package responses

import (
	"bufio"
	"context"
	"errors"
	"fmt"
	ctxpkg "github.com/kukichalang/kukicha/stdlib/ctx"
	"github.com/kukichalang/kukicha/stdlib/env"
	"github.com/kukichalang/kukicha/stdlib/fetch"
	"github.com/kukichalang/kukicha/stdlib/json"
	kukistring "github.com/kukichalang/kukicha/stdlib/string"
	"strings"
)

//line stdlib/llm/responses/responses.kuki:33
type ToolFunction struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Parameters  any    `json:"parameters"`
}

//line stdlib/llm/responses/responses.kuki:39
type Tool struct {
	Type     string       `json:"type"`
	Function ToolFunction `json:"function"`
}

//line stdlib/llm/responses/responses.kuki:44
type InputTextContent struct {
	Type string `json:"type"`
	Text string `json:"text"`
}

//line stdlib/llm/responses/responses.kuki:49
type OutputTextContent struct {
	Type        string `json:"type"`
	Text        string `json:"text"`
	Annotations []any  `json:"annotations,omitempty"`
}

//line stdlib/llm/responses/responses.kuki:56
type InputItem struct {
	Type      string `json:"type"`
	ID        string `json:"id,omitempty"`
	Role      string `json:"role,omitempty"`
	Content   any    `json:"content,omitempty"`
	Status    string `json:"status,omitempty"`
	CallID    string `json:"call_id,omitempty"`
	Name      string `json:"name,omitempty"`
	Arguments string `json:"arguments,omitempty"`
	Output    string `json:"output,omitempty"`
}

//line stdlib/llm/responses/responses.kuki:69
type OutputItem struct {
	Type      string `json:"type"`
	ID        string `json:"id,omitempty"`
	Role      string `json:"role,omitempty"`
	Content   []any  `json:"content,omitempty"`
	Status    string `json:"status,omitempty"`
	CallID    string `json:"call_id,omitempty"`
	Name      string `json:"name,omitempty"`
	Arguments string `json:"arguments,omitempty"`
	Summary   []any  `json:"summary,omitempty"`
}

//line stdlib/llm/responses/responses.kuki:81
type Usage struct {
	InputTokens  int `json:"input_tokens"`
	OutputTokens int `json:"output_tokens"`
	TotalTokens  int `json:"total_tokens"`
}

//line stdlib/llm/responses/responses.kuki:87
type ResponseError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

//line stdlib/llm/responses/responses.kuki:92
type Response struct {
	ID                 string            `json:"id"`
	Object             string            `json:"object"`
	CreatedAt          int               `json:"created_at"`
	CompletedAt        int               `json:"completed_at,omitempty"`
	Status             string            `json:"status"`
	Model              string            `json:"model"`
	Output             []OutputItem      `json:"output"`
	Error              ResponseError     `json:"error,omitzero"`
	PreviousResponseID string            `json:"previous_response_id,omitempty"`
	Instructions       string            `json:"instructions,omitempty"`
	Temperature        float64           `json:"temperature,omitempty"`
	TopP               float64           `json:"top_p,omitempty"`
	MaxOutputTokens    int               `json:"max_output_tokens,omitempty"`
	Usage              Usage             `json:"usage,omitzero"`
	Tools              []any             `json:"tools,omitempty"`
	ToolChoice         any               `json:"tool_choice,omitempty"`
	Truncation         string            `json:"truncation,omitempty"`
	Store              bool              `json:"store,omitempty"`
	Metadata           map[string]string `json:"metadata,omitempty"`
}

//line stdlib/llm/responses/responses.kuki:114
type ResponseRequest struct {
	Model              string            `json:"model"`
	Input              any               `json:"input"`
	Instructions       string            `json:"instructions,omitempty"`
	PreviousResponseID string            `json:"previous_response_id,omitempty"`
	Temperature        float64           `json:"temperature,omitempty"`
	TopP               float64           `json:"top_p,omitempty"`
	MaxOutputTokens    int               `json:"max_output_tokens,omitempty"`
	PresencePenalty    float64           `json:"presence_penalty,omitempty"`
	FrequencyPenalty   float64           `json:"frequency_penalty,omitempty"`
	Tools              []Tool            `json:"tools,omitempty"`
	ToolChoice         any               `json:"tool_choice,omitempty"`
	Stream             bool              `json:"stream,omitempty"`
	Store              bool              `json:"store,omitempty"`
	Truncation         string            `json:"truncation,omitempty"`
	Metadata           map[string]string `json:"metadata,omitempty"`
	Text               any               `json:"text,omitempty"`
}

//line stdlib/llm/responses/responses.kuki:133
type StreamEvent struct {
	Type           string     `json:"type"`
	SequenceNumber int        `json:"sequence_number"`
	Response       Response   `json:"response,omitzero"`
	OutputIndex    int        `json:"output_index,omitempty"`
	ContentIndex   int        `json:"content_index,omitempty"`
	ItemID         string     `json:"item_id,omitempty"`
	Item           OutputItem `json:"item,omitzero"`
	Delta          string     `json:"delta,omitempty"`
	Text           string     `json:"text,omitempty"`
	Part           any        `json:"part,omitempty"`
	Name           string     `json:"name,omitempty"`
	Arguments      string     `json:"arguments,omitempty"`
	Code           string     `json:"code,omitempty"`
	Message        string     `json:"message,omitempty"`
}

//line stdlib/llm/responses/responses.kuki:150
type Client struct {
	model              string
	provider           string
	baseURL            string
	path               string
	apiKey             string
	input              []InputItem
	instructions       string
	previousResponseID string
	temperature        float64
	topP               float64
	maxOutputTokens    int
	presencePenalty    float64
	frequencyPenalty   float64
	tools              []Tool
	toolChoice         any
	store              bool
	truncation         string
	metadata           map[string]string
	textFormat         any
	streamHandler      func(string)
	eventHandler       func(StreamEvent)
	retryMaxAttempts   int
	retryDelayMs       int
	ctx                context.Context
}

//line stdlib/llm/responses/responses.kuki:178
func New(model string) Client {
//line stdlib/llm/responses/responses.kuki:179
	c := Client{}
//line stdlib/llm/responses/responses.kuki:180
	if strings.Contains(model, ":") {
//line stdlib/llm/responses/responses.kuki:181
		parts := kukistring.SplitN(model, ":", 2)
//line stdlib/llm/responses/responses.kuki:182
		c.provider = parts[0]
//line stdlib/llm/responses/responses.kuki:183
		c.model = parts[1]
	} else {
//line stdlib/llm/responses/responses.kuki:185
		c.model = model
	}
//line stdlib/llm/responses/responses.kuki:186
	return c
}

//line stdlib/llm/responses/responses.kuki:189
func Provider(c Client, provider string) Client {
//line stdlib/llm/responses/responses.kuki:190
	c.provider = provider
//line stdlib/llm/responses/responses.kuki:191
	return c
}

//line stdlib/llm/responses/responses.kuki:194
func BaseURL(c Client, url string) Client {
//line stdlib/llm/responses/responses.kuki:195
	c.baseURL = url
//line stdlib/llm/responses/responses.kuki:196
	return c
}

//line stdlib/llm/responses/responses.kuki:199
func Path(c Client, path string) Client {
//line stdlib/llm/responses/responses.kuki:200
	c.path = path
//line stdlib/llm/responses/responses.kuki:201
	return c
}

//line stdlib/llm/responses/responses.kuki:204
func APIKey(c Client, key string) Client {
//line stdlib/llm/responses/responses.kuki:205
	c.apiKey = key
//line stdlib/llm/responses/responses.kuki:206
	return c
}

//line stdlib/llm/responses/responses.kuki:209
func Instructions(c Client, instructions string) Client {
//line stdlib/llm/responses/responses.kuki:210
	c.instructions = instructions
//line stdlib/llm/responses/responses.kuki:211
	return c
}

//line stdlib/llm/responses/responses.kuki:214
func PreviousResponse(c Client, id string) Client {
//line stdlib/llm/responses/responses.kuki:215
	c.previousResponseID = id
//line stdlib/llm/responses/responses.kuki:216
	return c
}

//line stdlib/llm/responses/responses.kuki:219
func User(c Client, content string) Client {
//line stdlib/llm/responses/responses.kuki:220
	item := InputItem{}
//line stdlib/llm/responses/responses.kuki:221
	item.Type = "message"
//line stdlib/llm/responses/responses.kuki:222
	item.Role = "user"
//line stdlib/llm/responses/responses.kuki:223
	item.Content = content
//line stdlib/llm/responses/responses.kuki:224
	c.input = append(c.input, item)
//line stdlib/llm/responses/responses.kuki:225
	return c
}

//line stdlib/llm/responses/responses.kuki:228
func System(c Client, content string) Client {
//line stdlib/llm/responses/responses.kuki:229
	item := InputItem{}
//line stdlib/llm/responses/responses.kuki:230
	item.Type = "message"
//line stdlib/llm/responses/responses.kuki:231
	item.Role = "system"
//line stdlib/llm/responses/responses.kuki:232
	item.Content = content
//line stdlib/llm/responses/responses.kuki:233
	c.input = append(c.input, item)
//line stdlib/llm/responses/responses.kuki:234
	return c
}

//line stdlib/llm/responses/responses.kuki:237
func Developer(c Client, content string) Client {
//line stdlib/llm/responses/responses.kuki:238
	item := InputItem{}
//line stdlib/llm/responses/responses.kuki:239
	item.Type = "message"
//line stdlib/llm/responses/responses.kuki:240
	item.Role = "developer"
//line stdlib/llm/responses/responses.kuki:241
	item.Content = content
//line stdlib/llm/responses/responses.kuki:242
	c.input = append(c.input, item)
//line stdlib/llm/responses/responses.kuki:243
	return c
}

//line stdlib/llm/responses/responses.kuki:246
func Assistant(c Client, content string) Client {
//line stdlib/llm/responses/responses.kuki:247
	item := InputItem{}
//line stdlib/llm/responses/responses.kuki:248
	item.Type = "message"
//line stdlib/llm/responses/responses.kuki:249
	item.Role = "assistant"
//line stdlib/llm/responses/responses.kuki:250
	item.Content = content
//line stdlib/llm/responses/responses.kuki:251
	c.input = append(c.input, item)
//line stdlib/llm/responses/responses.kuki:252
	return c
}

//line stdlib/llm/responses/responses.kuki:255
func AddInput(c Client, item InputItem) Client {
//line stdlib/llm/responses/responses.kuki:256
	c.input = append(c.input, item)
//line stdlib/llm/responses/responses.kuki:257
	return c
}

//line stdlib/llm/responses/responses.kuki:260
func FunctionCallOutput(c Client, callID string, output string) Client {
//line stdlib/llm/responses/responses.kuki:261
	item := InputItem{}
//line stdlib/llm/responses/responses.kuki:262
	item.Type = "function_call_output"
//line stdlib/llm/responses/responses.kuki:263
	item.CallID = callID
//line stdlib/llm/responses/responses.kuki:264
	item.Output = output
//line stdlib/llm/responses/responses.kuki:265
	c.input = append(c.input, item)
//line stdlib/llm/responses/responses.kuki:266
	return c
}

//line stdlib/llm/responses/responses.kuki:269
func Temperature(c Client, temp float64) Client {
//line stdlib/llm/responses/responses.kuki:270
	c.temperature = temp
//line stdlib/llm/responses/responses.kuki:271
	return c
}

//line stdlib/llm/responses/responses.kuki:274
func TopP(c Client, p float64) Client {
//line stdlib/llm/responses/responses.kuki:275
	c.topP = p
//line stdlib/llm/responses/responses.kuki:276
	return c
}

//line stdlib/llm/responses/responses.kuki:279
func MaxOutputTokens(c Client, tokens int) Client {
//line stdlib/llm/responses/responses.kuki:280
	c.maxOutputTokens = tokens
//line stdlib/llm/responses/responses.kuki:281
	return c
}

//line stdlib/llm/responses/responses.kuki:284
func PresencePenalty(c Client, penalty float64) Client {
//line stdlib/llm/responses/responses.kuki:285
	c.presencePenalty = penalty
//line stdlib/llm/responses/responses.kuki:286
	return c
}

//line stdlib/llm/responses/responses.kuki:289
func FrequencyPenalty(c Client, penalty float64) Client {
//line stdlib/llm/responses/responses.kuki:290
	c.frequencyPenalty = penalty
//line stdlib/llm/responses/responses.kuki:291
	return c
}

//line stdlib/llm/responses/responses.kuki:294
func AddTool(c Client, name string, description string, parameters any) Client {
//line stdlib/llm/responses/responses.kuki:295
	fn := ToolFunction{Name: name, Description: description, Parameters: parameters}
//line stdlib/llm/responses/responses.kuki:296
	c.tools = append(c.tools, Tool{Type: "function", Function: fn})
//line stdlib/llm/responses/responses.kuki:297
	return c
}

//line stdlib/llm/responses/responses.kuki:300
func ToolChoiceAuto(c Client) Client {
//line stdlib/llm/responses/responses.kuki:301
	c.toolChoice = "auto"
//line stdlib/llm/responses/responses.kuki:302
	return c
}

//line stdlib/llm/responses/responses.kuki:305
func ToolChoiceRequired(c Client) Client {
//line stdlib/llm/responses/responses.kuki:306
	c.toolChoice = "required"
//line stdlib/llm/responses/responses.kuki:307
	return c
}

//line stdlib/llm/responses/responses.kuki:310
func ToolChoiceNone(c Client) Client {
//line stdlib/llm/responses/responses.kuki:311
	c.toolChoice = "none"
//line stdlib/llm/responses/responses.kuki:312
	return c
}

//line stdlib/llm/responses/responses.kuki:315
func JSONMode(c Client) Client {
//line stdlib/llm/responses/responses.kuki:316
	c.textFormat = map[string]string{"type": "json_object"}
//line stdlib/llm/responses/responses.kuki:317
	return c
}

//line stdlib/llm/responses/responses.kuki:320
func JSONSchema(c Client, name string, schema any) Client {
//line stdlib/llm/responses/responses.kuki:321
	c.textFormat = map[string]any{"type": "json_schema", "name": name, "schema": schema, "strict": true}
//line stdlib/llm/responses/responses.kuki:322
	return c
}

//line stdlib/llm/responses/responses.kuki:325
func Store(c Client) Client {
//line stdlib/llm/responses/responses.kuki:326
	c.store = true
//line stdlib/llm/responses/responses.kuki:327
	return c
}

//line stdlib/llm/responses/responses.kuki:330
func Truncation(c Client, mode string) Client {
//line stdlib/llm/responses/responses.kuki:331
	c.truncation = mode
//line stdlib/llm/responses/responses.kuki:332
	return c
}

//line stdlib/llm/responses/responses.kuki:335
func Metadata(c Client, meta map[string]string) Client {
//line stdlib/llm/responses/responses.kuki:336
	c.metadata = meta
//line stdlib/llm/responses/responses.kuki:337
	return c
}

//line stdlib/llm/responses/responses.kuki:340
func Stream(c Client, handler func(string)) Client {
//line stdlib/llm/responses/responses.kuki:341
	c.streamHandler = handler
//line stdlib/llm/responses/responses.kuki:342
	return c
}

//line stdlib/llm/responses/responses.kuki:345
func StreamEvents(c Client, handler func(StreamEvent)) Client {
//line stdlib/llm/responses/responses.kuki:346
	c.eventHandler = handler
//line stdlib/llm/responses/responses.kuki:347
	return c
}

//line stdlib/llm/responses/responses.kuki:350
func Retry(c Client, maxAttempts int, delayMs int) Client {
//line stdlib/llm/responses/responses.kuki:351
	c.retryMaxAttempts = maxAttempts
//line stdlib/llm/responses/responses.kuki:352
	c.retryDelayMs = delayMs
//line stdlib/llm/responses/responses.kuki:353
	return c
}

//line stdlib/llm/responses/responses.kuki:356
func WithContext(c Client, h ctxpkg.Handle) Client {
//line stdlib/llm/responses/responses.kuki:357
	c.ctx = h.Ctx
//line stdlib/llm/responses/responses.kuki:358
	return c
}

//line stdlib/llm/responses/responses.kuki:362
func Ask(c Client, prompt string) (string, error) {
//line stdlib/llm/responses/responses.kuki:363
	c = User(c, prompt)
//line stdlib/llm/responses/responses.kuki:364
	return doExecute(c)
}

//line stdlib/llm/responses/responses.kuki:367
func Send(c Client) (string, error) {
//line stdlib/llm/responses/responses.kuki:368
	return doExecute(c)
}

//line stdlib/llm/responses/responses.kuki:371
func AskRaw(c Client, prompt string) (Response, error) {
//line stdlib/llm/responses/responses.kuki:372
	c = User(c, prompt)
//line stdlib/llm/responses/responses.kuki:373
	return doExecuteRaw(c)
}

//line stdlib/llm/responses/responses.kuki:376
func SendRaw(c Client) (Response, error) {
//line stdlib/llm/responses/responses.kuki:377
	return doExecuteRaw(c)
}

//line stdlib/llm/responses/responses.kuki:380
func Respond(model string, prompt string) (string, error) {
//line stdlib/llm/responses/responses.kuki:381
	return Ask(New(model), prompt)
}

//line stdlib/llm/responses/responses.kuki:384
func RespondWithInstructions(model string, instructions string, prompt string) (string, error) {
//line stdlib/llm/responses/responses.kuki:385
	c := New(model)
//line stdlib/llm/responses/responses.kuki:386
	c = Instructions(c, instructions)
//line stdlib/llm/responses/responses.kuki:387
	return Ask(c, prompt)
}

//line stdlib/llm/responses/responses.kuki:392
func FromResponse(c Client, resp Response) Client {
//line stdlib/llm/responses/responses.kuki:393
	return PreviousResponse(c, resp.ID)
}

//line stdlib/llm/responses/responses.kuki:400
func ExecuteFunctionCalls(c Client, resp Response, handlers map[string]func(string) string) (Client, error) {
//line stdlib/llm/responses/responses.kuki:401
	calls := GetFunctionCalls(resp)
//line stdlib/llm/responses/responses.kuki:402
	if len(calls) == 0 {
//line stdlib/llm/responses/responses.kuki:403
		return c, nil
	}
//line stdlib/llm/responses/responses.kuki:404
	c = FromResponse(c, resp)
//line stdlib/llm/responses/responses.kuki:405
	for _, call := range calls {
//line stdlib/llm/responses/responses.kuki:406
		handler, ok := handlers[call.Name]
//line stdlib/llm/responses/responses.kuki:407
		if !ok {
//line stdlib/llm/responses/responses.kuki:408
			return c, fmt.Errorf("no handler registered for function: %v", call.Name)
		}
//line stdlib/llm/responses/responses.kuki:409
		result := handler(call.Arguments)
//line stdlib/llm/responses/responses.kuki:410
		c = FunctionCallOutput(c, call.CallID, result)
	}
//line stdlib/llm/responses/responses.kuki:411
	return c, nil
}

//line stdlib/llm/responses/responses.kuki:414
func GetText(resp Response) string {
//line stdlib/llm/responses/responses.kuki:415
	for _, item := range resp.Output {
//line stdlib/llm/responses/responses.kuki:416
		if item.Type == "message" {
//line stdlib/llm/responses/responses.kuki:417
			for _, content := range item.Content {
//line stdlib/llm/responses/responses.kuki:418
				switch contentMap := content.(type) {
				case map[string]any:
//line stdlib/llm/responses/responses.kuki:420
					switch contentTypeStr := contentMap["type"].(type) {
					case string:
//line stdlib/llm/responses/responses.kuki:422
						if contentTypeStr == "output_text" {
//line stdlib/llm/responses/responses.kuki:423
							switch textStr := contentMap["text"].(type) {
							case string:
//line stdlib/llm/responses/responses.kuki:425
								return textStr
							}
						}
					}
				}
			}
		}
	}
//line stdlib/llm/responses/responses.kuki:427
	return ""
}

//line stdlib/llm/responses/responses.kuki:430
func GetFunctionCalls(resp Response) []OutputItem {
//line stdlib/llm/responses/responses.kuki:431
	calls := []OutputItem{}
//line stdlib/llm/responses/responses.kuki:432
	for _, item := range resp.Output {
//line stdlib/llm/responses/responses.kuki:433
		if item.Type == "function_call" {
//line stdlib/llm/responses/responses.kuki:434
			calls = append(calls, item)
		}
	}
//line stdlib/llm/responses/responses.kuki:435
	return calls
}

//line stdlib/llm/responses/responses.kuki:438
func HasFunctionCalls(resp Response) bool {
//line stdlib/llm/responses/responses.kuki:439
	return (len(GetFunctionCalls(resp)) > 0)
}

//line stdlib/llm/responses/responses.kuki:441
func providerDefaults(provider string) (string, string) {
//line stdlib/llm/responses/responses.kuki:442
	if provider == "openai" {
//line stdlib/llm/responses/responses.kuki:443
		return "OPENAI_API_KEY", "https://api.openai.com"
	}
//line stdlib/llm/responses/responses.kuki:444
	if provider == "mistral" {
//line stdlib/llm/responses/responses.kuki:445
		return "MISTRAL_API_KEY", "https://api.mistral.ai"
	}
//line stdlib/llm/responses/responses.kuki:446
	if provider == "groq" {
//line stdlib/llm/responses/responses.kuki:447
		return "GROQ_API_KEY", "https://api.groq.com/openai"
	}
//line stdlib/llm/responses/responses.kuki:448
	if provider == "together" {
//line stdlib/llm/responses/responses.kuki:449
		return "TOGETHER_API_KEY", "https://api.together.xyz"
	}
//line stdlib/llm/responses/responses.kuki:450
	if provider == "deepseek" {
//line stdlib/llm/responses/responses.kuki:451
		return "DEEPSEEK_API_KEY", "https://api.deepseek.com"
	}
//line stdlib/llm/responses/responses.kuki:452
	if provider == "xai" {
//line stdlib/llm/responses/responses.kuki:453
		return "XAI_API_KEY", "https://api.x.ai"
	}
//line stdlib/llm/responses/responses.kuki:454
	if provider == "ollama" {
//line stdlib/llm/responses/responses.kuki:455
		return "", "http://localhost:11434"
	}
//line stdlib/llm/responses/responses.kuki:456
	if (provider == "fastflowlm") || (provider == "flm") {
//line stdlib/llm/responses/responses.kuki:457
		return "", "http://localhost:52625"
	}
//line stdlib/llm/responses/responses.kuki:458
	return "", ""
}

//line stdlib/llm/responses/responses.kuki:460
func resolveAPIKey(c Client) string {
//line stdlib/llm/responses/responses.kuki:461
	if c.apiKey != "" {
//line stdlib/llm/responses/responses.kuki:462
		return c.apiKey
	}
//line stdlib/llm/responses/responses.kuki:463
	envKey, _ := providerDefaults(c.provider)
//line stdlib/llm/responses/responses.kuki:464
	if envKey != "" {
//line stdlib/llm/responses/responses.kuki:465
		return env.GetOr(envKey, "")
	}
//line stdlib/llm/responses/responses.kuki:466
	return env.GetOr("LLM_API_KEY", "")
}

//line stdlib/llm/responses/responses.kuki:468
func resolveBaseURL(c Client) string {
//line stdlib/llm/responses/responses.kuki:469
	if c.baseURL != "" {
//line stdlib/llm/responses/responses.kuki:470
		return c.baseURL
	}
//line stdlib/llm/responses/responses.kuki:471
	_, baseURL := providerDefaults(c.provider)
//line stdlib/llm/responses/responses.kuki:472
	if baseURL != "" {
//line stdlib/llm/responses/responses.kuki:473
		return baseURL
	}
//line stdlib/llm/responses/responses.kuki:474
	envURL := env.GetOr("LLM_BASE_URL", "")
//line stdlib/llm/responses/responses.kuki:475
	if envURL != "" {
//line stdlib/llm/responses/responses.kuki:476
		return envURL
	}
//line stdlib/llm/responses/responses.kuki:477
	return "http://localhost:8000"
}

//line stdlib/llm/responses/responses.kuki:479
func resolvePath(c Client) string {
//line stdlib/llm/responses/responses.kuki:480
	if c.path != "" {
//line stdlib/llm/responses/responses.kuki:481
		return c.path
	}
//line stdlib/llm/responses/responses.kuki:482
	return "/v1/responses"
}

//line stdlib/llm/responses/responses.kuki:484
func buildRequest(c Client) ResponseRequest {
//line stdlib/llm/responses/responses.kuki:485
	req := ResponseRequest{Model: c.model, Input: c.input}
//line stdlib/llm/responses/responses.kuki:486
	if c.instructions != "" {
//line stdlib/llm/responses/responses.kuki:487
		req.Instructions = c.instructions
	}
//line stdlib/llm/responses/responses.kuki:488
	if c.previousResponseID != "" {
//line stdlib/llm/responses/responses.kuki:489
		req.PreviousResponseID = c.previousResponseID
	}
//line stdlib/llm/responses/responses.kuki:490
	if c.temperature != 0.0 {
//line stdlib/llm/responses/responses.kuki:491
		req.Temperature = c.temperature
	}
//line stdlib/llm/responses/responses.kuki:492
	if c.topP != 0.0 {
//line stdlib/llm/responses/responses.kuki:493
		req.TopP = c.topP
	}
//line stdlib/llm/responses/responses.kuki:494
	if c.maxOutputTokens != 0 {
//line stdlib/llm/responses/responses.kuki:495
		req.MaxOutputTokens = c.maxOutputTokens
	}
//line stdlib/llm/responses/responses.kuki:496
	if c.presencePenalty != 0.0 {
//line stdlib/llm/responses/responses.kuki:497
		req.PresencePenalty = c.presencePenalty
	}
//line stdlib/llm/responses/responses.kuki:498
	if c.frequencyPenalty != 0.0 {
//line stdlib/llm/responses/responses.kuki:499
		req.FrequencyPenalty = c.frequencyPenalty
	}
//line stdlib/llm/responses/responses.kuki:500
	if len(c.tools) > 0 {
//line stdlib/llm/responses/responses.kuki:501
		req.Tools = c.tools
	}
//line stdlib/llm/responses/responses.kuki:502
	if c.toolChoice != nil {
//line stdlib/llm/responses/responses.kuki:503
		req.ToolChoice = c.toolChoice
	}
//line stdlib/llm/responses/responses.kuki:504
	if c.store {
//line stdlib/llm/responses/responses.kuki:505
		req.Store = true
	}
//line stdlib/llm/responses/responses.kuki:506
	if c.truncation != "" {
//line stdlib/llm/responses/responses.kuki:507
		req.Truncation = c.truncation
	}
//line stdlib/llm/responses/responses.kuki:508
	if len(c.metadata) > 0 {
//line stdlib/llm/responses/responses.kuki:509
		req.Metadata = c.metadata
	}
//line stdlib/llm/responses/responses.kuki:510
	if c.textFormat != nil {
//line stdlib/llm/responses/responses.kuki:511
		req.Text = c.textFormat
	}
//line stdlib/llm/responses/responses.kuki:512
	if (c.streamHandler != nil) || (c.eventHandler != nil) {
//line stdlib/llm/responses/responses.kuki:513
		req.Stream = true
	}
//line stdlib/llm/responses/responses.kuki:514
	return req
}

//line stdlib/llm/responses/responses.kuki:516
func doExecute(c Client) (string, error) {
//line stdlib/llm/responses/responses.kuki:517
	resp, err_1 := doExecuteRaw(c)
//line stdlib/llm/responses/responses.kuki:517
	if err_1 != nil {
//line stdlib/llm/responses/responses.kuki:517
		return "", err_1
	}
//line stdlib/llm/responses/responses.kuki:518
	return GetText(resp), nil
}

//line stdlib/llm/responses/responses.kuki:520
func doExecuteRaw(c Client) (Response, error) {
//line stdlib/llm/responses/responses.kuki:521
	if (c.streamHandler != nil) || (c.eventHandler != nil) {
//line stdlib/llm/responses/responses.kuki:522
		return doExecuteStreamRaw(c)
	}
//line stdlib/llm/responses/responses.kuki:524
	url := fmt.Sprintf("%v%v", resolveBaseURL(c), resolvePath(c))
//line stdlib/llm/responses/responses.kuki:525
	apiKey := resolveAPIKey(c)
//line stdlib/llm/responses/responses.kuki:527
	req := fetch.Body(fetch.Header(fetch.Method(fetch.New(url), "POST"), "Content-Type", "application/json"), buildRequest(c))
//line stdlib/llm/responses/responses.kuki:532
	if c.ctx != nil {
//line stdlib/llm/responses/responses.kuki:533
		req = fetch.WithContext(req, ctxpkg.FromContext(c.ctx))
	}
//line stdlib/llm/responses/responses.kuki:534
	if apiKey != "" {
//line stdlib/llm/responses/responses.kuki:535
		req = fetch.Header(req, "Authorization", fmt.Sprintf("Bearer %v", apiKey))
	}
//line stdlib/llm/responses/responses.kuki:536
	if c.retryMaxAttempts > 1 {
//line stdlib/llm/responses/responses.kuki:537
		req = fetch.Retry(req, c.retryMaxAttempts, c.retryDelayMs)
	}
//line stdlib/llm/responses/responses.kuki:539
	resp, err_2 := fetch.Do(req)
//line stdlib/llm/responses/responses.kuki:539
	if err_2 != nil {
		var _zero0 Response
//line stdlib/llm/responses/responses.kuki:539
		return _zero0, err_2
	}
//line stdlib/llm/responses/responses.kuki:541
	defer resp.Body.Close()
//line stdlib/llm/responses/responses.kuki:543
	if resp.StatusCode >= 400 {
//line stdlib/llm/responses/responses.kuki:544
		errBody, err_3 := fetch.Bytes(resp)
//line stdlib/llm/responses/responses.kuki:544
		if err_3 != nil {
//line stdlib/llm/responses/responses.kuki:544
			return Response{}, fmt.Errorf("API request failed with status %v", resp.StatusCode)
		}
//line stdlib/llm/responses/responses.kuki:545
		return Response{}, fmt.Errorf("API request failed (%v): %v", resp.StatusCode, string(errBody))
	}
//line stdlib/llm/responses/responses.kuki:547
	result := Response{}
//line stdlib/llm/responses/responses.kuki:548
//line stdlib/llm/responses/responses.kuki:548
	err_4 := json.ReadInto(resp.Body, &result)
//line stdlib/llm/responses/responses.kuki:548
	if err_4 != nil {
		var _zero0 Response
//line stdlib/llm/responses/responses.kuki:548
		return _zero0, err_4
	}
//line stdlib/llm/responses/responses.kuki:549
	return result, nil
}

//line stdlib/llm/responses/responses.kuki:551
func doExecuteStreamRaw(c Client) (Response, error) {
//line stdlib/llm/responses/responses.kuki:552
	url := fmt.Sprintf("%v%v", resolveBaseURL(c), resolvePath(c))
//line stdlib/llm/responses/responses.kuki:553
	apiKey := resolveAPIKey(c)
//line stdlib/llm/responses/responses.kuki:555
	req := fetch.Body(fetch.Header(fetch.Header(fetch.Method(fetch.New(url), "POST"), "Content-Type", "application/json"), "Accept", "text/event-stream"), buildRequest(c))
//line stdlib/llm/responses/responses.kuki:561
	if c.ctx != nil {
//line stdlib/llm/responses/responses.kuki:562
		req = fetch.WithContext(req, ctxpkg.FromContext(c.ctx))
	}
//line stdlib/llm/responses/responses.kuki:563
	if apiKey != "" {
//line stdlib/llm/responses/responses.kuki:564
		req = fetch.Header(req, "Authorization", fmt.Sprintf("Bearer %v", apiKey))
	}
//line stdlib/llm/responses/responses.kuki:565
	if c.retryMaxAttempts > 1 {
//line stdlib/llm/responses/responses.kuki:566
		req = fetch.Retry(req, c.retryMaxAttempts, c.retryDelayMs)
	}
//line stdlib/llm/responses/responses.kuki:568
	resp, err_5 := fetch.Do(req)
//line stdlib/llm/responses/responses.kuki:568
	if err_5 != nil {
		var _zero0 Response
//line stdlib/llm/responses/responses.kuki:568
		return _zero0, err_5
	}
//line stdlib/llm/responses/responses.kuki:570
	defer resp.Body.Close()
//line stdlib/llm/responses/responses.kuki:572
	if resp.StatusCode >= 400 {
//line stdlib/llm/responses/responses.kuki:573
		errBody, err_6 := fetch.Bytes(resp)
//line stdlib/llm/responses/responses.kuki:573
		if err_6 != nil {
//line stdlib/llm/responses/responses.kuki:573
			return Response{}, fmt.Errorf("API request failed with status %v", resp.StatusCode)
		}
//line stdlib/llm/responses/responses.kuki:574
		return Response{}, fmt.Errorf("API request failed (%v): %v", resp.StatusCode, string(errBody))
	}
//line stdlib/llm/responses/responses.kuki:576
	fullContent := ""
//line stdlib/llm/responses/responses.kuki:577
	callsMap := make(map[int]OutputItem)
//line stdlib/llm/responses/responses.kuki:578
	maxIdx := -1
//line stdlib/llm/responses/responses.kuki:579
	scanner := bufio.NewScanner(resp.Body)
//line stdlib/llm/responses/responses.kuki:580
	for scanner.Scan() {
//line stdlib/llm/responses/responses.kuki:581
		line := scanner.Text()
//line stdlib/llm/responses/responses.kuki:582
		if (line == "") || kukistring.HasPrefix(line, ":") {
//line stdlib/llm/responses/responses.kuki:583
			continue
		}
//line stdlib/llm/responses/responses.kuki:584
		if line == "data: [DONE]" {
//line stdlib/llm/responses/responses.kuki:585
			break
		}
//line stdlib/llm/responses/responses.kuki:586
		if kukistring.HasPrefix(line, "data: ") {
//line stdlib/llm/responses/responses.kuki:587
			data := kukistring.TrimPrefix(line, "data: ")
//line stdlib/llm/responses/responses.kuki:588
			evt := StreamEvent{}
//line stdlib/llm/responses/responses.kuki:589
//line stdlib/llm/responses/responses.kuki:589
			err_7 := json.ParseInto([]byte(data), &evt)
//line stdlib/llm/responses/responses.kuki:589
			if err_7 != nil {
//line stdlib/llm/responses/responses.kuki:589
				//line stdlib/llm/responses/responses.kuki:590
				continue
			}
//line stdlib/llm/responses/responses.kuki:592
			if c.eventHandler != nil {
//line stdlib/llm/responses/responses.kuki:593
				c.eventHandler(evt)
			}
//line stdlib/llm/responses/responses.kuki:595
			if evt.Type == "response.output_text.delta" {
//line stdlib/llm/responses/responses.kuki:596
				if evt.Delta != "" {
//line stdlib/llm/responses/responses.kuki:597
					fullContent = (fullContent + evt.Delta)
//line stdlib/llm/responses/responses.kuki:598
					if c.streamHandler != nil {
//line stdlib/llm/responses/responses.kuki:599
						c.streamHandler(evt.Delta)
					}
				}
			}
//line stdlib/llm/responses/responses.kuki:601
			if (evt.Type == "response.function_call.delta") || (evt.Type == "response.function_call_arguments.delta") {
//line stdlib/llm/responses/responses.kuki:602
				idx := evt.OutputIndex
//line stdlib/llm/responses/responses.kuki:603
				call := callsMap[idx]
//line stdlib/llm/responses/responses.kuki:604
				call.Type = "function_call"
//line stdlib/llm/responses/responses.kuki:605
				if evt.ItemID != "" {
//line stdlib/llm/responses/responses.kuki:606
					call.ID = evt.ItemID
				}
//line stdlib/llm/responses/responses.kuki:607
				if evt.Name != "" {
//line stdlib/llm/responses/responses.kuki:608
					call.Name = (call.Name + evt.Name)
				}
//line stdlib/llm/responses/responses.kuki:609
				if evt.Arguments != "" {
//line stdlib/llm/responses/responses.kuki:610
					call.Arguments = (call.Arguments + evt.Arguments)
				}
//line stdlib/llm/responses/responses.kuki:611
				callsMap[idx] = call
//line stdlib/llm/responses/responses.kuki:612
				if idx > maxIdx {
//line stdlib/llm/responses/responses.kuki:613
					maxIdx = idx
				}
			}
//line stdlib/llm/responses/responses.kuki:615
			if evt.Type == "error" {
//line stdlib/llm/responses/responses.kuki:616
				return Response{}, errors.New(evt.Message)
			}
		}
	}
//line stdlib/llm/responses/responses.kuki:618
//line stdlib/llm/responses/responses.kuki:618
	err_8 := scanner.Err()
//line stdlib/llm/responses/responses.kuki:618
	if err_8 != nil {
//line stdlib/llm/responses/responses.kuki:618
		return Response{}, fmt.Errorf("%v", err_8)
	}
//line stdlib/llm/responses/responses.kuki:620
	output := []OutputItem{}
//line stdlib/llm/responses/responses.kuki:621
	for i := range maxIdx + 1 {
//line stdlib/llm/responses/responses.kuki:622
		_, ok := callsMap[i]
//line stdlib/llm/responses/responses.kuki:623
		if ok {
//line stdlib/llm/responses/responses.kuki:624
			output = append(output, callsMap[i])
		}
	}
//line stdlib/llm/responses/responses.kuki:626
	if fullContent != "" {
//line stdlib/llm/responses/responses.kuki:627
		msgPart := map[string]any{"type": "output_text", "text": fullContent}
//line stdlib/llm/responses/responses.kuki:628
		output = append(output, OutputItem{Type: "message", Role: "assistant", Content: []any{msgPart}})
	}
//line stdlib/llm/responses/responses.kuki:633
	return Response{Output: output}, nil
}
