// Generated by Kukicha (requires Go 1.26+)

package ctx_test

import (
	"github.com/kukichalang/kukicha/stdlib/ctx"
	"github.com/kukichalang/kukicha/stdlib/test"
	"testing"
	"time"
)

//line stdlib/ctx/ctx_test.kuki:11
func TestBackground(t *testing.T) {
//line stdlib/ctx/ctx_test.kuki:12
	h := ctx.Background()
//line stdlib/ctx/ctx_test.kuki:13
	test.AssertEqual(t, h.Ctx.Err(), nil)
//line stdlib/ctx/ctx_test.kuki:15
	h.Cancel()
//line stdlib/ctx/ctx_test.kuki:16
	test.AssertEqual(t, h.Ctx.Err(), nil)
}

//line stdlib/ctx/ctx_test.kuki:19
func TestWithTimeoutCancel(t *testing.T) {
//line stdlib/ctx/ctx_test.kuki:20
	h := ctx.WithTimeout(ctx.Background(), (60 * time.Second))
//line stdlib/ctx/ctx_test.kuki:21
	test.AssertEqual(t, h.Ctx.Err(), nil)
//line stdlib/ctx/ctx_test.kuki:22
	h.Cancel()
//line stdlib/ctx/ctx_test.kuki:23
	test.AssertNotEqual(t, h.Ctx.Err(), nil)
}
