// Generated by Kukicha (requires Go 1.26+)

package maps_test

import (
	"github.com/kukichalang/kukicha/stdlib/maps"
	"github.com/kukichalang/kukicha/stdlib/slice"
	"testing"
)

//line stdlib/maps/maps_test.kuki:10
func TestMapHelpers(t *testing.T) {
//line stdlib/maps/maps_test.kuki:13
	sample := map[any]any{any("a"): any("1"), any("b"): any("2")}
//line stdlib/maps/maps_test.kuki:14
	keys := maps.Keys(sample)
//line stdlib/maps/maps_test.kuki:15
	if len(keys) != 2 {
//line stdlib/maps/maps_test.kuki:16
		t.Fatalf("Expected 2 keys, got %v", len(keys))
	}
//line stdlib/maps/maps_test.kuki:17
	if !slice.Contains(keys, "a") {
//line stdlib/maps/maps_test.kuki:18
		t.Errorf("Keys should include 'a'")
	}
//line stdlib/maps/maps_test.kuki:20
	values := maps.Values(sample)
//line stdlib/maps/maps_test.kuki:21
	if len(values) != 2 {
//line stdlib/maps/maps_test.kuki:22
		t.Fatalf("Expected 2 values, got %v", len(values))
	}
//line stdlib/maps/maps_test.kuki:23
	if !slice.Contains(values, "2") {
//line stdlib/maps/maps_test.kuki:24
		t.Errorf("Values should include '2'")
	}
//line stdlib/maps/maps_test.kuki:26
	if !maps.Contains(sample, "a") {
//line stdlib/maps/maps_test.kuki:27
		t.Errorf("Contains should return true for existing key")
	}
//line stdlib/maps/maps_test.kuki:28
	if maps.Contains(sample, "missing") {
//line stdlib/maps/maps_test.kuki:29
		t.Errorf("Contains should return false for missing key")
	}
}

//line stdlib/maps/maps_test.kuki:32
func TestMerge(t *testing.T) {
//line stdlib/maps/maps_test.kuki:33
	base := map[any]any{any("a"): any("1"), any("b"): any("2")}
//line stdlib/maps/maps_test.kuki:34
	overlay := map[any]any{any("b"): any("99"), any("c"): any("3")}
//line stdlib/maps/maps_test.kuki:35
	merged := maps.Merge(base, overlay)
//line stdlib/maps/maps_test.kuki:36
	if len(merged) != 3 {
//line stdlib/maps/maps_test.kuki:37
		t.Fatalf("Expected 3 keys, got %v", len(merged))
	}
//line stdlib/maps/maps_test.kuki:38
	if merged["a"] != "1" {
//line stdlib/maps/maps_test.kuki:39
		t.Errorf("Merge should keep base key 'a'")
	}
//line stdlib/maps/maps_test.kuki:40
	if merged["b"] != "99" {
//line stdlib/maps/maps_test.kuki:41
		t.Errorf("Merge should prefer overlay value for 'b'")
	}
//line stdlib/maps/maps_test.kuki:42
	if merged["c"] != "3" {
//line stdlib/maps/maps_test.kuki:43
		t.Errorf("Merge should include overlay key 'c'")
	}
}

//line stdlib/maps/maps_test.kuki:46
func TestSortedKeys(t *testing.T) {
//line stdlib/maps/maps_test.kuki:47
	sample := map[any]any{any("c"): any("3"), any("a"): any("1"), any("b"): any("2")}
//line stdlib/maps/maps_test.kuki:48
	keys := maps.SortedKeys(sample)
//line stdlib/maps/maps_test.kuki:49
	if len(keys) != 3 {
//line stdlib/maps/maps_test.kuki:50
		t.Fatalf("Expected 3 keys, got %v", len(keys))
	}
//line stdlib/maps/maps_test.kuki:51
	if keys[0] != "a" {
//line stdlib/maps/maps_test.kuki:52
		t.Errorf("Expected first key 'a', got '%v'", keys[0])
	}
//line stdlib/maps/maps_test.kuki:53
	if keys[1] != "b" {
//line stdlib/maps/maps_test.kuki:54
		t.Errorf("Expected second key 'b', got '%v'", keys[1])
	}
//line stdlib/maps/maps_test.kuki:55
	if keys[2] != "c" {
//line stdlib/maps/maps_test.kuki:56
		t.Errorf("Expected third key 'c', got '%v'", keys[2])
	}
}

//line stdlib/maps/maps_test.kuki:59
func TestPick(t *testing.T) {
//line stdlib/maps/maps_test.kuki:60
	m := map[any]any{any("a"): any("1"), any("b"): any("2"), any("c"): any("3")}
//line stdlib/maps/maps_test.kuki:61
	t.Run("picks specified keys", func(t *testing.T) {
//line stdlib/maps/maps_test.kuki:62
		result := maps.Pick(m, []any{any("a"), any("c")})
//line stdlib/maps/maps_test.kuki:63
		if len(result) != 2 {
//line stdlib/maps/maps_test.kuki:64
			t.Errorf("Expected 2 entries, got %v", len(result))
		}
//line stdlib/maps/maps_test.kuki:65
		if result["a"] != any("1") {
//line stdlib/maps/maps_test.kuki:66
			t.Errorf("Expected value '1' for key 'a'")
		}
//line stdlib/maps/maps_test.kuki:67
		_, hasB := result["b"]
//line stdlib/maps/maps_test.kuki:68
		if hasB {
//line stdlib/maps/maps_test.kuki:69
			t.Errorf("Key 'b' should not be in result")
		}
	})
//line stdlib/maps/maps_test.kuki:72
	t.Run("missing keys ignored", func(t *testing.T) {
//line stdlib/maps/maps_test.kuki:73
		result := maps.Pick(m, []any{any("a"), any("z")})
//line stdlib/maps/maps_test.kuki:74
		if len(result) != 1 {
//line stdlib/maps/maps_test.kuki:75
			t.Errorf("Expected 1 entry, got %v", len(result))
		}
	})
}

//line stdlib/maps/maps_test.kuki:79
func TestOmit(t *testing.T) {
//line stdlib/maps/maps_test.kuki:80
	m := map[any]any{any("a"): any("1"), any("b"): any("2"), any("c"): any("3")}
//line stdlib/maps/maps_test.kuki:81
	t.Run("omits specified keys", func(t *testing.T) {
//line stdlib/maps/maps_test.kuki:82
		result := maps.Omit(m, []any{any("b")})
//line stdlib/maps/maps_test.kuki:83
		if len(result) != 2 {
//line stdlib/maps/maps_test.kuki:84
			t.Errorf("Expected 2 entries, got %v", len(result))
		}
//line stdlib/maps/maps_test.kuki:85
		_, hasB := result["b"]
//line stdlib/maps/maps_test.kuki:86
		if hasB {
//line stdlib/maps/maps_test.kuki:87
			t.Errorf("Key 'b' should have been omitted")
		}
//line stdlib/maps/maps_test.kuki:88
		if result["a"] != any("1") {
//line stdlib/maps/maps_test.kuki:89
			t.Errorf("Expected value '1' for key 'a'")
		}
	})
//line stdlib/maps/maps_test.kuki:92
	t.Run("omit missing key is no-op", func(t *testing.T) {
//line stdlib/maps/maps_test.kuki:93
		result := maps.Omit(m, []any{any("z")})
//line stdlib/maps/maps_test.kuki:94
		if len(result) != 3 {
//line stdlib/maps/maps_test.kuki:95
			t.Errorf("Expected 3 entries, got %v", len(result))
		}
	})
}
