// Generated by Kukicha (requires Go 1.26+)

package shell

import (
	"bytes"
	"errors"
	"fmt"
	ctxpkg "github.com/kukichalang/kukicha/stdlib/ctx"
	kukistring "github.com/kukichalang/kukicha/stdlib/string"
	"os"
	"os/exec"
	"time"
)

//line stdlib/shell/shell.kuki:14
type Command struct {
	name    string
	args    []string
	dir     string
	timeout int
	env     map[string]string
	stdin   []byte
}

//line stdlib/shell/shell.kuki:23
type Result struct {
	Stdout   []byte
	Stderr   []byte
	ExitCode int
	Err      error
}

//line stdlib/shell/shell.kuki:35
func Run(cmd string) (string, error) {
//line stdlib/shell/shell.kuki:36
	fields := kukistring.Fields(cmd)
//line stdlib/shell/shell.kuki:37
	if len(fields) == 0 {
//line stdlib/shell/shell.kuki:38
		return "", errors.New("empty command")
	}
//line stdlib/shell/shell.kuki:39
	return Output(fields[0], fields[1:]...)
}

//line stdlib/shell/shell.kuki:45
func Output(name string, args ...string) (string, error) {
//line stdlib/shell/shell.kuki:46
	return New(name, args...).Output()
}

//line stdlib/shell/shell.kuki:51
func Capture(name string, args ...string) (string, string, error) {
//line stdlib/shell/shell.kuki:52
	return New(name, args...).Capture()
}

//line stdlib/shell/shell.kuki:57
func Check(name string, args ...string) error {
//line stdlib/shell/shell.kuki:58
	_, _, err := Capture(name, args...)
//line stdlib/shell/shell.kuki:59
	return err
}

//line stdlib/shell/shell.kuki:64
func Lines(name string, args ...string) ([]string, error) {
//line stdlib/shell/shell.kuki:65
	out, err_1 := Output(name, args...)
//line stdlib/shell/shell.kuki:65
	if err_1 != nil {
//line stdlib/shell/shell.kuki:65
		return []string{}, err_1
	}
//line stdlib/shell/shell.kuki:66
	lines := kukistring.Lines(out)
//line stdlib/shell/shell.kuki:67
	if (len(lines) > 0) && (lines[(len(lines)-1)] == "") {
//line stdlib/shell/shell.kuki:68
		lines = lines[:(len(lines) - 1)]
	}
//line stdlib/shell/shell.kuki:69
	return lines, nil
}

//line stdlib/shell/shell.kuki:79
func New(name string, args ...string) Command {
//line stdlib/shell/shell.kuki:80
	return Command{name: name, args: args, dir: "", timeout: 0, env: make(map[string]string), stdin: []byte{}}
}

//line stdlib/shell/shell.kuki:92
func Fatal(msg string) {
//line stdlib/shell/shell.kuki:93
	fmt.Fprintln(os.Stderr, msg)
//line stdlib/shell/shell.kuki:94
	os.Exit(1)
}

//line stdlib/shell/shell.kuki:98
func RequireCommand(name string) error {
//line stdlib/shell/shell.kuki:99
	if !Which(name) {
//line stdlib/shell/shell.kuki:100
		return fmt.Errorf("missing command: %v (install it, then run again)", name)
	}
//line stdlib/shell/shell.kuki:101
	return nil
}

//line stdlib/shell/shell.kuki:106
func Args(cmd Command, args ...string) Command {
//line stdlib/shell/shell.kuki:107
	cmd.args = append(cmd.args, args...)
//line stdlib/shell/shell.kuki:108
	return cmd
}

//line stdlib/shell/shell.kuki:114
func (cmd Command) Flag(name string, value string) Command {
//line stdlib/shell/shell.kuki:115
	cmd.args = append(cmd.args, name, value)
//line stdlib/shell/shell.kuki:116
	return cmd
}

//line stdlib/shell/shell.kuki:121
func (cmd Command) FlagIf(condition bool, args ...string) Command {
//line stdlib/shell/shell.kuki:122
	if condition {
//line stdlib/shell/shell.kuki:123
		cmd.args = append(cmd.args, args...)
	}
//line stdlib/shell/shell.kuki:124
	return cmd
}

//line stdlib/shell/shell.kuki:128
func (cmd Command) Dir(path string) Command {
//line stdlib/shell/shell.kuki:129
	cmd.dir = path
//line stdlib/shell/shell.kuki:130
	return cmd
}

//line stdlib/shell/shell.kuki:134
func (cmd Command) Env(key string, value string) Command {
//line stdlib/shell/shell.kuki:135
	cmd.env[key] = value
//line stdlib/shell/shell.kuki:136
	return cmd
}

//line stdlib/shell/shell.kuki:140
func (cmd Command) Timeout(seconds int) Command {
//line stdlib/shell/shell.kuki:141
	cmd.timeout = seconds
//line stdlib/shell/shell.kuki:142
	return cmd
}

//line stdlib/shell/shell.kuki:148
func (cmd Command) Stdin(data string) Command {
//line stdlib/shell/shell.kuki:149
	cmd.stdin = []byte(data)
//line stdlib/shell/shell.kuki:150
	return cmd
}

//line stdlib/shell/shell.kuki:155
func (cmd Command) StdinBytes(data []byte) Command {
//line stdlib/shell/shell.kuki:156
	cmd.stdin = data
//line stdlib/shell/shell.kuki:157
	return cmd
}

//line stdlib/shell/shell.kuki:161
func (cmd Command) Preview() string {
//line stdlib/shell/shell.kuki:162
	parts := []string{cmd.name}
//line stdlib/shell/shell.kuki:163
	parts = append(parts, cmd.args...)
//line stdlib/shell/shell.kuki:164
	return kukistring.Join(parts, " ")
}

//line stdlib/shell/shell.kuki:170
func (cmd Command) Execute() Result {
//line stdlib/shell/shell.kuki:173
	execCmd := exec.Command(cmd.name, cmd.args...)
//line stdlib/shell/shell.kuki:174
	if cmd.timeout > 0 {
//line stdlib/shell/shell.kuki:175
		h := ctxpkg.WithTimeout(ctxpkg.Background(), (time.Duration(cmd.timeout) * time.Second))
//line stdlib/shell/shell.kuki:176
		defer h.Cancel()
//line stdlib/shell/shell.kuki:177
		execCmd = exec.CommandContext(h.Ctx, cmd.name, cmd.args...)
	}
//line stdlib/shell/shell.kuki:180
	if cmd.dir != "" {
//line stdlib/shell/shell.kuki:181
		execCmd.Dir = cmd.dir
	}
//line stdlib/shell/shell.kuki:184
	if len(cmd.env) > 0 {
//line stdlib/shell/shell.kuki:185
		env := os.Environ()
//line stdlib/shell/shell.kuki:186
		for key, value := range cmd.env {
//line stdlib/shell/shell.kuki:187
			env = append(env, fmt.Sprintf("%v=%v", key, value))
		}
//line stdlib/shell/shell.kuki:188
		execCmd.Env = env
	}
//line stdlib/shell/shell.kuki:191
	if len(cmd.stdin) > 0 {
//line stdlib/shell/shell.kuki:192
		execCmd.Stdin = bytes.NewReader(cmd.stdin)
	}
//line stdlib/shell/shell.kuki:195
	stdoutBuf := bytes.Buffer{}
//line stdlib/shell/shell.kuki:196
	stderrBuf := bytes.Buffer{}
//line stdlib/shell/shell.kuki:197
	execCmd.Stdout = &stdoutBuf
//line stdlib/shell/shell.kuki:198
	execCmd.Stderr = &stderrBuf
//line stdlib/shell/shell.kuki:201
	err := execCmd.Run()
//line stdlib/shell/shell.kuki:204
	exitCode := getExitCode(err)
//line stdlib/shell/shell.kuki:206
	return Result{Stdout: stdoutBuf.Bytes(), Stderr: stderrBuf.Bytes(), ExitCode: exitCode, Err: err}
}

//line stdlib/shell/shell.kuki:212
func (cmd Command) Output() (string, error) {
//line stdlib/shell/shell.kuki:213
	return cmd.Execute().Require()
}

//line stdlib/shell/shell.kuki:220
func (cmd Command) Capture() (string, string, error) {
//line stdlib/shell/shell.kuki:221
	result := cmd.Execute()
//line stdlib/shell/shell.kuki:222
	stdout := string(result.Stdout)
//line stdlib/shell/shell.kuki:223
	stderr := string(result.Stderr)
//line stdlib/shell/shell.kuki:224
	if !result.Success() {
//line stdlib/shell/shell.kuki:225
		return stdout, stderr, fmt.Errorf("%v", stderr)
	}
//line stdlib/shell/shell.kuki:226
	return stdout, stderr, nil
}

//line stdlib/shell/shell.kuki:233
func (cmd Command) Check() error {
//line stdlib/shell/shell.kuki:234
	_, _, err := cmd.Capture()
//line stdlib/shell/shell.kuki:235
	return err
}

//line stdlib/shell/shell.kuki:238
func getExitCode(err error) int {
//line stdlib/shell/shell.kuki:239
	if err == nil {
//line stdlib/shell/shell.kuki:240
		return 0
	}
//line stdlib/shell/shell.kuki:241
	code := func() int {
		switch exitErr := err.(type) {
		case *exec.ExitError:
//line stdlib/shell/shell.kuki:243
			return exitErr.ExitCode()
		default:
//line stdlib/shell/shell.kuki:245
			return 1
		}
	}()
//line stdlib/shell/shell.kuki:247
	return code
}

//line stdlib/shell/shell.kuki:253
func (result Result) Success() bool {
//line stdlib/shell/shell.kuki:254
	return ((result.ExitCode == 0) && (result.Err == nil))
}

//line stdlib/shell/shell.kuki:259
func (result Result) Require() (string, error) {
//line stdlib/shell/shell.kuki:260
	if !result.Success() {
//line stdlib/shell/shell.kuki:261
		stderr := string(result.Stderr)
//line stdlib/shell/shell.kuki:262
		return "", fmt.Errorf("%v", stderr)
	}
//line stdlib/shell/shell.kuki:263
	return string(result.Stdout), nil
}

//line stdlib/shell/shell.kuki:270
func Which(name string) bool {
//line stdlib/shell/shell.kuki:271
	_, err := exec.LookPath(name)
//line stdlib/shell/shell.kuki:272
	return (err == nil)
}

//line stdlib/shell/shell.kuki:276
func Getenv(key string) string {
//line stdlib/shell/shell.kuki:277
	return os.Getenv(key)
}

//line stdlib/shell/shell.kuki:281
func Setenv(key string, value string) error {
//line stdlib/shell/shell.kuki:282
	return os.Setenv(key, value)
}

//line stdlib/shell/shell.kuki:286
func Unsetenv(key string) error {
//line stdlib/shell/shell.kuki:287
	return os.Unsetenv(key)
}

//line stdlib/shell/shell.kuki:292
func Environ() []string {
//line stdlib/shell/shell.kuki:293
	return os.Environ()
}
