// Generated by Kukicha (requires Go 1.26+)

package shell_test

import (
	"fmt"
	"github.com/kukichalang/kukicha/stdlib/shell"
	"github.com/kukichalang/kukicha/stdlib/slice"
	kukistring "github.com/kukichalang/kukicha/stdlib/string"
	"github.com/kukichalang/kukicha/stdlib/test"
	"testing"
)

//line stdlib/shell/shell_test.kuki:12
type ExecuteCase struct {
	name string
}

//line stdlib/shell/shell_test.kuki:15
func TestExecute(t *testing.T) {
//line stdlib/shell/shell_test.kuki:16
	cases := []ExecuteCase{ExecuteCase{name: "basic"}}
//line stdlib/shell/shell_test.kuki:18
	for _, tc := range cases {
//line stdlib/shell/shell_test.kuki:19
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/shell/shell_test.kuki:20
			cmd := shell.New("echo", "hello world")
//line stdlib/shell/shell_test.kuki:21
			result := cmd.Execute()
//line stdlib/shell/shell_test.kuki:23
			test.AssertTrue(t, result.Success())
//line stdlib/shell/shell_test.kuki:25
			output := string(result.Stdout)
//line stdlib/shell/shell_test.kuki:26
			expected := "hello world\n"
//line stdlib/shell/shell_test.kuki:27
			test.AssertEqual(t, output, expected)
		})
	}
}

//line stdlib/shell/shell_test.kuki:31
type ExecuteWithDirCase struct {
	name string
}

//line stdlib/shell/shell_test.kuki:34
func TestExecuteWithDir(t *testing.T) {
//line stdlib/shell/shell_test.kuki:35
	cases := []ExecuteWithDirCase{ExecuteWithDirCase{name: "with dir"}}
//line stdlib/shell/shell_test.kuki:37
	for _, tc := range cases {
//line stdlib/shell/shell_test.kuki:38
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/shell/shell_test.kuki:39
			cmd := shell.New("pwd").Dir("/tmp")
//line stdlib/shell/shell_test.kuki:40
			result := cmd.Execute()
//line stdlib/shell/shell_test.kuki:42
			test.AssertTrue(t, result.Success())
//line stdlib/shell/shell_test.kuki:44
			output := string(result.Stdout)
//line stdlib/shell/shell_test.kuki:45
			test.AssertTrue(t, kukistring.Contains(output, "tmp"))
		})
	}
}

//line stdlib/shell/shell_test.kuki:49
type ExecuteWithEnvCase struct {
	name string
}

//line stdlib/shell/shell_test.kuki:52
func TestExecuteWithEnv(t *testing.T) {
//line stdlib/shell/shell_test.kuki:53
	cases := []ExecuteWithEnvCase{ExecuteWithEnvCase{name: "with env"}}
//line stdlib/shell/shell_test.kuki:55
	for _, tc := range cases {
//line stdlib/shell/shell_test.kuki:56
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/shell/shell_test.kuki:57
			cmd := shell.New("sh", "-c", "echo $TEST_VAR").Env("TEST_VAR", "hello")
//line stdlib/shell/shell_test.kuki:58
			result := cmd.Execute()
//line stdlib/shell/shell_test.kuki:60
			test.AssertTrue(t, result.Success())
//line stdlib/shell/shell_test.kuki:62
			output := string(result.Stdout)
//line stdlib/shell/shell_test.kuki:63
			test.AssertTrue(t, kukistring.Contains(output, "hello"))
		})
	}
}

//line stdlib/shell/shell_test.kuki:67
type ExecuteFailedCase struct {
	name string
}

//line stdlib/shell/shell_test.kuki:70
func TestExecuteFailed(t *testing.T) {
//line stdlib/shell/shell_test.kuki:71
	cases := []ExecuteFailedCase{ExecuteFailedCase{name: "failed"}}
//line stdlib/shell/shell_test.kuki:73
	for _, tc := range cases {
//line stdlib/shell/shell_test.kuki:74
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/shell/shell_test.kuki:75
			cmd := shell.New("false")
//line stdlib/shell/shell_test.kuki:76
			result := cmd.Execute()
//line stdlib/shell/shell_test.kuki:78
			test.AssertFalse(t, result.Success())
//line stdlib/shell/shell_test.kuki:80
			exitCode := result.ExitCode
//line stdlib/shell/shell_test.kuki:81
			if exitCode == 0 {
//line stdlib/shell/shell_test.kuki:82
				t.Errorf("Expected non-zero exit code, got %v", exitCode)
			}
		})
	}
}

//line stdlib/shell/shell_test.kuki:86
type WhichCase struct {
	name string
}

//line stdlib/shell/shell_test.kuki:89
func TestWhich(t *testing.T) {
//line stdlib/shell/shell_test.kuki:90
	cases := []WhichCase{WhichCase{name: "which"}}
//line stdlib/shell/shell_test.kuki:92
	for _, tc := range cases {
//line stdlib/shell/shell_test.kuki:93
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/shell/shell_test.kuki:94
			test.AssertTrue(t, shell.Which("ls"))
//line stdlib/shell/shell_test.kuki:95
			test.AssertFalse(t, shell.Which("nonexistent-command-xyz"))
		})
	}
}

//line stdlib/shell/shell_test.kuki:99
type ArgsCase struct {
	name     string
	initial  []string
	extra    []string
	expected string
}

//line stdlib/shell/shell_test.kuki:105
func TestArgs(t *testing.T) {
//line stdlib/shell/shell_test.kuki:106
	cases := []ArgsCase{ArgsCase{name: "append single arg", initial: []string{"--repo", "foo"}, extra: []string{"--verbose"}, expected: "hello world\n"}, ArgsCase{name: "append multiple args", initial: []string{}, extra: []string{"--foo", "bar"}, expected: "hello world\n"}}
//line stdlib/shell/shell_test.kuki:121
	for _, tc := range cases {
//line stdlib/shell/shell_test.kuki:122
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/shell/shell_test.kuki:123
			cmd := shell.New("echo", tc.initial...)
//line stdlib/shell/shell_test.kuki:124
			cmd = shell.Args(cmd, tc.extra...)
//line stdlib/shell/shell_test.kuki:125
			var allArgs []string
//line stdlib/shell/shell_test.kuki:126
			allArgs = append(allArgs, tc.initial...)
//line stdlib/shell/shell_test.kuki:127
			allArgs = append(allArgs, tc.extra...)
//line stdlib/shell/shell_test.kuki:128
			result := cmd.Execute()
//line stdlib/shell/shell_test.kuki:129
			test.AssertTrue(t, result.Success())
		})
	}
}

//line stdlib/shell/shell_test.kuki:133
type FlagIfCase struct {
	name           string
	condition      bool
	flag           string
	expectContains string
	expectMissing  string
}

//line stdlib/shell/shell_test.kuki:140
func TestFlagIf(t *testing.T) {
//line stdlib/shell/shell_test.kuki:141
	cases := []FlagIfCase{FlagIfCase{name: "condition true adds flag", condition: true, flag: "--verbose", expectContains: "--verbose", expectMissing: ""}, FlagIfCase{name: "condition false skips flag", condition: false, flag: "--verbose", expectContains: "", expectMissing: "--verbose"}}
//line stdlib/shell/shell_test.kuki:158
	for _, tc := range cases {
//line stdlib/shell/shell_test.kuki:159
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/shell/shell_test.kuki:160
			cmd := shell.New("echo", "hello").FlagIf(tc.condition, tc.flag)
//line stdlib/shell/shell_test.kuki:162
			preview := cmd.Preview()
//line stdlib/shell/shell_test.kuki:163
			if tc.expectContains != "" {
//line stdlib/shell/shell_test.kuki:164
				test.AssertTrue(t, kukistring.Contains(preview, tc.expectContains))
			}
//line stdlib/shell/shell_test.kuki:165
			if tc.expectMissing != "" {
//line stdlib/shell/shell_test.kuki:166
				test.AssertFalse(t, kukistring.Contains(preview, tc.expectMissing))
			}
		})
	}
}

//line stdlib/shell/shell_test.kuki:170
type FlagIfMultiArgCase struct {
	name string
}

//line stdlib/shell/shell_test.kuki:173
func TestFlagIfMultiArg(t *testing.T) {
//line stdlib/shell/shell_test.kuki:174
	cases := []FlagIfMultiArgCase{FlagIfMultiArgCase{name: "multi-arg flag"}}
//line stdlib/shell/shell_test.kuki:176
	for _, tc := range cases {
//line stdlib/shell/shell_test.kuki:177
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/shell/shell_test.kuki:178
			cmd := shell.New("gh", "release", "create").FlagIf(true, "--target", "main").FlagIf(false, "--draft")
//line stdlib/shell/shell_test.kuki:182
			preview := cmd.Preview()
//line stdlib/shell/shell_test.kuki:183
			test.AssertTrue(t, kukistring.Contains(preview, "--target main"))
//line stdlib/shell/shell_test.kuki:184
			test.AssertFalse(t, kukistring.Contains(preview, "--draft"))
		})
	}
}

//line stdlib/shell/shell_test.kuki:188
type FlagCase struct {
	name string
}

//line stdlib/shell/shell_test.kuki:191
func TestFlag(t *testing.T) {
//line stdlib/shell/shell_test.kuki:192
	cases := []FlagCase{FlagCase{name: "two-arg flag"}}
//line stdlib/shell/shell_test.kuki:194
	for _, tc := range cases {
//line stdlib/shell/shell_test.kuki:195
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/shell/shell_test.kuki:196
			cmd := shell.New("aws", "s3api", "create-bucket").Flag("--bucket", "my-bucket").Flag("--region", "us-west-2")
//line stdlib/shell/shell_test.kuki:200
			preview := cmd.Preview()
//line stdlib/shell/shell_test.kuki:201
			test.AssertEqual(t, preview, "aws s3api create-bucket --bucket my-bucket --region us-west-2")
		})
	}
}

//line stdlib/shell/shell_test.kuki:209
type RequireCommandCase struct {
	name string
}

//line stdlib/shell/shell_test.kuki:212
func TestRequireCommand(t *testing.T) {
//line stdlib/shell/shell_test.kuki:213
	cases := []RequireCommandCase{RequireCommandCase{name: "require"}}
//line stdlib/shell/shell_test.kuki:215
	for _, tc := range cases {
//line stdlib/shell/shell_test.kuki:216
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/shell/shell_test.kuki:217
			err := shell.RequireCommand("ls")
//line stdlib/shell/shell_test.kuki:218
			test.AssertNoError(t, err)
//line stdlib/shell/shell_test.kuki:220
			err = shell.RequireCommand("nonexistent-command-xyz")
//line stdlib/shell/shell_test.kuki:221
			test.AssertError(t, err)
		})
	}
}

//line stdlib/shell/shell_test.kuki:225
type PreviewCase struct {
	name     string
	cmdName  string
	args     []string
	expected string
}

//line stdlib/shell/shell_test.kuki:231
func TestPreview(t *testing.T) {
//line stdlib/shell/shell_test.kuki:232
	cases := []PreviewCase{PreviewCase{name: "simple command", cmdName: "echo", args: []string{"hello"}, expected: "echo hello"}, PreviewCase{name: "no args", cmdName: "ls", args: []string{}, expected: "ls"}, PreviewCase{name: "multiple args", cmdName: "gh", args: []string{"release", "create", "v1.0.0", "--repo", "org/repo"}, expected: "gh release create v1.0.0 --repo org/repo"}}
//line stdlib/shell/shell_test.kuki:248
	for _, tc := range cases {
//line stdlib/shell/shell_test.kuki:249
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/shell/shell_test.kuki:250
			cmd := shell.New(tc.cmdName, tc.args...)
//line stdlib/shell/shell_test.kuki:251
			got := cmd.Preview()
//line stdlib/shell/shell_test.kuki:252
			test.AssertEqual(t, got, tc.expected)
		})
	}
}

//line stdlib/shell/shell_test.kuki:256
type LinesCase struct {
	name      string
	cmd       string
	cmdArgs   []string
	wantLines []string
	wantErr   bool
}

//line stdlib/shell/shell_test.kuki:263
func TestLines(t *testing.T) {
//line stdlib/shell/shell_test.kuki:264
	cases := []LinesCase{LinesCase{name: "single line strips trailing newline", cmd: "echo", cmdArgs: []string{"hello"}, wantLines: []string{"hello"}, wantErr: false}, LinesCase{name: "multiple lines", cmd: "sh", cmdArgs: []string{"-c", "printf 'a\\nb\\nc'"}, wantLines: []string{"a", "b", "c"}, wantErr: false}, LinesCase{name: "failing command returns error", cmd: "false", cmdArgs: []string{}, wantLines: []string{}, wantErr: true}}
//line stdlib/shell/shell_test.kuki:288
	for _, tc := range cases {
//line stdlib/shell/shell_test.kuki:289
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/shell/shell_test.kuki:290
			lines, err := shell.Lines(tc.cmd, tc.cmdArgs...)
//line stdlib/shell/shell_test.kuki:291
			if tc.wantErr {
//line stdlib/shell/shell_test.kuki:292
				test.AssertError(t, err)
			} else {
//line stdlib/shell/shell_test.kuki:294
				test.AssertNoError(t, err)
//line stdlib/shell/shell_test.kuki:295
				test.AssertEqual(t, len(lines), len(tc.wantLines))
//line stdlib/shell/shell_test.kuki:296
				for i, want := range tc.wantLines {
//line stdlib/shell/shell_test.kuki:297
					test.AssertEqual(t, lines[i], want)
				}
			}
		})
	}
}

//line stdlib/shell/shell_test.kuki:301
type RequireCase struct {
	name     string
	exitCode int
	stdout   string
	stderr   string
	wantOut  string
	wantErr  bool
}

//line stdlib/shell/shell_test.kuki:309
func TestRequire(t *testing.T) {
//line stdlib/shell/shell_test.kuki:310
	cases := []RequireCase{RequireCase{name: "success returns stdout", exitCode: 0, stdout: "ok output", stderr: "", wantOut: "ok output", wantErr: false}, RequireCase{name: "failure returns error with stderr", exitCode: 1, stdout: "", stderr: "build failed", wantOut: "", wantErr: true}}
//line stdlib/shell/shell_test.kuki:329
	for _, tc := range cases {
//line stdlib/shell/shell_test.kuki:330
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/shell/shell_test.kuki:331
			result := shell.Result{Stdout: []byte(tc.stdout), Stderr: []byte(tc.stderr), ExitCode: tc.exitCode, Err: nil}
//line stdlib/shell/shell_test.kuki:337
			if tc.exitCode != 0 {
//line stdlib/shell/shell_test.kuki:338
				result.Err = fmt.Errorf("exit status %v", tc.exitCode)
			}
//line stdlib/shell/shell_test.kuki:339
			out, err := result.Require()
//line stdlib/shell/shell_test.kuki:340
			if tc.wantErr {
//line stdlib/shell/shell_test.kuki:341
				test.AssertError(t, err)
//line stdlib/shell/shell_test.kuki:342
				test.AssertEqual(t, out, "")
			} else {
//line stdlib/shell/shell_test.kuki:344
				test.AssertNoError(t, err)
//line stdlib/shell/shell_test.kuki:345
				test.AssertEqual(t, out, tc.wantOut)
			}
		})
	}
}

//line stdlib/shell/shell_test.kuki:349
type EnvCase struct {
	name string
}

//line stdlib/shell/shell_test.kuki:352
func TestEnv(t *testing.T) {
//line stdlib/shell/shell_test.kuki:353
	cases := []EnvCase{EnvCase{name: "env operations"}}
//line stdlib/shell/shell_test.kuki:355
	for _, tc := range cases {
//line stdlib/shell/shell_test.kuki:356
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/shell/shell_test.kuki:357
			key := "KUKICHA_TEST_VAR"
//line stdlib/shell/shell_test.kuki:358
			val := "test_value"
//line stdlib/shell/shell_test.kuki:360
			err := shell.Setenv(key, val)
//line stdlib/shell/shell_test.kuki:361
			test.AssertNoError(t, err)
//line stdlib/shell/shell_test.kuki:363
			got := shell.Getenv(key)
//line stdlib/shell/shell_test.kuki:364
			test.AssertEqual(t, got, val)
//line stdlib/shell/shell_test.kuki:366
			envs := shell.Environ()
//line stdlib/shell/shell_test.kuki:367
			test.AssertTrue(t, slice.Contains(envs, fmt.Sprintf("%v=%v", key, val)))
//line stdlib/shell/shell_test.kuki:369
			shell.Unsetenv(key)
//line stdlib/shell/shell_test.kuki:370
			test.AssertEqual(t, shell.Getenv(key), "")
		})
	}
}

//line stdlib/shell/shell_test.kuki:376
type StdinCase struct {
	name  string
	input string
}

//line stdlib/shell/shell_test.kuki:380
func TestStdin(t *testing.T) {
//line stdlib/shell/shell_test.kuki:381
	cases := []StdinCase{StdinCase{name: "string input", input: "hello via stdin\n"}, StdinCase{name: "multiline input", input: "line1\nline2\nline3\n"}, StdinCase{name: "empty stays empty", input: ""}}
//line stdlib/shell/shell_test.kuki:387
	for _, tc := range cases {
//line stdlib/shell/shell_test.kuki:388
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/shell/shell_test.kuki:389
			out, err := shell.New("cat").Stdin(tc.input).Output()
//line stdlib/shell/shell_test.kuki:390
			test.AssertNoError(t, err)
//line stdlib/shell/shell_test.kuki:391
			test.AssertEqual(t, out, tc.input)
		})
	}
}

//line stdlib/shell/shell_test.kuki:395
func TestStdinBytes(t *testing.T) {
//line stdlib/shell/shell_test.kuki:396
	payload := []byte("raw-bytes")
//line stdlib/shell/shell_test.kuki:397
	out, err := shell.New("cat").StdinBytes(payload).Output()
//line stdlib/shell/shell_test.kuki:398
	test.AssertNoError(t, err)
//line stdlib/shell/shell_test.kuki:399
	test.AssertEqual(t, out, "raw-bytes")
}

//line stdlib/shell/shell_test.kuki:402
type CaptureCase struct {
	name       string
	cmd        string
	cmdArgs    []string
	wantStdout string
	wantStderr string
	wantErr    bool
}

//line stdlib/shell/shell_test.kuki:410
func TestCapture(t *testing.T) {
//line stdlib/shell/shell_test.kuki:411
	cases := []CaptureCase{CaptureCase{name: "success returns stdout and empty stderr", cmd: "echo", cmdArgs: []string{"hello"}, wantStdout: "hello\n", wantStderr: "", wantErr: false}, CaptureCase{name: "failure returns both streams and error", cmd: "sh", cmdArgs: []string{"-c", "echo oops >&2; exit 1"}, wantStdout: "", wantStderr: "oops\n", wantErr: true}}
//line stdlib/shell/shell_test.kuki:430
	for _, tc := range cases {
//line stdlib/shell/shell_test.kuki:431
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/shell/shell_test.kuki:432
			out, errOut, err := shell.New(tc.cmd, tc.cmdArgs...).Capture()
//line stdlib/shell/shell_test.kuki:433
			if tc.wantErr {
//line stdlib/shell/shell_test.kuki:434
				test.AssertError(t, err)
			} else {
//line stdlib/shell/shell_test.kuki:436
				test.AssertNoError(t, err)
			}
//line stdlib/shell/shell_test.kuki:437
			test.AssertEqual(t, out, tc.wantStdout)
//line stdlib/shell/shell_test.kuki:438
			test.AssertEqual(t, errOut, tc.wantStderr)
		})
	}
}

//line stdlib/shell/shell_test.kuki:441
func TestCaptureTopLevel(t *testing.T) {
//line stdlib/shell/shell_test.kuki:442
	out, errOut, err := shell.Capture("echo", "hello")
//line stdlib/shell/shell_test.kuki:443
	test.AssertNoError(t, err)
//line stdlib/shell/shell_test.kuki:444
	test.AssertEqual(t, out, "hello\n")
//line stdlib/shell/shell_test.kuki:445
	test.AssertEqual(t, errOut, "")
}

//line stdlib/shell/shell_test.kuki:448
type CheckCase struct {
	name    string
	cmd     string
	cmdArgs []string
	wantErr bool
}

//line stdlib/shell/shell_test.kuki:454
func TestCheck(t *testing.T) {
//line stdlib/shell/shell_test.kuki:455
	cases := []CheckCase{CheckCase{name: "success returns nil", cmd: "true", cmdArgs: []string{}, wantErr: false}, CheckCase{name: "failure returns error", cmd: "false", cmdArgs: []string{}, wantErr: true}, CheckCase{name: "missing binary returns error", cmd: "nonexistent-binary-xyz", cmdArgs: []string{}, wantErr: true}}
//line stdlib/shell/shell_test.kuki:476
	for _, tc := range cases {
//line stdlib/shell/shell_test.kuki:477
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/shell/shell_test.kuki:478
			err := shell.New(tc.cmd, tc.cmdArgs...).Check()
//line stdlib/shell/shell_test.kuki:479
			if tc.wantErr {
//line stdlib/shell/shell_test.kuki:480
				test.AssertError(t, err)
			} else {
//line stdlib/shell/shell_test.kuki:482
				test.AssertNoError(t, err)
			}
		})
	}
}

//line stdlib/shell/shell_test.kuki:485
func TestCheckTopLevel(t *testing.T) {
//line stdlib/shell/shell_test.kuki:486
	test.AssertNoError(t, shell.Check("true"))
//line stdlib/shell/shell_test.kuki:487
	test.AssertError(t, shell.Check("false"))
}
