// Generated by Kukicha (requires Go 1.26+)

package slice

import (
	"cmp"
	"errors"
	"fmt"
	"slices"
)

//line stdlib/slice/slice.kuki:9
func Take[T any](items []T, n int) []T {
//line stdlib/slice/slice.kuki:10
	if n <= 0 {
//line stdlib/slice/slice.kuki:11
		return make([]T, 0)
	}
//line stdlib/slice/slice.kuki:12
	if n >= len(items) {
//line stdlib/slice/slice.kuki:13
		return items
	}
//line stdlib/slice/slice.kuki:14
	return items[:n]
}

//line stdlib/slice/slice.kuki:18
func TakeLast[T any](items []T, n int) []T {
//line stdlib/slice/slice.kuki:19
	length := len(items)
//line stdlib/slice/slice.kuki:20
	if n <= 0 {
//line stdlib/slice/slice.kuki:21
		return make([]T, 0)
	}
//line stdlib/slice/slice.kuki:22
	if n >= length {
//line stdlib/slice/slice.kuki:23
		return items
	}
//line stdlib/slice/slice.kuki:24
	return items[(length - n):]
}

//line stdlib/slice/slice.kuki:28
func Skip[T any](items []T, n int) []T {
//line stdlib/slice/slice.kuki:29
	if n <= 0 {
//line stdlib/slice/slice.kuki:30
		return items
	}
//line stdlib/slice/slice.kuki:31
	if n >= len(items) {
//line stdlib/slice/slice.kuki:32
		return make([]T, 0)
	}
//line stdlib/slice/slice.kuki:33
	return items[n:]
}

//line stdlib/slice/slice.kuki:37
func SkipLast[T any](items []T, n int) []T {
//line stdlib/slice/slice.kuki:38
	length := len(items)
//line stdlib/slice/slice.kuki:39
	if n <= 0 {
//line stdlib/slice/slice.kuki:40
		return items
	}
//line stdlib/slice/slice.kuki:41
	if n >= length {
//line stdlib/slice/slice.kuki:42
		return make([]T, 0)
	}
//line stdlib/slice/slice.kuki:43
	return items[:(length - n)]
}

//line stdlib/slice/slice.kuki:47
func Reverse[T any](items []T) []T {
//line stdlib/slice/slice.kuki:48
	result := slices.Clone(items)
//line stdlib/slice/slice.kuki:49
	slices.Reverse(result)
//line stdlib/slice/slice.kuki:50
	return result
}

//line stdlib/slice/slice.kuki:55
func Unique[K comparable](items []K) []K {
//line stdlib/slice/slice.kuki:56
	if len(items) == 0 {
//line stdlib/slice/slice.kuki:57
		return items
	}
//line stdlib/slice/slice.kuki:59
	seen := make(map[K]bool)
//line stdlib/slice/slice.kuki:60
	result := make([]K, 0)
//line stdlib/slice/slice.kuki:62
	for _, item := range items {
//line stdlib/slice/slice.kuki:63
		if !seen[item] {
//line stdlib/slice/slice.kuki:64
			seen[item] = true
//line stdlib/slice/slice.kuki:65
			result = append(result, item)
		}
	}
//line stdlib/slice/slice.kuki:67
	return result
}

//line stdlib/slice/slice.kuki:71
func Chunk[T any](items []T, size int) [][]T {
//line stdlib/slice/slice.kuki:72
	if size <= 0 {
//line stdlib/slice/slice.kuki:73
		return make([][]T, 0)
	}
//line stdlib/slice/slice.kuki:75
	result := make([][]T, 0)
//line stdlib/slice/slice.kuki:76
	length := len(items)
//line stdlib/slice/slice.kuki:77
	i := 0
//line stdlib/slice/slice.kuki:79
	for i < length {
//line stdlib/slice/slice.kuki:80
		end := min((i + size), length)
//line stdlib/slice/slice.kuki:81
		chunk := items[i:end]
//line stdlib/slice/slice.kuki:82
		result = append(result, chunk)
//line stdlib/slice/slice.kuki:83
		i = (i + size)
	}
//line stdlib/slice/slice.kuki:85
	return result
}

//line stdlib/slice/slice.kuki:89
func Contains[K comparable](items []K, value K) bool {
//line stdlib/slice/slice.kuki:90
	return slices.Contains(items, value)
}

//line stdlib/slice/slice.kuki:95
func IndexOf[K comparable](items []K, value K) int {
//line stdlib/slice/slice.kuki:96
	return slices.Index(items, value)
}

//line stdlib/slice/slice.kuki:100
func Concat[T any](slices [][]T) []T {
//line stdlib/slice/slice.kuki:101
	totalLength := 0
//line stdlib/slice/slice.kuki:102
	for _, slice := range slices {
//line stdlib/slice/slice.kuki:103
		totalLength = (totalLength + len(slice))
	}
//line stdlib/slice/slice.kuki:105
	result := make([]T, 0, totalLength)
//line stdlib/slice/slice.kuki:106
	for _, slice := range slices {
//line stdlib/slice/slice.kuki:107
		for _, item := range slice {
//line stdlib/slice/slice.kuki:108
			result = append(result, item)
		}
	}
//line stdlib/slice/slice.kuki:110
	return result
}

//line stdlib/slice/slice.kuki:114
func Filter[T any](items []T, predicate func(T) bool) []T {
//line stdlib/slice/slice.kuki:115
	result := make([]T, 0)
//line stdlib/slice/slice.kuki:116
	for _, item := range items {
//line stdlib/slice/slice.kuki:117
		if predicate(item) {
//line stdlib/slice/slice.kuki:118
			result = append(result, item)
		}
	}
//line stdlib/slice/slice.kuki:119
	return result
}

//line stdlib/slice/slice.kuki:124
func Reject[T any](items []T, predicate func(T) bool) []T {
//line stdlib/slice/slice.kuki:125
	result := make([]T, 0)
//line stdlib/slice/slice.kuki:126
	for _, item := range items {
//line stdlib/slice/slice.kuki:127
		if !predicate(item) {
//line stdlib/slice/slice.kuki:128
			result = append(result, item)
		}
	}
//line stdlib/slice/slice.kuki:129
	return result
}

//line stdlib/slice/slice.kuki:134
func Partition[T any](items []T, predicate func(T) bool) ([]T, []T) {
//line stdlib/slice/slice.kuki:135
	matches := make([]T, 0)
//line stdlib/slice/slice.kuki:136
	rest := make([]T, 0)
//line stdlib/slice/slice.kuki:137
	for _, item := range items {
//line stdlib/slice/slice.kuki:138
		if predicate(item) {
//line stdlib/slice/slice.kuki:139
			matches = append(matches, item)
		} else {
//line stdlib/slice/slice.kuki:141
			rest = append(rest, item)
		}
	}
//line stdlib/slice/slice.kuki:142
	return matches, rest
}

//line stdlib/slice/slice.kuki:146
func Map[T any, R any](items []T, transform func(T) R) []R {
//line stdlib/slice/slice.kuki:147
	out := make([]R, len(items))
//line stdlib/slice/slice.kuki:148
	for i, item := range items {
//line stdlib/slice/slice.kuki:149
		out[i] = transform(item)
	}
//line stdlib/slice/slice.kuki:150
	return out
}

//line stdlib/slice/slice.kuki:159
func GroupBy[T any, K comparable](items []T, keyFunc func(T) K) map[K][]T {
//line stdlib/slice/slice.kuki:160
	result := make(map[K][]T)
//line stdlib/slice/slice.kuki:161
	for _, item := range items {
//line stdlib/slice/slice.kuki:162
		k := keyFunc(item)
//line stdlib/slice/slice.kuki:163
		result[k] = append(result[k], item)
	}
//line stdlib/slice/slice.kuki:164
	return result
}

//line stdlib/slice/slice.kuki:172
func Get[T any](items []T, index int) (T, error) {
//line stdlib/slice/slice.kuki:173
	length := len(items)
//line stdlib/slice/slice.kuki:174
	if length == 0 {
//line stdlib/slice/slice.kuki:175
		var _zero0 T
		return _zero0, errors.New("slice is empty")
	}
//line stdlib/slice/slice.kuki:178
	actualIndex := index
//line stdlib/slice/slice.kuki:179
	if index < 0 {
//line stdlib/slice/slice.kuki:180
		actualIndex = (length + index)
	}
//line stdlib/slice/slice.kuki:182
	if (actualIndex < 0) || (actualIndex >= length) {
//line stdlib/slice/slice.kuki:183
		var _zero0 T
		return _zero0, fmt.Errorf("index %v out of bounds for slice of length %v", index, length)
	}
//line stdlib/slice/slice.kuki:185
	return items[actualIndex], nil
}

//line stdlib/slice/slice.kuki:191
func GetOr[T any](items []T, index int, defaultValue T) T {
//line stdlib/slice/slice.kuki:192
	length := len(items)
//line stdlib/slice/slice.kuki:193
	if length == 0 {
//line stdlib/slice/slice.kuki:194
		return defaultValue
	}
//line stdlib/slice/slice.kuki:197
	actualIndex := index
//line stdlib/slice/slice.kuki:198
	if index < 0 {
//line stdlib/slice/slice.kuki:199
		actualIndex = (length + index)
	}
//line stdlib/slice/slice.kuki:201
	if (actualIndex < 0) || (actualIndex >= length) {
//line stdlib/slice/slice.kuki:202
		return defaultValue
	}
//line stdlib/slice/slice.kuki:204
	return items[actualIndex]
}

//line stdlib/slice/slice.kuki:208
func First[T any](items []T) (T, error) {
//line stdlib/slice/slice.kuki:209
	if len(items) == 0 {
//line stdlib/slice/slice.kuki:210
		var _zero0 T
		return _zero0, errors.New("slice is empty")
	}
//line stdlib/slice/slice.kuki:211
	return items[0], nil
}

//line stdlib/slice/slice.kuki:216
func FirstOr[T any](items []T, defaultValue T) T {
//line stdlib/slice/slice.kuki:217
	if len(items) == 0 {
//line stdlib/slice/slice.kuki:218
		return defaultValue
	}
//line stdlib/slice/slice.kuki:219
	return items[0]
}

//line stdlib/slice/slice.kuki:223
func Last[T any](items []T) (T, error) {
//line stdlib/slice/slice.kuki:224
	if len(items) == 0 {
//line stdlib/slice/slice.kuki:225
		var _zero0 T
		return _zero0, errors.New("slice is empty")
	}
//line stdlib/slice/slice.kuki:226
	return items[(len(items) - 1)], nil
}

//line stdlib/slice/slice.kuki:231
func LastOr[T any](items []T, defaultValue T) T {
//line stdlib/slice/slice.kuki:232
	if len(items) == 0 {
//line stdlib/slice/slice.kuki:233
		return defaultValue
	}
//line stdlib/slice/slice.kuki:234
	return items[(len(items) - 1)]
}

//line stdlib/slice/slice.kuki:238
func Find[T any](items []T, predicate func(T) bool) (T, error) {
//line stdlib/slice/slice.kuki:239
	for _, item := range items {
//line stdlib/slice/slice.kuki:240
		if predicate(item) {
//line stdlib/slice/slice.kuki:241
			return item, nil
		}
	}
//line stdlib/slice/slice.kuki:242
	var _zero0 T
	return _zero0, errors.New("no matching element found")
}

//line stdlib/slice/slice.kuki:247
func FindOr[T any](items []T, predicate func(T) bool, defaultValue T) T {
//line stdlib/slice/slice.kuki:248
	for _, item := range items {
//line stdlib/slice/slice.kuki:249
		if predicate(item) {
//line stdlib/slice/slice.kuki:250
			return item
		}
	}
//line stdlib/slice/slice.kuki:251
	return defaultValue
}

//line stdlib/slice/slice.kuki:256
func FindIndex[T any](items []T, predicate func(T) bool) int {
//line stdlib/slice/slice.kuki:257
	for i, item := range items {
//line stdlib/slice/slice.kuki:258
		if predicate(item) {
//line stdlib/slice/slice.kuki:259
			return i
		}
	}
//line stdlib/slice/slice.kuki:260
	return -1
}

//line stdlib/slice/slice.kuki:264
func FindLast[T any](items []T, predicate func(T) bool) (T, error) {
//line stdlib/slice/slice.kuki:265
	if len(items) == 0 {
//line stdlib/slice/slice.kuki:266
		var _zero0 T
		return _zero0, errors.New("no matching element found")
	}
//line stdlib/slice/slice.kuki:267
	{
		_iStart, _iEnd, _iStep := (len(items) - 1), 0, 1
		if _iStart > _iEnd {
			_iStep = -1
		}
		for i := _iStart; i != _iEnd+_iStep; i += _iStep {
//line stdlib/slice/slice.kuki:268
			if predicate(items[i]) {
//line stdlib/slice/slice.kuki:269
				return items[i], nil
			}
		}
	}
//line stdlib/slice/slice.kuki:270
	var _zero0 T
	return _zero0, errors.New("no matching element found")
}

//line stdlib/slice/slice.kuki:274
func FindLastOr[T any](items []T, predicate func(T) bool, defaultValue T) T {
//line stdlib/slice/slice.kuki:275
	if len(items) == 0 {
//line stdlib/slice/slice.kuki:276
		return defaultValue
	}
//line stdlib/slice/slice.kuki:277
	{
		_iStart, _iEnd, _iStep := (len(items) - 1), 0, 1
		if _iStart > _iEnd {
			_iStep = -1
		}
		for i := _iStart; i != _iEnd+_iStep; i += _iStep {
//line stdlib/slice/slice.kuki:278
			if predicate(items[i]) {
//line stdlib/slice/slice.kuki:279
				return items[i]
			}
		}
	}
//line stdlib/slice/slice.kuki:280
	return defaultValue
}

//line stdlib/slice/slice.kuki:285
func PopLast[T any](items []T) (T, []T, error) {
//line stdlib/slice/slice.kuki:286
	if len(items) == 0 {
//line stdlib/slice/slice.kuki:287
		var _zero0 T
		return _zero0, items, errors.New("cannot pop from empty slice")
	}
//line stdlib/slice/slice.kuki:288
	return items[(len(items) - 1)], items[:(len(items) - 1)], nil
}

//line stdlib/slice/slice.kuki:293
func PopFirst[T any](items []T) (T, []T, error) {
//line stdlib/slice/slice.kuki:294
	if len(items) == 0 {
//line stdlib/slice/slice.kuki:295
		var _zero0 T
		return _zero0, items, errors.New("cannot pop from empty slice")
	}
//line stdlib/slice/slice.kuki:296
	return items[0], items[1:], nil
}

//line stdlib/slice/slice.kuki:305
func Sum[K cmp.Ordered](items []K) K {
//line stdlib/slice/slice.kuki:306
	var total K
//line stdlib/slice/slice.kuki:307
	for _, item := range items {
//line stdlib/slice/slice.kuki:308
		total = (total + item)
	}
//line stdlib/slice/slice.kuki:309
	return total
}

//line stdlib/slice/slice.kuki:313
func Min[K cmp.Ordered](items []K) (K, error) {
//line stdlib/slice/slice.kuki:314
	if len(items) == 0 {
//line stdlib/slice/slice.kuki:315
		var _zero0 K
		return _zero0, errors.New("cannot take min of empty slice")
	}
//line stdlib/slice/slice.kuki:316
	best := items[0]
//line stdlib/slice/slice.kuki:317
	for _, item := range items[1:] {
//line stdlib/slice/slice.kuki:318
		if item < best {
//line stdlib/slice/slice.kuki:319
			best = item
		}
	}
//line stdlib/slice/slice.kuki:320
	return best, nil
}

//line stdlib/slice/slice.kuki:324
func Max[K cmp.Ordered](items []K) (K, error) {
//line stdlib/slice/slice.kuki:325
	if len(items) == 0 {
//line stdlib/slice/slice.kuki:326
		var _zero0 K
		return _zero0, errors.New("cannot take max of empty slice")
	}
//line stdlib/slice/slice.kuki:327
	best := items[0]
//line stdlib/slice/slice.kuki:328
	for _, item := range items[1:] {
//line stdlib/slice/slice.kuki:329
		if item > best {
//line stdlib/slice/slice.kuki:330
			best = item
		}
	}
//line stdlib/slice/slice.kuki:331
	return best, nil
}

//line stdlib/slice/slice.kuki:336
func Average(items []float64) (float64, error) {
//line stdlib/slice/slice.kuki:337
	if len(items) == 0 {
//line stdlib/slice/slice.kuki:338
		return 0.0, errors.New("cannot take average of empty slice")
	}
//line stdlib/slice/slice.kuki:339
	total := 0.0
//line stdlib/slice/slice.kuki:340
	for _, item := range items {
//line stdlib/slice/slice.kuki:341
		total = (total + item)
	}
//line stdlib/slice/slice.kuki:342
	return (total / float64(len(items))), nil
}
