// Generated by Kukicha (requires Go 1.26+)

package json

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"os"
)

//line stdlib/json/json.kuki:13
type Number = json.Number

//line stdlib/json/json.kuki:16
type Encoder struct {
	writer io.Writer
	indent string
	prefix string
}

//line stdlib/json/json.kuki:22
type Decoder struct {
	reader io.Reader
}

//line stdlib/json/json.kuki:28
func NewEncoder(writer io.Writer) Encoder {
//line stdlib/json/json.kuki:29
	enc := Encoder{}
//line stdlib/json/json.kuki:30
	enc.writer = writer
//line stdlib/json/json.kuki:31
	enc.indent = ""
//line stdlib/json/json.kuki:32
	enc.prefix = ""
//line stdlib/json/json.kuki:33
	return enc
}

//line stdlib/json/json.kuki:38
func WithIndent(enc Encoder, indent string) Encoder {
//line stdlib/json/json.kuki:39
	enc.indent = indent
//line stdlib/json/json.kuki:40
	return enc
}

//line stdlib/json/json.kuki:44
func WithPrefix(enc Encoder, prefix string) Encoder {
//line stdlib/json/json.kuki:45
	enc.prefix = prefix
//line stdlib/json/json.kuki:46
	return enc
}

//line stdlib/json/json.kuki:52
func Encode(enc Encoder, value any) error {
//line stdlib/json/json.kuki:53
	encoder := json.NewEncoder(enc.writer)
//line stdlib/json/json.kuki:54
	if (enc.indent != "") || (enc.prefix != "") {
//line stdlib/json/json.kuki:55
		encoder.SetIndent(enc.prefix, enc.indent)
	}
//line stdlib/json/json.kuki:56
	return encoder.Encode(value)
}

//line stdlib/json/json.kuki:61
func NewDecoder(reader io.Reader) Decoder {
//line stdlib/json/json.kuki:62
	dec := Decoder{}
//line stdlib/json/json.kuki:63
	dec.reader = reader
//line stdlib/json/json.kuki:64
	return dec
}

//line stdlib/json/json.kuki:69
func Decode(dec Decoder, target any) error {
//line stdlib/json/json.kuki:70
	decoder := json.NewDecoder(dec.reader)
//line stdlib/json/json.kuki:71
	return decoder.Decode(target)
}

//line stdlib/json/json.kuki:75
func Bytes(value any) ([]byte, error) {
//line stdlib/json/json.kuki:76
	bytes, err := json.Marshal(value)
//line stdlib/json/json.kuki:77
	return bytes, err
}

//line stdlib/json/json.kuki:81
func PrettyBytes(value any) ([]byte, error) {
//line stdlib/json/json.kuki:82
	bytes, err := json.MarshalIndent(value, "", "  ")
//line stdlib/json/json.kuki:83
	return bytes, err
}

//line stdlib/json/json.kuki:88
func ParseInto(data []byte, target any) error {
//line stdlib/json/json.kuki:89
	return json.Unmarshal(data, target)
}

//line stdlib/json/json.kuki:94
func ParseStringInto(data string, target any) error {
//line stdlib/json/json.kuki:95
	return json.Unmarshal([]byte(data), target)
}

//line stdlib/json/json.kuki:101
func Write(writer io.Writer, value any) error {
//line stdlib/json/json.kuki:102
	return Encode(NewEncoder(writer), value)
}

//line stdlib/json/json.kuki:108
func ReadInto(reader io.Reader, target any) error {
//line stdlib/json/json.kuki:109
	return Decode(NewDecoder(reader), target)
}

//line stdlib/json/json.kuki:115
func WriteOutput(v any) error {
//line stdlib/json/json.kuki:116
	bytes, err := Bytes(v)
//line stdlib/json/json.kuki:117
	if err != nil {
//line stdlib/json/json.kuki:118
		return err
	}
//line stdlib/json/json.kuki:119
	_, err = fmt.Fprintln(os.Stdout, string(bytes))
//line stdlib/json/json.kuki:120
	return err
}

//line stdlib/json/json.kuki:124
func Read[T any](reader io.Reader) (T, error) {
//line stdlib/json/json.kuki:125
	data := *new(T)
//line stdlib/json/json.kuki:126
	// pipe step 1: ReadInto(...)
//line stdlib/json/json.kuki:126
	err_1 := ReadInto(reader, &data)
//line stdlib/json/json.kuki:126
	if err_1 != nil {
//line stdlib/json/json.kuki:126
		err_1 = fmt.Errorf("failed to read json: %w", err_1)
		var _zero0 T
//line stdlib/json/json.kuki:126
		return _zero0, err_1
	}
	_ = reader
//line stdlib/json/json.kuki:127
	return data, nil
}

//line stdlib/json/json.kuki:131
func Parse[T any](data []byte) (T, error) {
//line stdlib/json/json.kuki:132
	out := *new(T)
//line stdlib/json/json.kuki:133
//line stdlib/json/json.kuki:133
	err_2 := ParseInto(data, &out)
//line stdlib/json/json.kuki:133
	if err_2 != nil {
//line stdlib/json/json.kuki:133
		err_2 = fmt.Errorf("failed to parse json: %w", err_2)
		var _zero0 T
//line stdlib/json/json.kuki:133
		return _zero0, err_2
	}
//line stdlib/json/json.kuki:134
	return out, nil
}

//line stdlib/json/json.kuki:138
func ParseString[T any](data string) (T, error) {
//line stdlib/json/json.kuki:139
	out := *new(T)
//line stdlib/json/json.kuki:140
//line stdlib/json/json.kuki:140
	err_3 := ParseStringInto(data, &out)
//line stdlib/json/json.kuki:140
	if err_3 != nil {
//line stdlib/json/json.kuki:140
		err_3 = fmt.Errorf("failed to parse json: %w", err_3)
		var _zero0 T
//line stdlib/json/json.kuki:140
		return _zero0, err_3
	}
//line stdlib/json/json.kuki:141
	return out, nil
}

//line stdlib/json/json.kuki:147
func Pretty(s string) string {
//line stdlib/json/json.kuki:148
	buf := bytes.Buffer{}
//line stdlib/json/json.kuki:149
//line stdlib/json/json.kuki:149
	err_4 := json.Indent(&buf, []byte(s), "", "  ")
//line stdlib/json/json.kuki:149
	if err_4 != nil {
//line stdlib/json/json.kuki:149
		return s
	}
//line stdlib/json/json.kuki:150
	return buf.String()
}
