// Generated by Kukicha (requires Go 1.26+)

package table

import (
	"fmt"
	strpkg "github.com/kukichalang/kukicha/stdlib/string"
	"github.com/kukichalang/kukicha/stdlib/term"
	"strings"
)

//line stdlib/table/table.kuki:23
type Style string

const (
	StylePlain    Style = "plain"
	StyleBox      Style = "box"
	StyleMarkdown Style = "markdown"
)

func (e Style) String() string {
	return string(e)
}

func ParseStyle(s string) (Style, bool) {
	switch s {
	case "plain":
		return StylePlain, true
	case "box":
		return StyleBox, true
	case "markdown":
		return StyleMarkdown, true
	}
	var zero Style
	return zero, false
}

//line stdlib/table/table.kuki:29
type Table struct {
	Headers []string
	Rows    [][]string
}

//line stdlib/table/table.kuki:35
func New(headers []string) Table {
//line stdlib/table/table.kuki:36
	return Table{Headers: headers, Rows: make([][]string, 0)}
}

//line stdlib/table/table.kuki:41
func AddRow(t Table, row []string) Table {
//line stdlib/table/table.kuki:42
	padded := make([]string, len(t.Headers))
//line stdlib/table/table.kuki:43
	for i := range len(t.Headers) {
//line stdlib/table/table.kuki:44
		if i < len(row) {
//line stdlib/table/table.kuki:45
			padded[i] = row[i]
		}
	}
//line stdlib/table/table.kuki:46
	t.Rows = append(t.Rows, padded)
//line stdlib/table/table.kuki:47
	return t
}

//line stdlib/table/table.kuki:52
func Print(t Table) {
//line stdlib/table/table.kuki:53
	fmt.Println(renderTable(t, StylePlain))
}

//line stdlib/table/table.kuki:57
func PrintWithStyle(t Table, style Style) {
//line stdlib/table/table.kuki:58
	fmt.Println(renderTable(t, style))
}

//line stdlib/table/table.kuki:62
func ToString(t Table) string {
//line stdlib/table/table.kuki:63
	return renderTable(t, StylePlain)
}

//line stdlib/table/table.kuki:67
func ToStringWithStyle(t Table, style Style) string {
//line stdlib/table/table.kuki:68
	return renderTable(t, style)
}

//line stdlib/table/table.kuki:74
func renderTable(t Table, style Style) string {
//line stdlib/table/table.kuki:75
	widths := make([]int, len(t.Headers))
//line stdlib/table/table.kuki:76
	for i := range len(t.Headers) {
//line stdlib/table/table.kuki:77
		widths[i] = term.VisibleWidth(t.Headers[i])
	}
//line stdlib/table/table.kuki:78
	for _, row := range t.Rows {
//line stdlib/table/table.kuki:79
		for i := range len(t.Headers) {
//line stdlib/table/table.kuki:80
			if i < len(row) {
//line stdlib/table/table.kuki:81
				w := term.VisibleWidth(row[i])
//line stdlib/table/table.kuki:82
				if w > widths[i] {
//line stdlib/table/table.kuki:83
					widths[i] = w
				}
			}
		}
	}
//line stdlib/table/table.kuki:85
	out := strings.Builder{}
//line stdlib/table/table.kuki:87
	switch style {
	case StyleMarkdown:
//line stdlib/table/table.kuki:89
		out.WriteString(renderMarkdownRow(t.Headers, widths))
//line stdlib/table/table.kuki:90
		out.WriteString(renderMarkdownSep(widths))
//line stdlib/table/table.kuki:91
		for _, row := range t.Rows {
//line stdlib/table/table.kuki:92
			out.WriteString(renderMarkdownRow(row, widths))
		}
	case StyleBox:
//line stdlib/table/table.kuki:94
		out.WriteString(renderBoxTop(widths))
//line stdlib/table/table.kuki:95
		out.WriteString(renderBoxRow(t.Headers, widths))
//line stdlib/table/table.kuki:96
		out.WriteString(renderBoxMid(widths))
//line stdlib/table/table.kuki:97
		for _, row := range t.Rows {
//line stdlib/table/table.kuki:98
			out.WriteString(renderBoxRow(row, widths))
		}
//line stdlib/table/table.kuki:99
		out.WriteString(renderBoxBottom(widths))
	case StylePlain:
//line stdlib/table/table.kuki:101
		out.WriteString(renderPlainRow(t.Headers, widths))
//line stdlib/table/table.kuki:102
		out.WriteString(renderPlainSep(widths))
//line stdlib/table/table.kuki:103
		for _, row := range t.Rows {
//line stdlib/table/table.kuki:104
			out.WriteString(renderPlainRow(row, widths))
		}
	}
//line stdlib/table/table.kuki:106
	return out.String()
}

//line stdlib/table/table.kuki:108
func renderPlainRow(cols []string, widths []int) string {
//line stdlib/table/table.kuki:109
	sb := strings.Builder{}
//line stdlib/table/table.kuki:110
	for i := range len(widths) {
//line stdlib/table/table.kuki:111
		val := ""
//line stdlib/table/table.kuki:112
		if i < len(cols) {
//line stdlib/table/table.kuki:113
			val = cols[i]
		}
//line stdlib/table/table.kuki:114
		sb.WriteString(term.PadRightVisible(val, widths[i]))
//line stdlib/table/table.kuki:115
		if i < (len(widths) - 1) {
//line stdlib/table/table.kuki:116
			sb.WriteString("  ")
		}
	}
//line stdlib/table/table.kuki:117
	sb.WriteString("\n")
//line stdlib/table/table.kuki:118
	return sb.String()
}

//line stdlib/table/table.kuki:120
func renderPlainSep(widths []int) string {
//line stdlib/table/table.kuki:121
	sb := strings.Builder{}
//line stdlib/table/table.kuki:122
	for i := range len(widths) {
//line stdlib/table/table.kuki:123
		sb.WriteString(strpkg.Repeat("-", widths[i]))
//line stdlib/table/table.kuki:124
		if i < (len(widths) - 1) {
//line stdlib/table/table.kuki:125
			sb.WriteString("  ")
		}
	}
//line stdlib/table/table.kuki:126
	sb.WriteString("\n")
//line stdlib/table/table.kuki:127
	return sb.String()
}

//line stdlib/table/table.kuki:129
func renderMarkdownRow(cols []string, widths []int) string {
//line stdlib/table/table.kuki:130
	sb := strings.Builder{}
//line stdlib/table/table.kuki:131
	sb.WriteString("|")
//line stdlib/table/table.kuki:132
	for i := range len(widths) {
//line stdlib/table/table.kuki:133
		val := ""
//line stdlib/table/table.kuki:134
		if i < len(cols) {
//line stdlib/table/table.kuki:135
			val = cols[i]
		}
//line stdlib/table/table.kuki:136
		sb.WriteString(fmt.Sprintf(" %v |", term.PadRightVisible(val, widths[i])))
	}
//line stdlib/table/table.kuki:137
	sb.WriteString("\n")
//line stdlib/table/table.kuki:138
	return sb.String()
}

//line stdlib/table/table.kuki:140
func renderMarkdownSep(widths []int) string {
//line stdlib/table/table.kuki:141
	sb := strings.Builder{}
//line stdlib/table/table.kuki:142
	sb.WriteString("|")
//line stdlib/table/table.kuki:143
	for i := range len(widths) {
//line stdlib/table/table.kuki:144
		dashes := max(widths[i], 3)
//line stdlib/table/table.kuki:145
		sb.WriteString(" ")
//line stdlib/table/table.kuki:146
		sb.WriteString(strpkg.Repeat("-", dashes))
//line stdlib/table/table.kuki:147
		sb.WriteString(" |")
	}
//line stdlib/table/table.kuki:148
	sb.WriteString("\n")
//line stdlib/table/table.kuki:149
	return sb.String()
}

//line stdlib/table/table.kuki:151
func renderBoxTop(widths []int) string {
//line stdlib/table/table.kuki:152
	sb := strings.Builder{}
//line stdlib/table/table.kuki:153
	sb.WriteString("┌")
//line stdlib/table/table.kuki:154
	for i := range len(widths) {
//line stdlib/table/table.kuki:155
		sb.WriteString(strpkg.Repeat("─", (widths[i] + 2)))
//line stdlib/table/table.kuki:156
		if i < (len(widths) - 1) {
//line stdlib/table/table.kuki:157
			sb.WriteString("┬")
		}
	}
//line stdlib/table/table.kuki:158
	sb.WriteString("┐\n")
//line stdlib/table/table.kuki:159
	return sb.String()
}

//line stdlib/table/table.kuki:161
func renderBoxMid(widths []int) string {
//line stdlib/table/table.kuki:162
	sb := strings.Builder{}
//line stdlib/table/table.kuki:163
	sb.WriteString("├")
//line stdlib/table/table.kuki:164
	for i := range len(widths) {
//line stdlib/table/table.kuki:165
		sb.WriteString(strpkg.Repeat("─", (widths[i] + 2)))
//line stdlib/table/table.kuki:166
		if i < (len(widths) - 1) {
//line stdlib/table/table.kuki:167
			sb.WriteString("┼")
		}
	}
//line stdlib/table/table.kuki:168
	sb.WriteString("┤\n")
//line stdlib/table/table.kuki:169
	return sb.String()
}

//line stdlib/table/table.kuki:171
func renderBoxBottom(widths []int) string {
//line stdlib/table/table.kuki:172
	sb := strings.Builder{}
//line stdlib/table/table.kuki:173
	sb.WriteString("└")
//line stdlib/table/table.kuki:174
	for i := range len(widths) {
//line stdlib/table/table.kuki:175
		sb.WriteString(strpkg.Repeat("─", (widths[i] + 2)))
//line stdlib/table/table.kuki:176
		if i < (len(widths) - 1) {
//line stdlib/table/table.kuki:177
			sb.WriteString("┴")
		}
	}
//line stdlib/table/table.kuki:178
	sb.WriteString("┘\n")
//line stdlib/table/table.kuki:179
	return sb.String()
}

//line stdlib/table/table.kuki:181
func renderBoxRow(cols []string, widths []int) string {
//line stdlib/table/table.kuki:182
	sb := strings.Builder{}
//line stdlib/table/table.kuki:183
	sb.WriteString("│")
//line stdlib/table/table.kuki:184
	for i := range len(widths) {
//line stdlib/table/table.kuki:185
		val := ""
//line stdlib/table/table.kuki:186
		if i < len(cols) {
//line stdlib/table/table.kuki:187
			val = cols[i]
		}
//line stdlib/table/table.kuki:188
		sb.WriteString(fmt.Sprintf(" %v │", term.PadRightVisible(val, widths[i])))
	}
//line stdlib/table/table.kuki:189
	sb.WriteString("\n")
//line stdlib/table/table.kuki:190
	return sb.String()
}
