// Generated by Kukicha (requires Go 1.26+)

package obs

import (
	"fmt"
	"github.com/kukichalang/kukicha/stdlib/json"
	"github.com/kukichalang/kukicha/stdlib/random"
	"maps"
	"time"
)

//line stdlib/obs/obs.kuki:14
type Logger struct {
	Service       string
	Environment   string
	Component     string
	CorrelationID string
}

//line stdlib/obs/obs.kuki:21
type Timer struct {
	Logger    Logger
	Operation string
	StartedAt time.Time
}

//line stdlib/obs/obs.kuki:27
func New(service string, environment string) Logger {
//line stdlib/obs/obs.kuki:28
	return Logger{Service: service, Environment: environment, Component: "", CorrelationID: ""}
}

//line stdlib/obs/obs.kuki:31
func NewCorrelationID() string {
//line stdlib/obs/obs.kuki:32
	return random.String(16)
}

//line stdlib/obs/obs.kuki:35
func Debug(logger Logger, message string, fields map[string]any) {
//line stdlib/obs/obs.kuki:36
	Log(logger, "debug", message, fields)
}

//line stdlib/obs/obs.kuki:39
func Info(logger Logger, message string, fields map[string]any) {
//line stdlib/obs/obs.kuki:40
	Log(logger, "info", message, fields)
}

//line stdlib/obs/obs.kuki:43
func Warn(logger Logger, message string, fields map[string]any) {
//line stdlib/obs/obs.kuki:44
	Log(logger, "warn", message, fields)
}

//line stdlib/obs/obs.kuki:47
func Error(logger Logger, message string, fields map[string]any) {
//line stdlib/obs/obs.kuki:48
	Log(logger, "error", message, fields)
}

//line stdlib/obs/obs.kuki:51
func Log(logger Logger, level string, message string, fields map[string]any) {
//line stdlib/obs/obs.kuki:52
	payload := map[string]any{"ts": time.Now().Format(time.RFC3339Nano), "level": level, "message": message}
//line stdlib/obs/obs.kuki:58
	if logger.Service != "" {
//line stdlib/obs/obs.kuki:59
		payload["service"] = logger.Service
	}
//line stdlib/obs/obs.kuki:60
	if logger.Environment != "" {
//line stdlib/obs/obs.kuki:61
		payload["environment"] = logger.Environment
	}
//line stdlib/obs/obs.kuki:62
	if logger.Component != "" {
//line stdlib/obs/obs.kuki:63
		payload["component"] = logger.Component
	}
//line stdlib/obs/obs.kuki:64
	if logger.CorrelationID != "" {
//line stdlib/obs/obs.kuki:65
		payload["correlation_id"] = logger.CorrelationID
	}
//line stdlib/obs/obs.kuki:66
	if fields != nil {
//line stdlib/obs/obs.kuki:67
		maps.Copy(payload, fields)
	}
//line stdlib/obs/obs.kuki:69
	line, err_1 := json.Bytes(payload)
//line stdlib/obs/obs.kuki:69
	if err_1 != nil {
//line stdlib/obs/obs.kuki:69
		//line stdlib/obs/obs.kuki:70
		fmt.Println(fmt.Sprintf("[obs:%v] %v", level, message))
		//line stdlib/obs/obs.kuki:71
		return
	}
//line stdlib/obs/obs.kuki:73
	fmt.Printf("%s\n", line)
}

//line stdlib/obs/obs.kuki:76
func Start(logger Logger, operation string) Timer {
//line stdlib/obs/obs.kuki:77
	return Timer{Logger: logger, Operation: operation, StartedAt: time.Now()}
}

//line stdlib/obs/obs.kuki:80
func Stop(timer Timer, fields map[string]any) {
//line stdlib/obs/obs.kuki:81
	elapsedMs := time.Since(timer.StartedAt).Milliseconds()
//line stdlib/obs/obs.kuki:82
	if fields == nil {
//line stdlib/obs/obs.kuki:83
		fields = map[string]any{}
	}
//line stdlib/obs/obs.kuki:84
	fields["operation"] = timer.Operation
//line stdlib/obs/obs.kuki:85
	fields["duration_ms"] = elapsedMs
//line stdlib/obs/obs.kuki:86
	Info(timer.Logger, "operation complete", fields)
}

//line stdlib/obs/obs.kuki:89
func Fail(timer Timer, reason string, fields map[string]any) {
//line stdlib/obs/obs.kuki:90
	elapsedMs := time.Since(timer.StartedAt).Milliseconds()
//line stdlib/obs/obs.kuki:91
	if fields == nil {
//line stdlib/obs/obs.kuki:92
		fields = map[string]any{}
	}
//line stdlib/obs/obs.kuki:93
	fields["operation"] = timer.Operation
//line stdlib/obs/obs.kuki:94
	fields["duration_ms"] = elapsedMs
//line stdlib/obs/obs.kuki:95
	fields["reason"] = reason
//line stdlib/obs/obs.kuki:96
	Error(timer.Logger, "operation failed", fields)
}
