// Generated by Kukicha (requires Go 1.26+)

package chat

import (
	"bufio"
	"context"
	"fmt"
	ctxpkg "github.com/kukichalang/kukicha/stdlib/ctx"
	"github.com/kukichalang/kukicha/stdlib/env"
	"github.com/kukichalang/kukicha/stdlib/fetch"
	"github.com/kukichalang/kukicha/stdlib/json"
	kukistring "github.com/kukichalang/kukicha/stdlib/string"
	"strings"
)

//line stdlib/llm/chat/chat.kuki:37
type Message struct {
	Role       string     `json:"role"`
	Content    any        `json:"content"`
	ToolCalls  []ToolCall `json:"tool_calls,omitempty"`
	ToolCallID string     `json:"tool_call_id,omitempty"`
}

//line stdlib/llm/chat/chat.kuki:44
type ToolFunction struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Parameters  any    `json:"parameters"`
}

//line stdlib/llm/chat/chat.kuki:50
type Tool struct {
	Type     string       `json:"type"`
	Function ToolFunction `json:"function"`
}

//line stdlib/llm/chat/chat.kuki:55
type ToolCall struct {
	ID       string           `json:"id"`
	Type     string           `json:"type"`
	Function ToolCallFunction `json:"function"`
}

//line stdlib/llm/chat/chat.kuki:61
type ToolCallFunction struct {
	Name      string `json:"name"`
	Arguments string `json:"arguments"`
}

//line stdlib/llm/chat/chat.kuki:66
type Choice struct {
	Index        int             `json:"index"`
	Message      ResponseMessage `json:"message"`
	FinishReason string          `json:"finish_reason"`
}

//line stdlib/llm/chat/chat.kuki:72
type ResponseMessage struct {
	Role      string     `json:"role"`
	Content   string     `json:"content"`
	ToolCalls []ToolCall `json:"tool_calls,omitempty"`
}

//line stdlib/llm/chat/chat.kuki:78
type Usage struct {
	PromptTokens     int `json:"prompt_tokens"`
	CompletionTokens int `json:"completion_tokens"`
	TotalTokens      int `json:"total_tokens"`
}

//line stdlib/llm/chat/chat.kuki:84
type Completion struct {
	ID      string   `json:"id"`
	Object  string   `json:"object"`
	Created int      `json:"created"`
	Model   string   `json:"model"`
	Choices []Choice `json:"choices"`
	Usage   Usage    `json:"usage"`
}

//line stdlib/llm/chat/chat.kuki:93
type ChunkToolCallFunction struct {
	Name      string `json:"name,omitempty"`
	Arguments string `json:"arguments,omitempty"`
}

//line stdlib/llm/chat/chat.kuki:98
type ChunkToolCall struct {
	Index    int                   `json:"index"`
	ID       string                `json:"id,omitempty"`
	Type     string                `json:"type,omitempty"`
	Function ChunkToolCallFunction `json:"function"`
}

//line stdlib/llm/chat/chat.kuki:105
type ChunkDelta struct {
	Role      string          `json:"role,omitempty"`
	Content   string          `json:"content,omitempty"`
	ToolCalls []ChunkToolCall `json:"tool_calls,omitempty"`
}

//line stdlib/llm/chat/chat.kuki:111
type ChunkChoice struct {
	Index        int        `json:"index"`
	Delta        ChunkDelta `json:"delta"`
	FinishReason string     `json:"finish_reason,omitempty"`
}

//line stdlib/llm/chat/chat.kuki:117
type Chunk struct {
	ID      string        `json:"id"`
	Object  string        `json:"object"`
	Created int           `json:"created"`
	Model   string        `json:"model"`
	Choices []ChunkChoice `json:"choices"`
}

//line stdlib/llm/chat/chat.kuki:127
type StreamEvent struct {
	Type  string
	Chunk string
	Index int
}

//line stdlib/llm/chat/chat.kuki:133
type CompletionRequest struct {
	Model            string    `json:"model"`
	Messages         []Message `json:"messages"`
	Temperature      float64   `json:"temperature,omitempty"`
	MaxTokens        int       `json:"max_tokens,omitempty"`
	TopP             float64   `json:"top_p,omitempty"`
	N                int       `json:"n,omitempty"`
	Stop             []string  `json:"stop,omitempty"`
	PresencePenalty  float64   `json:"presence_penalty,omitempty"`
	FrequencyPenalty float64   `json:"frequency_penalty,omitempty"`
	Seed             int       `json:"seed,omitempty"`
	User             string    `json:"user,omitempty"`
	Stream           bool      `json:"stream,omitempty"`
	Tools            []Tool    `json:"tools,omitempty"`
	ToolChoice       any       `json:"tool_choice,omitempty"`
	ResponseFormat   any       `json:"response_format,omitempty"`
}

//line stdlib/llm/chat/chat.kuki:151
type Client struct {
	model            string
	provider         string
	baseURL          string
	path             string
	apiKey           string
	messages         []Message
	temperature      float64
	maxTokens        int
	topP             float64
	n                int
	stop             []string
	presencePenalty  float64
	frequencyPenalty float64
	seed             int
	user             string
	tools            []Tool
	toolChoice       any
	responseFormat   any
	streamHandler    func(string)
	eventHandler     func(StreamEvent)
	retryMaxAttempts int
	retryDelayMs     int
	ctx              context.Context
}

//line stdlib/llm/chat/chat.kuki:178
func New(model string) Client {
//line stdlib/llm/chat/chat.kuki:179
	c := Client{}
//line stdlib/llm/chat/chat.kuki:180
	if strings.Contains(model, ":") {
//line stdlib/llm/chat/chat.kuki:181
		parts := kukistring.SplitN(model, ":", 2)
//line stdlib/llm/chat/chat.kuki:182
		c.provider = parts[0]
//line stdlib/llm/chat/chat.kuki:183
		c.model = parts[1]
	} else {
//line stdlib/llm/chat/chat.kuki:185
		c.model = model
	}
//line stdlib/llm/chat/chat.kuki:186
	return c
}

//line stdlib/llm/chat/chat.kuki:189
func Provider(c Client, provider string) Client {
//line stdlib/llm/chat/chat.kuki:190
	c.provider = provider
//line stdlib/llm/chat/chat.kuki:191
	return c
}

//line stdlib/llm/chat/chat.kuki:194
func Gateway(c Client, url string) Client {
//line stdlib/llm/chat/chat.kuki:195
	c.baseURL = url
//line stdlib/llm/chat/chat.kuki:196
	return c
}

//line stdlib/llm/chat/chat.kuki:200
func Model(c Client, model string) Client {
//line stdlib/llm/chat/chat.kuki:201
	c.model = model
//line stdlib/llm/chat/chat.kuki:202
	return c
}

//line stdlib/llm/chat/chat.kuki:205
func BaseURL(c Client, url string) Client {
//line stdlib/llm/chat/chat.kuki:206
	c.baseURL = url
//line stdlib/llm/chat/chat.kuki:207
	return c
}

//line stdlib/llm/chat/chat.kuki:210
func Path(c Client, path string) Client {
//line stdlib/llm/chat/chat.kuki:211
	c.path = path
//line stdlib/llm/chat/chat.kuki:212
	return c
}

//line stdlib/llm/chat/chat.kuki:216
func APIKey(c Client, key string) Client {
//line stdlib/llm/chat/chat.kuki:217
	c.apiKey = key
//line stdlib/llm/chat/chat.kuki:218
	return c
}

//line stdlib/llm/chat/chat.kuki:221
func System(c Client, content string) Client {
//line stdlib/llm/chat/chat.kuki:222
	c.messages = append(c.messages, Message{Role: "system", Content: content})
//line stdlib/llm/chat/chat.kuki:223
	return c
}

//line stdlib/llm/chat/chat.kuki:226
func User(c Client, content string) Client {
//line stdlib/llm/chat/chat.kuki:227
	c.messages = append(c.messages, Message{Role: "user", Content: content})
//line stdlib/llm/chat/chat.kuki:228
	return c
}

//line stdlib/llm/chat/chat.kuki:231
func Assistant(c Client, content string) Client {
//line stdlib/llm/chat/chat.kuki:232
	c.messages = append(c.messages, Message{Role: "assistant", Content: content})
//line stdlib/llm/chat/chat.kuki:233
	return c
}

//line stdlib/llm/chat/chat.kuki:236
func AddMessage(c Client, role string, content string) Client {
//line stdlib/llm/chat/chat.kuki:237
	c.messages = append(c.messages, Message{Role: role, Content: content})
//line stdlib/llm/chat/chat.kuki:238
	return c
}

//line stdlib/llm/chat/chat.kuki:241
func Messages(c Client, msgs []Message) Client {
//line stdlib/llm/chat/chat.kuki:242
	c.messages = msgs
//line stdlib/llm/chat/chat.kuki:243
	return c
}

//line stdlib/llm/chat/chat.kuki:246
func Temperature(c Client, temp float64) Client {
//line stdlib/llm/chat/chat.kuki:247
	c.temperature = temp
//line stdlib/llm/chat/chat.kuki:248
	return c
}

//line stdlib/llm/chat/chat.kuki:251
func MaxTokens(c Client, tokens int) Client {
//line stdlib/llm/chat/chat.kuki:252
	c.maxTokens = tokens
//line stdlib/llm/chat/chat.kuki:253
	return c
}

//line stdlib/llm/chat/chat.kuki:256
func TopP(c Client, p float64) Client {
//line stdlib/llm/chat/chat.kuki:257
	c.topP = p
//line stdlib/llm/chat/chat.kuki:258
	return c
}

//line stdlib/llm/chat/chat.kuki:261
func Stop(c Client, sequences []string) Client {
//line stdlib/llm/chat/chat.kuki:262
	c.stop = sequences
//line stdlib/llm/chat/chat.kuki:263
	return c
}

//line stdlib/llm/chat/chat.kuki:266
func PresencePenalty(c Client, penalty float64) Client {
//line stdlib/llm/chat/chat.kuki:267
	c.presencePenalty = penalty
//line stdlib/llm/chat/chat.kuki:268
	return c
}

//line stdlib/llm/chat/chat.kuki:271
func FrequencyPenalty(c Client, penalty float64) Client {
//line stdlib/llm/chat/chat.kuki:272
	c.frequencyPenalty = penalty
//line stdlib/llm/chat/chat.kuki:273
	return c
}

//line stdlib/llm/chat/chat.kuki:276
func Seed(c Client, seed int) Client {
//line stdlib/llm/chat/chat.kuki:277
	c.seed = seed
//line stdlib/llm/chat/chat.kuki:278
	return c
}

//line stdlib/llm/chat/chat.kuki:281
func SetUser(c Client, user string) Client {
//line stdlib/llm/chat/chat.kuki:282
	c.user = user
//line stdlib/llm/chat/chat.kuki:283
	return c
}

//line stdlib/llm/chat/chat.kuki:286
func AddTool(c Client, name string, description string, parameters any) Client {
//line stdlib/llm/chat/chat.kuki:287
	fn := ToolFunction{Name: name, Description: description, Parameters: parameters}
//line stdlib/llm/chat/chat.kuki:288
	c.tools = append(c.tools, Tool{Type: "function", Function: fn})
//line stdlib/llm/chat/chat.kuki:289
	return c
}

//line stdlib/llm/chat/chat.kuki:292
func ToolChoiceAuto(c Client) Client {
//line stdlib/llm/chat/chat.kuki:293
	c.toolChoice = "auto"
//line stdlib/llm/chat/chat.kuki:294
	return c
}

//line stdlib/llm/chat/chat.kuki:297
func ToolChoiceRequired(c Client) Client {
//line stdlib/llm/chat/chat.kuki:298
	c.toolChoice = "required"
//line stdlib/llm/chat/chat.kuki:299
	return c
}

//line stdlib/llm/chat/chat.kuki:302
func ToolChoiceNone(c Client) Client {
//line stdlib/llm/chat/chat.kuki:303
	c.toolChoice = "none"
//line stdlib/llm/chat/chat.kuki:304
	return c
}

//line stdlib/llm/chat/chat.kuki:307
func JSONMode(c Client) Client {
//line stdlib/llm/chat/chat.kuki:308
	c.responseFormat = map[string]string{"type": "json_object"}
//line stdlib/llm/chat/chat.kuki:309
	return c
}

//line stdlib/llm/chat/chat.kuki:312
func Stream(c Client, handler func(string)) Client {
//line stdlib/llm/chat/chat.kuki:313
	c.streamHandler = handler
//line stdlib/llm/chat/chat.kuki:314
	return c
}

//line stdlib/llm/chat/chat.kuki:319
func StreamEvents(c Client, handler func(StreamEvent)) Client {
//line stdlib/llm/chat/chat.kuki:320
	c.eventHandler = handler
//line stdlib/llm/chat/chat.kuki:321
	return c
}

//line stdlib/llm/chat/chat.kuki:325
func Retry(c Client, maxAttempts int, delayMs int) Client {
//line stdlib/llm/chat/chat.kuki:326
	c.retryMaxAttempts = maxAttempts
//line stdlib/llm/chat/chat.kuki:327
	c.retryDelayMs = delayMs
//line stdlib/llm/chat/chat.kuki:328
	return c
}

//line stdlib/llm/chat/chat.kuki:331
func WithContext(c Client, h ctxpkg.Handle) Client {
//line stdlib/llm/chat/chat.kuki:332
	c.ctx = h.Ctx
//line stdlib/llm/chat/chat.kuki:333
	return c
}

//line stdlib/llm/chat/chat.kuki:337
func Ask(c Client, prompt string) (string, error) {
//line stdlib/llm/chat/chat.kuki:338
	c = User(c, prompt)
//line stdlib/llm/chat/chat.kuki:339
	return execute(c)
}

//line stdlib/llm/chat/chat.kuki:342
func Send(c Client) (string, error) {
//line stdlib/llm/chat/chat.kuki:343
	return execute(c)
}

//line stdlib/llm/chat/chat.kuki:347
func SendRaw(c Client) (Completion, error) {
//line stdlib/llm/chat/chat.kuki:348
	return executeRaw(c)
}

//line stdlib/llm/chat/chat.kuki:352
func Complete(model string, prompt string) (string, error) {
//line stdlib/llm/chat/chat.kuki:353
	return Ask(New(model), prompt)
}

//line stdlib/llm/chat/chat.kuki:356
func CompleteWithSystem(model string, systemPrompt string, prompt string) (string, error) {
//line stdlib/llm/chat/chat.kuki:357
	c := New(model)
//line stdlib/llm/chat/chat.kuki:358
	c = System(c, systemPrompt)
//line stdlib/llm/chat/chat.kuki:359
	return Ask(c, prompt)
}

//line stdlib/llm/chat/chat.kuki:364
func FromCompletion(c Client, comp Completion) Client {
//line stdlib/llm/chat/chat.kuki:365
	if len(comp.Choices) == 0 {
//line stdlib/llm/chat/chat.kuki:366
		return c
	}
//line stdlib/llm/chat/chat.kuki:367
	msg := comp.Choices[0].Message
//line stdlib/llm/chat/chat.kuki:368
	assistantMsg := Message{Role: "assistant", Content: msg.Content}
//line stdlib/llm/chat/chat.kuki:369
	if len(msg.ToolCalls) > 0 {
//line stdlib/llm/chat/chat.kuki:370
		assistantMsg.ToolCalls = msg.ToolCalls
	}
//line stdlib/llm/chat/chat.kuki:371
	c.messages = append(c.messages, assistantMsg)
//line stdlib/llm/chat/chat.kuki:372
	return c
}

//line stdlib/llm/chat/chat.kuki:379
func ExecuteToolCalls(c Client, comp Completion, handlers map[string]func(string) string) (Client, error) {
//line stdlib/llm/chat/chat.kuki:380
	if len(comp.Choices) == 0 {
//line stdlib/llm/chat/chat.kuki:381
		return c, nil
	}
//line stdlib/llm/chat/chat.kuki:382
	msg := comp.Choices[0].Message
//line stdlib/llm/chat/chat.kuki:383
	assistantMsg := Message{Role: "assistant", Content: msg.Content, ToolCalls: msg.ToolCalls}
//line stdlib/llm/chat/chat.kuki:384
	c.messages = append(c.messages, assistantMsg)
//line stdlib/llm/chat/chat.kuki:385
	for _, call := range msg.ToolCalls {
//line stdlib/llm/chat/chat.kuki:386
		handler, ok := handlers[call.Function.Name]
//line stdlib/llm/chat/chat.kuki:387
		if !ok {
//line stdlib/llm/chat/chat.kuki:388
			return c, fmt.Errorf("no handler registered for tool: %v", call.Function.Name)
		}
//line stdlib/llm/chat/chat.kuki:389
		result := handler(call.Function.Arguments)
//line stdlib/llm/chat/chat.kuki:390
		toolMsg := Message{Role: "tool", Content: result, ToolCallID: call.ID}
//line stdlib/llm/chat/chat.kuki:391
		c.messages = append(c.messages, toolMsg)
	}
//line stdlib/llm/chat/chat.kuki:392
	return c, nil
}

//line stdlib/llm/chat/chat.kuki:395
func GetText(comp Completion) string {
//line stdlib/llm/chat/chat.kuki:396
	if len(comp.Choices) == 0 {
//line stdlib/llm/chat/chat.kuki:397
		return ""
	}
//line stdlib/llm/chat/chat.kuki:398
	return comp.Choices[0].Message.Content
}

//line stdlib/llm/chat/chat.kuki:401
func GetToolCalls(comp Completion) []ToolCall {
//line stdlib/llm/chat/chat.kuki:402
	if len(comp.Choices) == 0 {
//line stdlib/llm/chat/chat.kuki:403
		return []ToolCall{}
	}
//line stdlib/llm/chat/chat.kuki:404
	return comp.Choices[0].Message.ToolCalls
}

//line stdlib/llm/chat/chat.kuki:407
func HasToolCalls(comp Completion) bool {
//line stdlib/llm/chat/chat.kuki:408
	return (len(GetToolCalls(comp)) > 0)
}

//line stdlib/llm/chat/chat.kuki:410
func providerDefaults(provider string) (string, string) {
//line stdlib/llm/chat/chat.kuki:411
	if provider == "openai" {
//line stdlib/llm/chat/chat.kuki:412
		return "OPENAI_API_KEY", "https://api.openai.com"
	}
//line stdlib/llm/chat/chat.kuki:413
	if provider == "anthropic" {
//line stdlib/llm/chat/chat.kuki:414
		return "ANTHROPIC_API_KEY", "https://api.anthropic.com"
	}
//line stdlib/llm/chat/chat.kuki:415
	if provider == "mistral" {
//line stdlib/llm/chat/chat.kuki:416
		return "MISTRAL_API_KEY", "https://api.mistral.ai"
	}
//line stdlib/llm/chat/chat.kuki:417
	if provider == "groq" {
//line stdlib/llm/chat/chat.kuki:418
		return "GROQ_API_KEY", "https://api.groq.com/openai"
	}
//line stdlib/llm/chat/chat.kuki:419
	if provider == "together" {
//line stdlib/llm/chat/chat.kuki:420
		return "TOGETHER_API_KEY", "https://api.together.xyz"
	}
//line stdlib/llm/chat/chat.kuki:421
	if provider == "deepseek" {
//line stdlib/llm/chat/chat.kuki:422
		return "DEEPSEEK_API_KEY", "https://api.deepseek.com"
	}
//line stdlib/llm/chat/chat.kuki:423
	if provider == "xai" {
//line stdlib/llm/chat/chat.kuki:424
		return "XAI_API_KEY", "https://api.x.ai"
	}
//line stdlib/llm/chat/chat.kuki:425
	if provider == "ollama" {
//line stdlib/llm/chat/chat.kuki:426
		return "", "http://localhost:11434"
	}
//line stdlib/llm/chat/chat.kuki:427
	if (provider == "fastflowlm") || (provider == "flm") {
//line stdlib/llm/chat/chat.kuki:428
		return "", "http://localhost:52625"
	}
//line stdlib/llm/chat/chat.kuki:429
	return "", ""
}

//line stdlib/llm/chat/chat.kuki:431
func resolveAPIKey(c Client) string {
//line stdlib/llm/chat/chat.kuki:432
	if c.apiKey != "" {
//line stdlib/llm/chat/chat.kuki:433
		return c.apiKey
	}
//line stdlib/llm/chat/chat.kuki:434
	envKey, _ := providerDefaults(c.provider)
//line stdlib/llm/chat/chat.kuki:435
	if envKey != "" {
//line stdlib/llm/chat/chat.kuki:436
		return env.GetOr(envKey, "")
	}
//line stdlib/llm/chat/chat.kuki:437
	return env.GetOr("LLM_API_KEY", "")
}

//line stdlib/llm/chat/chat.kuki:439
func resolveBaseURL(c Client) string {
//line stdlib/llm/chat/chat.kuki:440
	if c.baseURL != "" {
//line stdlib/llm/chat/chat.kuki:441
		return c.baseURL
	}
//line stdlib/llm/chat/chat.kuki:442
	_, baseURL := providerDefaults(c.provider)
//line stdlib/llm/chat/chat.kuki:443
	if baseURL != "" {
//line stdlib/llm/chat/chat.kuki:444
		return baseURL
	}
//line stdlib/llm/chat/chat.kuki:445
	envURL := env.GetOr("LLM_BASE_URL", "")
//line stdlib/llm/chat/chat.kuki:446
	if envURL != "" {
//line stdlib/llm/chat/chat.kuki:447
		return envURL
	}
//line stdlib/llm/chat/chat.kuki:448
	return "http://localhost:8000"
}

//line stdlib/llm/chat/chat.kuki:450
func resolvePath(c Client) string {
//line stdlib/llm/chat/chat.kuki:451
	if c.path != "" {
//line stdlib/llm/chat/chat.kuki:452
		return c.path
	}
//line stdlib/llm/chat/chat.kuki:453
	return "/v1/chat/completions"
}

//line stdlib/llm/chat/chat.kuki:455
func buildRequest(c Client) CompletionRequest {
//line stdlib/llm/chat/chat.kuki:456
	req := CompletionRequest{Model: c.model, Messages: c.messages}
//line stdlib/llm/chat/chat.kuki:457
	if c.temperature != 0.0 {
//line stdlib/llm/chat/chat.kuki:458
		req.Temperature = c.temperature
	}
//line stdlib/llm/chat/chat.kuki:459
	if c.maxTokens != 0 {
//line stdlib/llm/chat/chat.kuki:460
		req.MaxTokens = c.maxTokens
	}
//line stdlib/llm/chat/chat.kuki:461
	if c.topP != 0.0 {
//line stdlib/llm/chat/chat.kuki:462
		req.TopP = c.topP
	}
//line stdlib/llm/chat/chat.kuki:463
	if c.n != 0 {
//line stdlib/llm/chat/chat.kuki:464
		req.N = c.n
	}
//line stdlib/llm/chat/chat.kuki:465
	if c.seed != 0 {
//line stdlib/llm/chat/chat.kuki:466
		req.Seed = c.seed
	}
//line stdlib/llm/chat/chat.kuki:467
	if c.presencePenalty != 0.0 {
//line stdlib/llm/chat/chat.kuki:468
		req.PresencePenalty = c.presencePenalty
	}
//line stdlib/llm/chat/chat.kuki:469
	if c.frequencyPenalty != 0.0 {
//line stdlib/llm/chat/chat.kuki:470
		req.FrequencyPenalty = c.frequencyPenalty
	}
//line stdlib/llm/chat/chat.kuki:471
	if c.user != "" {
//line stdlib/llm/chat/chat.kuki:472
		req.User = c.user
	}
//line stdlib/llm/chat/chat.kuki:473
	if len(c.stop) > 0 {
//line stdlib/llm/chat/chat.kuki:474
		req.Stop = c.stop
	}
//line stdlib/llm/chat/chat.kuki:475
	if len(c.tools) > 0 {
//line stdlib/llm/chat/chat.kuki:476
		req.Tools = c.tools
	}
//line stdlib/llm/chat/chat.kuki:477
	if c.toolChoice != nil {
//line stdlib/llm/chat/chat.kuki:478
		req.ToolChoice = c.toolChoice
	}
//line stdlib/llm/chat/chat.kuki:479
	if c.responseFormat != nil {
//line stdlib/llm/chat/chat.kuki:480
		req.ResponseFormat = c.responseFormat
	}
//line stdlib/llm/chat/chat.kuki:481
	if (c.streamHandler != nil) || (c.eventHandler != nil) {
//line stdlib/llm/chat/chat.kuki:482
		req.Stream = true
	}
//line stdlib/llm/chat/chat.kuki:483
	return req
}

//line stdlib/llm/chat/chat.kuki:485
func execute(c Client) (string, error) {
//line stdlib/llm/chat/chat.kuki:486
	comp, err_1 := executeRaw(c)
//line stdlib/llm/chat/chat.kuki:486
	if err_1 != nil {
//line stdlib/llm/chat/chat.kuki:486
		return "", err_1
	}
//line stdlib/llm/chat/chat.kuki:487
	return GetText(comp), nil
}

//line stdlib/llm/chat/chat.kuki:489
func executeRaw(c Client) (Completion, error) {
//line stdlib/llm/chat/chat.kuki:490
	if (c.streamHandler != nil) || (c.eventHandler != nil) {
//line stdlib/llm/chat/chat.kuki:491
		return executeStreamRaw(c)
	}
//line stdlib/llm/chat/chat.kuki:493
	url := fmt.Sprintf("%v%v", resolveBaseURL(c), resolvePath(c))
//line stdlib/llm/chat/chat.kuki:494
	apiKey := resolveAPIKey(c)
//line stdlib/llm/chat/chat.kuki:496
	req := fetch.Body(fetch.Header(fetch.Method(fetch.New(url), "POST"), "Content-Type", "application/json"), buildRequest(c))
//line stdlib/llm/chat/chat.kuki:501
	if c.ctx != nil {
//line stdlib/llm/chat/chat.kuki:502
		req = fetch.WithContext(req, ctxpkg.FromContext(c.ctx))
	}
//line stdlib/llm/chat/chat.kuki:503
	if apiKey != "" {
//line stdlib/llm/chat/chat.kuki:504
		req = fetch.Header(req, "Authorization", fmt.Sprintf("Bearer %v", apiKey))
	}
//line stdlib/llm/chat/chat.kuki:505
	if c.retryMaxAttempts > 1 {
//line stdlib/llm/chat/chat.kuki:506
		req = fetch.Retry(req, c.retryMaxAttempts, c.retryDelayMs)
	}
//line stdlib/llm/chat/chat.kuki:508
	resp, err_2 := fetch.Do(req)
//line stdlib/llm/chat/chat.kuki:508
	if err_2 != nil {
		var _zero0 Completion
//line stdlib/llm/chat/chat.kuki:508
		return _zero0, err_2
	}
//line stdlib/llm/chat/chat.kuki:510
	defer resp.Body.Close()
//line stdlib/llm/chat/chat.kuki:512
	if resp.StatusCode >= 400 {
//line stdlib/llm/chat/chat.kuki:513
		errBody, err_3 := fetch.Bytes(resp)
//line stdlib/llm/chat/chat.kuki:513
		if err_3 != nil {
//line stdlib/llm/chat/chat.kuki:513
			return Completion{}, fmt.Errorf("API request failed with status %v", resp.StatusCode)
		}
//line stdlib/llm/chat/chat.kuki:514
		return Completion{}, fmt.Errorf("API request failed (%v): %v", resp.StatusCode, string(errBody))
	}
//line stdlib/llm/chat/chat.kuki:516
	comp := Completion{}
//line stdlib/llm/chat/chat.kuki:517
//line stdlib/llm/chat/chat.kuki:517
	err_4 := json.ReadInto(resp.Body, &comp)
//line stdlib/llm/chat/chat.kuki:517
	if err_4 != nil {
		var _zero0 Completion
//line stdlib/llm/chat/chat.kuki:517
		return _zero0, err_4
	}
//line stdlib/llm/chat/chat.kuki:518
	return comp, nil
}

//line stdlib/llm/chat/chat.kuki:520
func executeStreamRaw(c Client) (Completion, error) {
//line stdlib/llm/chat/chat.kuki:521
	url := fmt.Sprintf("%v%v", resolveBaseURL(c), resolvePath(c))
//line stdlib/llm/chat/chat.kuki:522
	apiKey := resolveAPIKey(c)
//line stdlib/llm/chat/chat.kuki:524
	req := fetch.Body(fetch.Header(fetch.Header(fetch.Method(fetch.New(url), "POST"), "Content-Type", "application/json"), "Accept", "text/event-stream"), buildRequest(c))
//line stdlib/llm/chat/chat.kuki:530
	if c.ctx != nil {
//line stdlib/llm/chat/chat.kuki:531
		req = fetch.WithContext(req, ctxpkg.FromContext(c.ctx))
	}
//line stdlib/llm/chat/chat.kuki:532
	if apiKey != "" {
//line stdlib/llm/chat/chat.kuki:533
		req = fetch.Header(req, "Authorization", fmt.Sprintf("Bearer %v", apiKey))
	}
//line stdlib/llm/chat/chat.kuki:534
	if c.retryMaxAttempts > 1 {
//line stdlib/llm/chat/chat.kuki:535
		req = fetch.Retry(req, c.retryMaxAttempts, c.retryDelayMs)
	}
//line stdlib/llm/chat/chat.kuki:537
	resp, err_5 := fetch.Do(req)
//line stdlib/llm/chat/chat.kuki:537
	if err_5 != nil {
		var _zero0 Completion
//line stdlib/llm/chat/chat.kuki:537
		return _zero0, err_5
	}
//line stdlib/llm/chat/chat.kuki:539
	defer resp.Body.Close()
//line stdlib/llm/chat/chat.kuki:541
	if resp.StatusCode >= 400 {
//line stdlib/llm/chat/chat.kuki:542
		errBody, err_6 := fetch.Bytes(resp)
//line stdlib/llm/chat/chat.kuki:542
		if err_6 != nil {
//line stdlib/llm/chat/chat.kuki:542
			return Completion{}, fmt.Errorf("API request failed with status %v", resp.StatusCode)
		}
//line stdlib/llm/chat/chat.kuki:543
		return Completion{}, fmt.Errorf("API request failed (%v): %v", resp.StatusCode, string(errBody))
	}
//line stdlib/llm/chat/chat.kuki:545
	fullContent := ""
//line stdlib/llm/chat/chat.kuki:546
	callsMap := make(map[int]ToolCall)
//line stdlib/llm/chat/chat.kuki:547
	maxIdx := -1
//line stdlib/llm/chat/chat.kuki:548
	scanner := bufio.NewScanner(resp.Body)
//line stdlib/llm/chat/chat.kuki:549
	for scanner.Scan() {
//line stdlib/llm/chat/chat.kuki:550
		line := scanner.Text()
//line stdlib/llm/chat/chat.kuki:551
		if (line == "") || kukistring.HasPrefix(line, ":") {
//line stdlib/llm/chat/chat.kuki:552
			continue
		}
//line stdlib/llm/chat/chat.kuki:553
		if line == "data: [DONE]" {
//line stdlib/llm/chat/chat.kuki:554
			break
		}
//line stdlib/llm/chat/chat.kuki:555
		if kukistring.HasPrefix(line, "data: ") {
//line stdlib/llm/chat/chat.kuki:556
			data := kukistring.TrimPrefix(line, "data: ")
//line stdlib/llm/chat/chat.kuki:557
			chunk := Chunk{}
//line stdlib/llm/chat/chat.kuki:558
//line stdlib/llm/chat/chat.kuki:558
			err_7 := json.ParseInto([]byte(data), &chunk)
//line stdlib/llm/chat/chat.kuki:558
			if err_7 != nil {
//line stdlib/llm/chat/chat.kuki:558
				//line stdlib/llm/chat/chat.kuki:559
				continue
			}
//line stdlib/llm/chat/chat.kuki:561
			if len(chunk.Choices) > 0 {
//line stdlib/llm/chat/chat.kuki:562
				delta := chunk.Choices[0].Delta
//line stdlib/llm/chat/chat.kuki:563
				if delta.Content != "" {
//line stdlib/llm/chat/chat.kuki:564
					fullContent = (fullContent + delta.Content)
//line stdlib/llm/chat/chat.kuki:565
					if c.streamHandler != nil {
//line stdlib/llm/chat/chat.kuki:566
						c.streamHandler(delta.Content)
					}
//line stdlib/llm/chat/chat.kuki:567
					if c.eventHandler != nil {
//line stdlib/llm/chat/chat.kuki:568
						c.eventHandler(StreamEvent{Type: "text", Chunk: delta.Content})
					}
				}
//line stdlib/llm/chat/chat.kuki:569
				if len(delta.ToolCalls) > 0 {
//line stdlib/llm/chat/chat.kuki:570
					for _, tcDelta := range delta.ToolCalls {
//line stdlib/llm/chat/chat.kuki:571
						idx := tcDelta.Index
//line stdlib/llm/chat/chat.kuki:572
						call := callsMap[idx]
//line stdlib/llm/chat/chat.kuki:573
						if tcDelta.ID != "" {
//line stdlib/llm/chat/chat.kuki:574
							call.ID = tcDelta.ID
						}
//line stdlib/llm/chat/chat.kuki:575
						if tcDelta.Type != "" {
//line stdlib/llm/chat/chat.kuki:576
							call.Type = tcDelta.Type
						}
//line stdlib/llm/chat/chat.kuki:577
						if tcDelta.Function.Name != "" {
//line stdlib/llm/chat/chat.kuki:578
							call.Function.Name = (call.Function.Name + tcDelta.Function.Name)
//line stdlib/llm/chat/chat.kuki:579
							if c.eventHandler != nil {
//line stdlib/llm/chat/chat.kuki:580
								c.eventHandler(StreamEvent{Type: "tool_call_name", Chunk: tcDelta.Function.Name, Index: idx})
							}
						}
//line stdlib/llm/chat/chat.kuki:585
						if tcDelta.Function.Arguments != "" {
//line stdlib/llm/chat/chat.kuki:586
							call.Function.Arguments = (call.Function.Arguments + tcDelta.Function.Arguments)
//line stdlib/llm/chat/chat.kuki:587
							if c.eventHandler != nil {
//line stdlib/llm/chat/chat.kuki:588
								c.eventHandler(StreamEvent{Type: "tool_call_args", Chunk: tcDelta.Function.Arguments, Index: idx})
							}
						}
//line stdlib/llm/chat/chat.kuki:593
						callsMap[idx] = call
//line stdlib/llm/chat/chat.kuki:594
						if idx > maxIdx {
//line stdlib/llm/chat/chat.kuki:595
							maxIdx = idx
						}
					}
				}
			}
		}
	}
//line stdlib/llm/chat/chat.kuki:597
//line stdlib/llm/chat/chat.kuki:597
	err_8 := scanner.Err()
//line stdlib/llm/chat/chat.kuki:597
	if err_8 != nil {
//line stdlib/llm/chat/chat.kuki:597
		return Completion{}, fmt.Errorf("%v", err_8)
	}
//line stdlib/llm/chat/chat.kuki:599
	toolCalls := make([]ToolCall, 0)
//line stdlib/llm/chat/chat.kuki:600
	for i := range maxIdx + 1 {
//line stdlib/llm/chat/chat.kuki:601
		tc, ok := callsMap[i]
//line stdlib/llm/chat/chat.kuki:602
		if ok {
//line stdlib/llm/chat/chat.kuki:603
			if tc.Type == "" {
//line stdlib/llm/chat/chat.kuki:604
				tc.Type = "function"
			}
//line stdlib/llm/chat/chat.kuki:605
			toolCalls = append(toolCalls, tc)
		}
	}
//line stdlib/llm/chat/chat.kuki:607
	comp := Completion{Choices: []Choice{Choice{Index: 0, Message: ResponseMessage{Role: "assistant", Content: fullContent, ToolCalls: toolCalls}}}}
//line stdlib/llm/chat/chat.kuki:615
	return comp, nil
}
