// Generated by Kukicha (requires Go 1.26+)

package input

import (
	"bufio"
	"errors"
	"fmt"
	kukistring "github.com/kukichalang/kukicha/stdlib/string"
	"os"
	"strconv"
)

//line stdlib/input/input.kuki:18
func ReadLine(prompt string) (string, error) {
//line stdlib/input/input.kuki:19
	if prompt != "" {
//line stdlib/input/input.kuki:20
		fmt.Print(prompt)
	}
//line stdlib/input/input.kuki:22
	reader := bufio.NewReader(os.Stdin)
//line stdlib/input/input.kuki:23
	text, err_1 := reader.ReadString('\n')
//line stdlib/input/input.kuki:23
	if err_1 != nil {
//line stdlib/input/input.kuki:23
		return "", err_1
	}
//line stdlib/input/input.kuki:24
	return kukistring.TrimSpace(text), nil
}

//line stdlib/input/input.kuki:29
func Confirm(prompt string) (bool, error) {
//line stdlib/input/input.kuki:30
	answer, err_2 := ReadLine(fmt.Sprintf("%v [y/N]: ", prompt))
//line stdlib/input/input.kuki:30
	if err_2 != nil {
//line stdlib/input/input.kuki:30
		err_2 = fmt.Errorf("confirm prompt: %w", err_2)
//line stdlib/input/input.kuki:30
		return false, err_2
	}
//line stdlib/input/input.kuki:31
	lower := kukistring.ToLower(kukistring.TrimSpace(answer))
//line stdlib/input/input.kuki:32
	return ((lower == "y") || (lower == "yes")), nil
}

//line stdlib/input/input.kuki:40
func Choose(prompt string, options []string) (int, error) {
//line stdlib/input/input.kuki:41
	if len(options) == 0 {
//line stdlib/input/input.kuki:42
		return -1, errors.New("no options provided")
	}
//line stdlib/input/input.kuki:44
	fmt.Println(prompt)
//line stdlib/input/input.kuki:45
	fmt.Println("")
//line stdlib/input/input.kuki:46
	for i, opt := range options {
//line stdlib/input/input.kuki:47
		fmt.Println(fmt.Sprintf("  %v) %v", (i + 1), opt))
	}
//line stdlib/input/input.kuki:48
	fmt.Println("")
//line stdlib/input/input.kuki:50
	raw, err_3 := ReadLine("Enter number (or q to quit): ")
//line stdlib/input/input.kuki:50
	if err_3 != nil {
//line stdlib/input/input.kuki:50
		err_3 = fmt.Errorf("choose prompt: %w", err_3)
//line stdlib/input/input.kuki:50
		return 0, err_3
	}
//line stdlib/input/input.kuki:51
	trimmed := kukistring.TrimSpace(raw)
//line stdlib/input/input.kuki:53
	if ((trimmed == "") || (trimmed == "q")) || (trimmed == "Q") {
//line stdlib/input/input.kuki:54
		return -1, errors.New("cancelled")
	}
//line stdlib/input/input.kuki:56
	val, err_4 := strconv.Atoi(trimmed)
//line stdlib/input/input.kuki:56
	if err_4 != nil {
//line stdlib/input/input.kuki:56
		return -1, fmt.Errorf("invalid selection: %v", trimmed)
	}
//line stdlib/input/input.kuki:57
	if (val < 1) || (val > len(options)) {
//line stdlib/input/input.kuki:58
		return -1, fmt.Errorf("selection out of range: %v", val)
	}
//line stdlib/input/input.kuki:60
	return (val - 1), nil
}

//line stdlib/input/input.kuki:82
const fieldKindText = "text"

//line stdlib/input/input.kuki:84
const fieldKindConfirm = "confirm"

//line stdlib/input/input.kuki:86
const fieldKindChoose = "choose"

//line stdlib/input/input.kuki:91
type FormField struct {
	Key       string
	Prompt    string
	Kind      string
	Options   []string
	Default   string
	Validator func(string) error
}

//line stdlib/input/input.kuki:101
type Form struct {
	Fields []FormField
	Values map[string]string
	W      *os.File
	R      *os.File
}

//line stdlib/input/input.kuki:108
func NewForm() *Form {
//line stdlib/input/input.kuki:109
	return &Form{Fields: []FormField{}, Values: make(map[string]string), W: os.Stdout, R: os.Stdin}
}

//line stdlib/input/input.kuki:117
func (f *Form) Text(key string, prompt string) *Form {
//line stdlib/input/input.kuki:118
	f.Fields = append(f.Fields, FormField{Key: key, Prompt: prompt, Kind: fieldKindText})
//line stdlib/input/input.kuki:119
	return f
}

//line stdlib/input/input.kuki:122
func (f *Form) Confirm(key string, prompt string) *Form {
//line stdlib/input/input.kuki:123
	f.Fields = append(f.Fields, FormField{Key: key, Prompt: prompt, Kind: fieldKindConfirm})
//line stdlib/input/input.kuki:124
	return f
}

//line stdlib/input/input.kuki:128
func (f *Form) Choose(key string, prompt string, options []string) *Form {
//line stdlib/input/input.kuki:129
	f.Fields = append(f.Fields, FormField{Key: key, Prompt: prompt, Kind: fieldKindChoose, Options: options})
//line stdlib/input/input.kuki:130
	return f
}

//line stdlib/input/input.kuki:135
func (f *Form) Validate(key string, validator func(string) error) *Form {
//line stdlib/input/input.kuki:136
	i := 0
//line stdlib/input/input.kuki:137
	for i < len(f.Fields) {
//line stdlib/input/input.kuki:138
		if f.Fields[i].Key == key {
//line stdlib/input/input.kuki:139
			f.Fields[i].Validator = validator
//line stdlib/input/input.kuki:140
			return f
		}
//line stdlib/input/input.kuki:141
		i = (i + 1)
	}
//line stdlib/input/input.kuki:142
	return f
}

//line stdlib/input/input.kuki:149
func (f *Form) Default(key string, value string) *Form {
//line stdlib/input/input.kuki:150
	i := 0
//line stdlib/input/input.kuki:151
	for i < len(f.Fields) {
//line stdlib/input/input.kuki:152
		if f.Fields[i].Key == key {
//line stdlib/input/input.kuki:153
			f.Fields[i].Default = value
//line stdlib/input/input.kuki:154
			return f
		}
//line stdlib/input/input.kuki:155
		i = (i + 1)
	}
//line stdlib/input/input.kuki:156
	return f
}

//line stdlib/input/input.kuki:160
func (f *Form) Run() error {
//line stdlib/input/input.kuki:161
	reader := bufio.NewReader(f.R)
//line stdlib/input/input.kuki:162
	for _, field := range f.Fields {
//line stdlib/input/input.kuki:163
		for {
//line stdlib/input/input.kuki:164
			value, err := promptField(f.W, reader, field)
//line stdlib/input/input.kuki:165
			if err != nil {
//line stdlib/input/input.kuki:166
				return err
			}
//line stdlib/input/input.kuki:167
			if field.Validator != nil {
//line stdlib/input/input.kuki:168
				vErr := field.Validator(value)
//line stdlib/input/input.kuki:169
				if vErr != nil {
//line stdlib/input/input.kuki:170
					fmt.Fprintln(f.W, fmt.Sprintf("  %v", vErr))
//line stdlib/input/input.kuki:171
					continue
				}
			}
//line stdlib/input/input.kuki:172
			f.Values[field.Key] = value
//line stdlib/input/input.kuki:173
			break
		}
	}
//line stdlib/input/input.kuki:174
	return nil
}

//line stdlib/input/input.kuki:177
func (f *Form) String(key string) string {
//line stdlib/input/input.kuki:178
	return f.Values[key]
}

//line stdlib/input/input.kuki:182
func (f *Form) Bool(key string) bool {
//line stdlib/input/input.kuki:183
	return (f.Values[key] == "true")
}

//line stdlib/input/input.kuki:189
func promptField(w *os.File, reader *bufio.Reader, field FormField) (string, error) {
//line stdlib/input/input.kuki:190
	if field.Kind == fieldKindText {
//line stdlib/input/input.kuki:191
		line, err_5 := readLineFrom(w, reader, field.Prompt)
//line stdlib/input/input.kuki:191
		if err_5 != nil {
//line stdlib/input/input.kuki:191
			return "", err_5
		}
//line stdlib/input/input.kuki:192
		if (line == "") && (field.Default != "") {
//line stdlib/input/input.kuki:193
			return field.Default, nil
		}
//line stdlib/input/input.kuki:194
		return line, nil
	}
//line stdlib/input/input.kuki:195
	if field.Kind == fieldKindConfirm {
//line stdlib/input/input.kuki:196
		line, err_6 := readLineFrom(w, reader, fmt.Sprintf("%v[y/N]: ", field.Prompt))
//line stdlib/input/input.kuki:196
		if err_6 != nil {
//line stdlib/input/input.kuki:196
			return "", err_6
		}
//line stdlib/input/input.kuki:197
		lower := kukistring.ToLower(kukistring.TrimSpace(line))
//line stdlib/input/input.kuki:198
		if (lower == "y") || (lower == "yes") {
//line stdlib/input/input.kuki:199
			return "true", nil
		}
//line stdlib/input/input.kuki:200
		return "false", nil
	}
//line stdlib/input/input.kuki:201
	if field.Kind == fieldKindChoose {
//line stdlib/input/input.kuki:202
		return promptChoose(w, reader, field)
	}
//line stdlib/input/input.kuki:203
	return "", fmt.Errorf("unknown field kind: %v", field.Kind)
}

//line stdlib/input/input.kuki:206
func promptChoose(w *os.File, reader *bufio.Reader, field FormField) (string, error) {
//line stdlib/input/input.kuki:207
	if len(field.Options) == 0 {
//line stdlib/input/input.kuki:208
		return "", fmt.Errorf("no options for %v", field.Key)
	}
//line stdlib/input/input.kuki:209
	fmt.Fprintln(w, field.Prompt)
//line stdlib/input/input.kuki:210
	for i, opt := range field.Options {
//line stdlib/input/input.kuki:211
		fmt.Fprintln(w, fmt.Sprintf("  %v) %v", (i+1), opt))
	}
//line stdlib/input/input.kuki:212
	raw, err_7 := readLineFrom(w, reader, "Enter number (or q to quit): ")
//line stdlib/input/input.kuki:212
	if err_7 != nil {
//line stdlib/input/input.kuki:212
		return "", err_7
	}
//line stdlib/input/input.kuki:213
	trimmed := kukistring.TrimSpace(raw)
//line stdlib/input/input.kuki:214
	if ((trimmed == "") || (trimmed == "q")) || (trimmed == "Q") {
//line stdlib/input/input.kuki:215
		return "", errors.New("cancelled")
	}
//line stdlib/input/input.kuki:216
	val, err_8 := strconv.Atoi(trimmed)
//line stdlib/input/input.kuki:216
	if err_8 != nil {
//line stdlib/input/input.kuki:216
		return "", fmt.Errorf("invalid selection: %v", trimmed)
	}
//line stdlib/input/input.kuki:217
	if (val < 1) || (val > len(field.Options)) {
//line stdlib/input/input.kuki:218
		return "", fmt.Errorf("selection out of range: %v", val)
	}
//line stdlib/input/input.kuki:219
	return field.Options[(val - 1)], nil
}

//line stdlib/input/input.kuki:223
func readLineFrom(w *os.File, reader *bufio.Reader, prompt string) (string, error) {
//line stdlib/input/input.kuki:224
	if prompt != "" {
//line stdlib/input/input.kuki:225
		fmt.Fprint(w, prompt)
	}
//line stdlib/input/input.kuki:226
	text, err_9 := reader.ReadString('\n')
//line stdlib/input/input.kuki:226
	if err_9 != nil {
//line stdlib/input/input.kuki:226
		return "", err_9
	}
//line stdlib/input/input.kuki:227
	return kukistring.TrimSpace(text), nil
}
