// Generated by Kukicha (requires Go 1.26+)

package parse_test

import (
	"github.com/kukichalang/kukicha/stdlib/parse"
	"github.com/kukichalang/kukicha/stdlib/test"
	"net/url"
	"os"
	"testing"
	"time"
)

//line stdlib/parse/parse_test.kuki:13
type User struct {
	Name string
	Age  int
}

//line stdlib/parse/parse_test.kuki:17
func TestJSON(t *testing.T) {
//line stdlib/parse/parse_test.kuki:18
	u, errs := parse.JSON[User]("{\"Name\":\"ada\",\"Age\":36}")
//line stdlib/parse/parse_test.kuki:19
	test.AssertEqual(t, len(errs), 0)
//line stdlib/parse/parse_test.kuki:20
	test.AssertEqual(t, u.Name, "ada")
//line stdlib/parse/parse_test.kuki:21
	test.AssertEqual(t, u.Age, 36)
}

//line stdlib/parse/parse_test.kuki:23
func TestJSONParseError(t *testing.T) {
//line stdlib/parse/parse_test.kuki:24
	_, errs := parse.JSON[User]("not valid json")
//line stdlib/parse/parse_test.kuki:25
	test.AssertEqual(t, len(errs), 1)
//line stdlib/parse/parse_test.kuki:26
	test.AssertEqual(t, errs[0].Path, "$")
//line stdlib/parse/parse_test.kuki:27
	test.AssertEqual(t, errs[0].Rule, "parse")
}

//line stdlib/parse/parse_test.kuki:30
func TestJSONLines(t *testing.T) {
//line stdlib/parse/parse_test.kuki:31
	lines := parse.JSONLines("{\"a\":1}\n\n {\"b\":2}\n")
//line stdlib/parse/parse_test.kuki:32
	test.AssertEqual(t, len(lines), 2)
//line stdlib/parse/parse_test.kuki:33
	test.AssertEqual(t, lines[0], "{\"a\":1}")
//line stdlib/parse/parse_test.kuki:34
	test.AssertEqual(t, lines[1], "{\"b\":2}")
}

//line stdlib/parse/parse_test.kuki:37
type Config struct {
	User  string
	Email string
}

//line stdlib/parse/parse_test.kuki:41
func TestYAML(t *testing.T) {
//line stdlib/parse/parse_test.kuki:42
	c, errs := parse.YAML[Config]("user: alice\nemail: test@example.com")
//line stdlib/parse/parse_test.kuki:43
	test.AssertEqual(t, len(errs), 0)
//line stdlib/parse/parse_test.kuki:44
	test.AssertEqual(t, c.User, "alice")
//line stdlib/parse/parse_test.kuki:45
	test.AssertEqual(t, c.Email, "test@example.com")
}

//line stdlib/parse/parse_test.kuki:47
func TestYAMLParseError(t *testing.T) {
//line stdlib/parse/parse_test.kuki:48
	_, errs := parse.YAML[Config]("::: not valid yaml :::")
//line stdlib/parse/parse_test.kuki:49
	test.AssertEqual(t, len(errs), 1)
//line stdlib/parse/parse_test.kuki:50
	test.AssertEqual(t, errs[0].Path, "$")
//line stdlib/parse/parse_test.kuki:51
	test.AssertEqual(t, errs[0].Rule, "parse")
}

//line stdlib/parse/parse_test.kuki:54
type LoginForm struct {
	Name   string
	Age    int
	Active bool
}

//line stdlib/parse/parse_test.kuki:59
func TestForm(t *testing.T) {
//line stdlib/parse/parse_test.kuki:60
	values := url.Values{}
//line stdlib/parse/parse_test.kuki:61
	values.Set("Name", "ada")
//line stdlib/parse/parse_test.kuki:62
	values.Set("Age", "36")
//line stdlib/parse/parse_test.kuki:63
	values.Set("Active", "true")
//line stdlib/parse/parse_test.kuki:64
	form, errs := parse.Form[LoginForm](values)
//line stdlib/parse/parse_test.kuki:65
	test.AssertEqual(t, len(errs), 0)
//line stdlib/parse/parse_test.kuki:66
	test.AssertEqual(t, form.Name, "ada")
//line stdlib/parse/parse_test.kuki:67
	test.AssertEqual(t, form.Age, 36)
//line stdlib/parse/parse_test.kuki:68
	test.AssertEqual(t, form.Active, true)
}

//line stdlib/parse/parse_test.kuki:70
func TestFormParseError(t *testing.T) {
//line stdlib/parse/parse_test.kuki:71
	values := url.Values{}
//line stdlib/parse/parse_test.kuki:72
	values.Set("Age", "not a number")
//line stdlib/parse/parse_test.kuki:73
	_, errs := parse.Form[LoginForm](values)
//line stdlib/parse/parse_test.kuki:74
	test.AssertEqual(t, len(errs), 1)
//line stdlib/parse/parse_test.kuki:75
	test.AssertEqual(t, errs[0].Path, "Age")
//line stdlib/parse/parse_test.kuki:76
	test.AssertEqual(t, errs[0].Rule, "parse")
}

//line stdlib/parse/parse_test.kuki:79
type AppConfig struct {
	Host  string
	Port  int
	Debug bool
}

//line stdlib/parse/parse_test.kuki:84
func TestEnv(t *testing.T) {
//line stdlib/parse/parse_test.kuki:85
	os.Setenv("APP_HOST", "localhost")
//line stdlib/parse/parse_test.kuki:86
	os.Setenv("APP_PORT", "8080")
//line stdlib/parse/parse_test.kuki:87
	os.Setenv("APP_DEBUG", "true")
//line stdlib/parse/parse_test.kuki:88
	defer os.Unsetenv("APP_HOST")
//line stdlib/parse/parse_test.kuki:89
	defer os.Unsetenv("APP_PORT")
//line stdlib/parse/parse_test.kuki:90
	defer os.Unsetenv("APP_DEBUG")
//line stdlib/parse/parse_test.kuki:92
	cfg, errs := parse.Env[AppConfig]("APP")
//line stdlib/parse/parse_test.kuki:93
	test.AssertEqual(t, len(errs), 0)
//line stdlib/parse/parse_test.kuki:94
	test.AssertEqual(t, cfg.Host, "localhost")
//line stdlib/parse/parse_test.kuki:95
	test.AssertEqual(t, cfg.Port, 8080)
//line stdlib/parse/parse_test.kuki:96
	test.AssertEqual(t, cfg.Debug, true)
}

//line stdlib/parse/parse_test.kuki:98
func TestEnvParseError(t *testing.T) {
//line stdlib/parse/parse_test.kuki:99
	os.Setenv("APP_PORT", "notanumber")
//line stdlib/parse/parse_test.kuki:100
	defer os.Unsetenv("APP_PORT")
//line stdlib/parse/parse_test.kuki:101
	_, errs := parse.Env[AppConfig]("APP")
//line stdlib/parse/parse_test.kuki:102
	test.AssertEqual(t, len(errs), 1)
//line stdlib/parse/parse_test.kuki:103
	test.AssertEqual(t, errs[0].Path, "Port")
//line stdlib/parse/parse_test.kuki:104
	test.AssertEqual(t, errs[0].Rule, "parse")
}

//line stdlib/parse/parse_test.kuki:107
func TestCSV(t *testing.T) {
//line stdlib/parse/parse_test.kuki:108
	records, err := parse.CSV("name,age\nalice,30\nbob,25")
//line stdlib/parse/parse_test.kuki:109
	test.AssertNoError(t, err)
//line stdlib/parse/parse_test.kuki:110
	test.AssertEqual(t, len(records), 3)
//line stdlib/parse/parse_test.kuki:111
	test.AssertEqual(t, records[0][0], "name")
//line stdlib/parse/parse_test.kuki:112
	test.AssertEqual(t, records[1][0], "alice")
}

//line stdlib/parse/parse_test.kuki:115
func TestCSVRecords(t *testing.T) {
//line stdlib/parse/parse_test.kuki:116
	rows, err := parse.CSVRecords("name,age\nalice,30\nbob,25")
//line stdlib/parse/parse_test.kuki:117
	test.AssertNoError(t, err)
//line stdlib/parse/parse_test.kuki:118
	test.AssertEqual(t, len(rows), 2)
//line stdlib/parse/parse_test.kuki:119
	test.AssertEqual(t, rows[0]["name"], "alice")
//line stdlib/parse/parse_test.kuki:120
	test.AssertEqual(t, rows[0]["age"], "30")
//line stdlib/parse/parse_test.kuki:121
	test.AssertEqual(t, rows[1]["name"], "bob")
}

//line stdlib/parse/parse_test.kuki:124
func TestLines(t *testing.T) {
//line stdlib/parse/parse_test.kuki:125
	lines := parse.Lines("foo\n\n  bar  \n\nbaz\n")
//line stdlib/parse/parse_test.kuki:126
	test.AssertEqual(t, len(lines), 3)
//line stdlib/parse/parse_test.kuki:127
	test.AssertEqual(t, lines[0], "foo")
//line stdlib/parse/parse_test.kuki:128
	test.AssertEqual(t, lines[1], "bar")
//line stdlib/parse/parse_test.kuki:129
	test.AssertEqual(t, lines[2], "baz")
}

//line stdlib/parse/parse_test.kuki:132
func TestDuration(t *testing.T) {
//line stdlib/parse/parse_test.kuki:133
	d, err := parse.Duration("1h30m")
//line stdlib/parse/parse_test.kuki:134
	test.AssertNoError(t, err)
//line stdlib/parse/parse_test.kuki:135
	test.AssertEqual(t, d, (90 * time.Minute))
}

//line stdlib/parse/parse_test.kuki:138
func TestURL(t *testing.T) {
//line stdlib/parse/parse_test.kuki:139
	u, err := parse.URL("https://example.com/api?q=1")
//line stdlib/parse/parse_test.kuki:140
	test.AssertNoError(t, err)
//line stdlib/parse/parse_test.kuki:141
	test.AssertEqual(t, u.Host, "example.com")
//line stdlib/parse/parse_test.kuki:142
	test.AssertEqual(t, u.Path, "/api")
}

//line stdlib/parse/parse_test.kuki:145
func TestQuery(t *testing.T) {
//line stdlib/parse/parse_test.kuki:146
	v, err := parse.Query("name=ada&age=30")
//line stdlib/parse/parse_test.kuki:147
	test.AssertNoError(t, err)
//line stdlib/parse/parse_test.kuki:148
	test.AssertEqual(t, v.Get("name"), "ada")
//line stdlib/parse/parse_test.kuki:149
	test.AssertEqual(t, v.Get("age"), "30")
}
