// Generated by Kukicha (requires Go 1.26+)

package webinfer

import (
	"encoding/base64"
	"fmt"
	kukijson "github.com/kukichalang/kukicha/stdlib/json"
	"github.com/kukichalang/infer/internal/errors"
	playwright "github.com/playwright-community/playwright-go"
	"os"
	"os/exec"
	"sync/atomic"
)

var ortWebCDN string = "https://cdn.jsdelivr.net/npm/onnxruntime-web@1.21.0/dist/ort.min.js"

var sessionCounter atomic.Int64

type Env struct {
	pw      *playwright.Playwright
	browser playwright.Browser
	page    playwright.Page
}

type Config struct {
	ep string
}

type Model struct {
	env         *Env
	sessionID   string
	inputNames  []string
	outputNames []string
	inputs      []Tensor
	outputs     []Tensor
}

type Tensor interface{ isTensor() }

type Float32 struct {
	shape []int64
	data  []float32
}

type Int64 struct {
	shape []int64
	data  []int64
}

func (Float32) isTensor() {}
func (Int64) isTensor()   {}

type ModelInfo struct {
	graphName string
	inputs    []IOInfo
	outputs   []IOInfo
}

type IOInfo struct {
	Name  string
	Dims  []int64
	Dtype string
}

type FeedEntry struct {
	Dtype string    `json:"dtype"`
	Shape []int64   `json:"shape"`
	Data  []float32 `json:"data"`
}

type ResultEntry struct {
	Dtype string    `json:"dtype"`
	Shape []int64   `json:"shape"`
	Data  []float32 `json:"data"`
}

func Init() (Env, error) {
	pw, runErr := playwright.Run()
	if runErr != nil {
		return Env{}, fmt.Errorf("start playwright: %w", runErr)
	}
	webnnArgs := []string{"--enable-features=WebMachineLearningNeuralNetwork,WebNNOnnxRuntime"}
	browser, launchErr := pw.Chromium.Launch(playwright.BrowserTypeLaunchOptions{Headless: playwright.Bool(true), Channel: playwright.String("chromium"), Args: webnnArgs})
	if launchErr != nil {
		pw.Stop()
		return Env{}, fmt.Errorf("launch browser: %w", launchErr)
	}
	page, pageErr := browser.NewPage()
	if pageErr != nil {
		browser.Close()
		pw.Stop()
		return Env{}, fmt.Errorf("open page: %w", pageErr)
	}
	loadErr := loadOrtWeb(page)
	if loadErr != nil {
		browser.Close()
		pw.Stop()
		return Env{}, fmt.Errorf("load onnxruntime-web: %w", loadErr)
	}
	return Env{pw: pw, browser: browser, page: page}, nil
}

func Cleanup(env Env) error {
	if env.browser != nil {
		env.browser.Close()
	}
	if env.pw != nil {
		return env.pw.Stop()
	}
	return nil
}

func IsAvailable() bool {
	browsers := []string{"chromium", "chromium-browser", "google-chrome", "google-chrome-stable"}
	for _, name := range browsers {
		_, err := exec.LookPath(name)
		if err == nil {
			return true
		}
	}
	return false
}

func Version(env Env) string {
	if env.page == nil {
		return ""
	}
	result, err := env.page.Evaluate("() => typeof ort !== 'undefined' ? '1.21.0' : ''")
	if err != nil {
		return ""
	}
	s, ok := result.(string)
	if !ok {
		return ""
	}
	return s
}

func New() Config {
	return Config{ep: "wasm"}
}

func EP(cfg Config, ep string) Config {
	cfg.ep = ep
	return cfg
}

func Load(cfg Config, env Env, path string, inputNames []string, outputNames []string, inputs []Tensor, outputs []Tensor) (Model, error) {
	modelBytes, readErr := os.ReadFile(path)
	if readErr != nil {
		return Model{}, fmt.Errorf("read model: %w", readErr)
	}
	modelB64 := base64.StdEncoding.EncodeToString(modelBytes)
	sessionID := fmt.Sprintf("s%d", sessionCounter.Add(1))
	ep := cfg.ep
	if ep == "" {
		ep = "wasm"
	}
	js := fmt.Sprintf("async () => { const b64 = %q; const raw = atob(b64); const bytes = new Uint8Array(raw.length); for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i); const session = await ort.InferenceSession.create(bytes.buffer, { executionProviders: [%q] }); window.__kuki = window.__kuki || {}; window.__kuki[%q] = session; return 'ok'; }", modelB64, ep, sessionID)
	_, evalErr := env.page.Evaluate(js)
	if evalErr != nil {
		return Model{}, fmt.Errorf("create session: %w", evalErr)
	}
	return Model{env: &env, sessionID: sessionID, inputNames: inputNames, outputNames: outputNames, inputs: inputs, outputs: outputs}, nil
}

func Close(model Model) error {
	if (model.env == nil) || (model.env.page == nil) {
		return nil
	}
	js := fmt.Sprintf("async () => { if (window.__kuki && window.__kuki[%q]) { await window.__kuki[%q].handler?.dispose?.(); delete window.__kuki[%q]; } return 'ok'; }", model.sessionID, model.sessionID, model.sessionID)
	_, err := model.env.page.Evaluate(js)
	return err
}

func Run(model Model) error {
	if (model.env == nil) || (model.env.page == nil) {
		return errors.New("model not loaded")
	}
	feeds := map[string]FeedEntry{}
	for i := range len(model.inputNames) {
		name := model.inputNames[i]
		if i < len(model.inputs) {
			switch t := model.inputs[i].(type) {
			case Float32:
				feeds[name] = FeedEntry{Dtype: "float32", Shape: t.shape, Data: t.data}
			case Int64:
				f32 := make([]float32, len(t.data))
				for j, v := range t.data {
					f32[j] = float32(v)
				}
				feeds[name] = FeedEntry{Dtype: "int64", Shape: t.shape, Data: f32}
			}
		}
	}
	feedsJSON, marshalErr := kukijson.Marshal(feeds)
	if marshalErr != nil {
		return fmt.Errorf("marshal feeds: %w", marshalErr)
	}
	outNamesJSON, _ := kukijson.Marshal(model.outputNames)
	js := fmt.Sprintf("async () => { const session = window.__kuki[%q]; const feedData = %s; const feeds = {}; for (const [name, info] of Object.entries(feedData)) { feeds[name] = new ort.Tensor(info.dtype, new Float32Array(info.data), info.shape); } const results = await session.run(feeds); const outNames = %s; const outputs = {}; for (const name of outNames) { const t = results[name]; if (t) outputs[name] = { dtype: t.type, shape: Array.from(t.dims), data: Array.from(t.data) }; } return JSON.stringify(outputs); }", model.sessionID, string(feedsJSON), string(outNamesJSON))
	raw, evalErr := model.env.page.Evaluate(js)
	if evalErr != nil {
		return fmt.Errorf("run inference: %w", evalErr)
	}
	rawStr, ok := raw.(string)
	if !ok {
		return errors.New("unexpected result type from browser")
	}
	resultMap := map[string]ResultEntry{}
	unmarshalErr := kukijson.Unmarshal([]byte(rawStr), &resultMap)
	if unmarshalErr != nil {
		return fmt.Errorf("parse results: %w", unmarshalErr)
	}
	for i := range len(model.outputNames) {
		name := model.outputNames[i]
		if i < len(model.outputs) {
			r, rok := resultMap[name]
			if rok {
				switch t := model.outputs[i].(type) {
				case Float32:
					t.data = r.Data
					t.shape = r.Shape
					model.outputs[i] = t
				case Int64:
					i64 := make([]int64, len(r.Data))
					for j, v := range r.Data {
						i64[j] = int64(v)
					}
					t.data = i64
					t.shape = r.Shape
					model.outputs[i] = t
				}
			}
		}
	}
	return nil
}

func Shape(dims ...int64) []int64 {
	result := make([]int64, len(dims))
	for i := range len(dims) {
		result[i] = dims[i]
	}
	return result
}

func NewFloat32(shape []int64, data []float32) (Tensor, error) {
	return Float32{shape: shape, data: data}, nil
}

func ZeroFloat32(shape []int64) (Tensor, error) {
	size := int64(1)
	for _, d := range shape {
		size = (size * d)
	}
	return Float32{shape: shape, data: make([]float32, size)}, nil
}

func NewInt64(shape []int64, data []int64) (Tensor, error) {
	return Int64{shape: shape, data: data}, nil
}

func ZeroInt64(shape []int64) (Tensor, error) {
	size := int64(1)
	for _, d := range shape {
		size = (size * d)
	}
	return Int64{shape: shape, data: make([]int64, size)}, nil
}

func Destroy(tensor Tensor) error {
	return nil
}

func GetFloat32(tensor Tensor) []float32 {
	switch t := tensor.(type) {
	case Float32:
		return t.data
	case Int64:
		return []float32{}
	default:
		_ = t
		return []float32{}
	}
}

func GetInt64(tensor Tensor) []int64 {
	switch t := tensor.(type) {
	case Float32:
		return []int64{}
	case Int64:
		return t.data
	default:
		_ = t
		return []int64{}
	}
}

func GetShape(tensor Tensor) []int64 {
	switch t := tensor.(type) {
	case Float32:
		return t.shape
	case Int64:
		return t.shape
	default:
		_ = t
		return []int64{}
	}
}

func Dtype(tensor Tensor) string {
	switch t := tensor.(type) {
	case Float32:
		return "float32"
	case Int64:
		return "int64"
	default:
		_ = t
		return "unknown"
	}
}

func Inspect(path string) (ModelInfo, error) {
	return ModelInfo{}, errors.New("webinfer: model inspection not supported (use infer.Inspect)")
}

func InputNames(info ModelInfo) []string {
	names := make([]string, len(info.inputs))
	for i := range len(info.inputs) {
		names[i] = info.inputs[i].Name
	}
	return names
}

func OutputNames(info ModelInfo) []string {
	names := make([]string, len(info.outputs))
	for i := range len(info.outputs) {
		names[i] = info.outputs[i].Name
	}
	return names
}

func GraphName(info ModelInfo) string {
	return info.graphName
}

func Inputs(info ModelInfo) []IOInfo {
	return info.inputs
}

func Outputs(info ModelInfo) []IOInfo {
	return info.outputs
}

func loadOrtWeb(page playwright.Page) error {
	url := ortWebCDN
	_, tagErr := page.AddScriptTag(playwright.PageAddScriptTagOptions{URL: &url})
	if tagErr != nil {
		return fmt.Errorf("add ort script: %w", tagErr)
	}
	result, err := page.Evaluate("() => typeof ort !== 'undefined'")
	if err != nil {
		return err
	}
	loaded, ok := result.(bool)
	if !ok || !loaded {
		return fmt.Errorf("ort not available after load")
	}
	return nil
}
